### PR TITLE
header --> original_header

### PR DESCRIPTION
**Pull request by maxpietsch**
I changed quite a lot of files in a semi-automatic way. So it would be good if somebody with more experience of the affected code could eyeball the diffs as these changes affect quite a lot of code.

### CODE REVIEW

**Comment by thijsdhollander** [comment]
Okay, I did a first check by

1) Switching to this branch and pulling everything.
2) Deleting the configuration file and entire build that I still had sitting there locally.
3) Nicely running ./configure and ./build again.

...so as to safely force everything to recompile.  And it does, so I reason there's no more occurrences of references to `.header()` in the image class.  I'll quickly go over the actual changes to see if I spot anything that shouldn't have been changed.

**Comment by thijsdhollander** [comment]
Went over each change in the mean time; at first sight, this looks all good.  A few ones I wanted to highlight though, so people are aware or can check if needed:

* In fixel_map.h, [line 88](https://github.com/MRtrix3/mrtrix3/blob/8620226c023db1f380e852ef62791d9c3ec56f9e/src/dwi/fixel_map.h#L88) : so it propagates to the Fixel_map class (but it makes sense)
* In src/gui/mrview/volume.h, [lines 97-98](https://github.com/MRtrix3/mrtrix3/blob/8620226c023db1f380e852ef62791d9c3ec56f9e/src/gui/mrview/volume.h#L97-L98) : @Lestropie , you're working on this one I guess; does it make sense over there?
* [It also applies to adapters now.](https://github.com/MRtrix3/mrtrix3/blob/8620226c023db1f380e852ef62791d9c3ec56f9e/lib/adapter/base.h#L52)
* [And to filters.](https://github.com/MRtrix3/mrtrix3/blob/8620226c023db1f380e852ef62791d9c3ec56f9e/lib/filter/base.h#L64-L66)
* And I'm not really sure myself if it's correct to use the original header in lines (102)[https://github.com/MRtrix3/mrtrix3/blob/8620226c023db1f380e852ef62791d9c3ec56f9e/lib/header.h#L102] and (132)[https://github.com/MRtrix3/mrtrix3/blob/8620226c023db1f380e852ef62791d9c3ec56f9e/lib/header.h#L132] of header.h .  So it's maybe best if someone else checked those 2 lines closely as well (the functionality hasn't changed as to before though).

Apart from that, after this stuff is merged into the actual updated_syntax branch: it's quite handy to explicitly see original_header everywhere where ... well ... it is.  So it's maybe a good thing to check whether that is definitely the wanted behaviour in all of those places, especially if the actual IO might use another type or other strides.  That's what tripped me up with the previous header() anyway. :-)

**Comment by jdtournier** [comment]
All seems sensible to me - including those last two question marks you had about the `lib/header.h` lines: they'll be necessary to allow constructing a `Header` from an `Image` or `Adapter`.

**Comment by thijsdhollander** [comment]
Aha, yes, that makes sense. :-)  Good, I'll merge things again in the updated_syntax branch before any other divergences happen.

**Pull request merged**
