### PR TITLE
Disable clang format for CLI code

### PR DESCRIPTION
**Pull request by Lestropie**
Partial reversion of #2652; though it's not "reverted" so much as replaced with manually formatted code.

Upon attempting to commence #2138 I found the reformatted `usage()` code so unbearable that I committed to refactoring all of the affected code.

I've tried to follow something resembling standards in terms of code formatting, including reducing text width even if column size isn't going to be enforced within these blocks of code. I also took the opportunity to tweak certain command documentation as I was going; shouldn't be anything controversial.

Could do with a fresh set of eyes over the manifest changes to the online command documentation just to be sure I've not broken anything.

### CODE REVIEW

**Comment by Lestropie** [comment]
Line count is a little gratuitous; will need to refactor and put the bulk of changes under the MRtrixBot account.

**Comment by daljit46** [comment]
LGTM, modulo the fact that sometimes you've missed a space in `// clang-format off`. I also recommend installing `pre-commit` locally and then run `pre-commit install` to install a git hook that will catch if you have code that is not formatted.

**Comment by Lestropie** [comment]
I've put off installing the pre-commit hook / format on save because there's a lot of branches that I still need to explicitly transition from pre-clang-format code. I do however need to get into the habit of running it explicitly. Not so concerned on commits like this one; it's moreso not wanting 200 clang-format-related commits on 100 different branches all making their way into the history.

**Comment by Lestropie** [comment]
Replaced by #2818.

**Pull request closed without merging**
