### PR TITLE
mrview: fix bug introduced in #1638

### LINKED ISSUE #1640: mrview volume navigation crash in dev
On second thought, it might be better to create an issue anyway, as it's otherwise quite hard to keep track of comments on a closed pull request... So this particular issue is described [here](https://github.com/MRtrix3/mrtrix3/pull/1638#issuecomment-511734061) and [here](https://github.com/MRtrix3/mrtrix3/pull/1638#issuecomment-511737901) a bit further.

### PR DESCRIPTION
**Pull request by jdtournier**
This should fix #1640...

### CODE REVIEW

**Comment by jdtournier** [comment]
Darn, looks like TravisCI has (finally) upgraded its systems to Ubuntu 16.04 - means we'll need to figure out the right packages to install and update the `travis.yml` to match...

**Comment by maxpietsch** [comment]
Since we're at it, I've unified the volume index handling across dimensions in the view tool in 6466ff8dfd6a6892439f3c77faa87f58bd31903f to address #1474 (in parts). Feel free to cherry-pick into this PR if you want to merge it all in one go.

**Comment by jdtournier** [comment]
@maxpietsch: I merged your changes (re #1474) with my additions onto this branch. Might be worth testing how well it handles very high dimensional data before merging though, if you have the time...?

**Comment by jdtournier** [comment]
OK, I just had a go with a 7D image - seems to work fine. Also had a go with 10D - we get a 3rd row, it all seems to work as it should... :crossed_fingers:

**Comment by jdtournier** [comment]
What this looks like with a 10D image... :grin:

Screenshot from 2019-07-18 14-41-02

**Comment by thijsdhollander** [comment]
I like the labels in the box; it looks really clean.

**Comment by jdtournier** [comment]
OK, I'll merge. We can fix any further issues as they arise.

**Comment by thijsdhollander** [comment]
Thanks. :+1:

**Pull request merged**
