### PR TITLE
Fix configure to support building with msys2 on windows.

### PR DESCRIPTION
**Pull request by bjeurissen**
Fix OS being reported as mingw_* instead of windows on msys2.
Fix configure to handle include paths relative to tmp.
Replace GL_ with gl:: to make OpenGL related stuff compile with Qt 4.

### CODE REVIEW

**Comment by Lestropie** [comment]
Compiled, built & run on my Windows box.

**Comment by jdtournier** [comment]
@Lestropie, can I just confirm this was using the standard Qt download as recommended on the wiki?

**Comment by Lestropie** [comment]
No, I'm currently on (this)[http://sourceforge.net/projects/qt64ng/files/qt/x86-64/5.4.1/mingw-4.9/sjlj/]; it's newer than what's offered by MinGW-builds, but looks like the project has crashed and burned.

**Comment by jdtournier** [comment]
@Lestropie, interesting that you're on Qt 5.4 - can you confirm that everything works as expected in MRView...? @bjeurissen & I are slightly concerned about things breaking with the move to Qt's `QOpenGLWidget` - seems to cause issues on his system. But then it could be because he's running a full 5K display, which most likely requires special handling due to HiDPI rendering...

**Comment by jdtournier** [comment]
OK, just gave it a shot on my Windows 7 VM - `configure` ran fine with the Qt 5.2.0 download as per the wiki. I think this is good to merge - the discussion about `QOpenGLWidget` doesn't have any impact on that.

**Comment by Lestropie** [comment]
Haven't had any issues specific to Qt 5.4.

**Comment by jdtournier** [comment]
Good to hear. 

One thing worth fixing though is that `./configure` falls over on my system due to a space in my user profile path... The only way around I could find was to rename my user folder - not entirely trivial. It would be good to fix that properly. The issue is I think with importing the `CFLAGS`, `LDFLAGS`, and `GSL_CFLAGS` & `GSL_LDFLAGS` environment variables - currently they're imported using the `shlex.split()` method, but that relies on spaces having been escaped properly when setting up the variables. I can't think of a trivial fix for this...

**Comment by bjeurissen** [comment]
Just tested the new configure using the wiki instructions and it works fine. So I guess this branch can be pulled then? Or should we also fix the issue with the spaces?

@jdtournier : have you tried using msys2? It could be that the spaces are not an issue there...

**Comment by jdtournier** [comment]
Just looking into the space in filename issue - there's really no trivial fix for this. Even if everything is escaped properly so that the arguments are properly split (I can verify they are immediately prior to executing the command), the compiler fails to find `zlib.h`, despite the correct folder being listed in the include path. 

I'll try msys2 now...

**Comment by jdtournier** [comment]
Yep, msys2 works a treat - no trouble running `./configure`. It's really good to work with too - much better than the git bash approach...

**Pull request merged**
