### PR TITLE
Improved fod integration

### LINKED ISSUE #312: FOD segmentation: Improve integral calculation
As discussed in #201; moving here so that the issue title actually reflects what needs to be done, and the label is more appropriate.

I think the most likely approach is going to be to perform something akin to the trapezoidal rule on the sphere, rather than just summing amplitudes. This should also take into account zero-crossings.

### PR DESCRIPTION
**Pull request by Lestropie**
This essentially fixes the orientation bias observed in the calculation of FOD integrals using the FMLS segmenter, by deriving a set of appropriate weights to apply to the sample points when summing. The sampling density is therefore returned to the 1281-direction set, avoiding the ~ 4x speed penalty observed with the temporary fix of moving to a 5000-direction set.

Closes #312.

### CODE REVIEW

**Comment by jdtournier** [comment]
Just for my own interest: does this use the approach I'd [outlined in this post](https://github.com/MRtrix3/mrtrix3/issues/201#issuecomment-89053428)...?

**Comment by Lestropie** [comment]
Close to. Rather than random SH functions, I generate the SH2A transform up to _lmax_ `LforN(num_directions)+2`, generate SH basis functions using vectors that are zero-filled except for one coefficient, and enforce that the integrals of all of those functions (when combined with a vector of sample point weighting coefficients) should be zero (except for the vector where it's the _l=0_ term that's non-zero).

**Comment by Lestropie** [comment]
Chalk up another win for automated testing.

**Comment by draffelt** [comment]
Thanks Trav :+1:

**Pull request merged**
