### PR TITLE
Read VTK as input streamlines, write RIB files (RenderMan)

### PR DESCRIPTION
**Pull request by blezek**
VTK input as a conversion back from [Slicer's white matter analysis package](https://github.com/SlicerDMRI/whitematteranalysis).  RIB export for [RenderMan rendering](https://renderman.pixar.com/view/renderman).

Unfortunately, only binary VTK input is read (which should be OK).

### CODE REVIEW

**Comment by jdtournier** [comment]
Thanks for all your efforts, @blezek. It might be worth point out that all this may change in future though, if #411 eventually gets addressed...

**Comment by blezek** [comment]
@jdtournier would be happy to port if #411 becomes standard.  I added a quick update to (optionally) write DEC colors to the RIB files.  Here are the results from RenderMan of some tracts (please @Lestropie no comments on my poor choice of algorithm! we're working on it).

sagittal0000

**Comment by Lestropie** [comment]
Definitely won't *all* be redundant with #411: A generic tractography file handler interface won't necessarily handle all of the "bells and whistles" (e.g. per-streamline colouring, generating cylinders), so some explicit handling in `tckconvert` will still be required.

**Comment by jdtournier** [comment]
Wasn't thinking any of this would be redundant - just that it might need to be reworked in the not too distant future. In the meantime, I guess we can merge this...?

**Comment by blezek** [comment]
I'd be happy to rework as needed, when the #411 is implemented.  Just let me know.

Could this be merged into master for the time being?

**Comment by Lestropie** [comment]
Merged since the code is very stand-alone so there shouldn't really be a risk of breaking other functionalities. Any specific issues in the import/export can be dealt with as they arise.

**Comment by Lestropie** [comment]
Whoops; looks like some "comparison between signed and unsigned integer" warnings in there. 

Also @blezek: I'd consider your additions to `tckconvert` substantial enough to warrant addition to the command's [author list](https://github.com/MRtrix3/mrtrix3/blob/master/cmd/tckconvert.cpp#L30-L32), which appears in the command's [help page](http://mrtrix.readthedocs.io/en/latest/reference/commands/tckconvert.html#tckconvert). Would you like your name to appear there?

**Comment by jdtournier** [comment]
> Whoops; looks like some "comparison between signed and unsigned integer" warnings in there.

I think these warnings predate these changes, I recently fixed those on `master` in [this commit](https://github.com/MRtrix3/mrtrix3/commit/db1dfe802ecfabbbe6fb51dc815f66a83b7b9ca9). I don't see any further warnings related to these changes... (?)

> Also @blezek: I'd consider your additions to tckconvert substantial enough to warrant addition to the command's author list, which appears in the command's help page. Would you like your name to appear there?

I'd second that. You've done plenty enough to get your name on it. :+1:

**Comment by blezek** [comment]
Just back from a week of camping and sailing...  @jdtournier & @Lestropie, I'd be happy if you would add my name to the author's list.  I'm thrilled that I can contribute and that you take my pull requests, makes my life easier to have my code in the main repo.

Please use `daniel.blezek@gmail.com` as my mail, and "Daniel Blezek" as name.

**Comment by jdtournier** [comment]
Done.

**Pull request merged**
