### PR TITLE
New function DWI::stash_DW_scheme()

### PR DESCRIPTION
**Pull request by Lestropie**
Finishing off #375 

Took the liberty of ensuring that it's the gradient table _used_ in processing that gets captured in the header, not just what was stored in the header (which could have been either absent or over-ruled by providing such information at the command-line).

Alternative function / keyval naming suggestions welcome.

### CODE REVIEW

**Comment by jdtournier** [comment]
Sounds good. Not sure about the key `basis_dw_scheme` though: the word 'basis' has other connotations, and doesn't really convey the sense that these were the directions used when processing the images. I'd rather use something like `dw_scheme_as_processed` or similar...

**Comment by thijsdhollander** [comment]
`original_dw_scheme`, or maybe `acquired_dw_scheme` ?  I agree with "basis" potentially being confusing.  I may be missing the message/point of `dw_scheme_as_processed` as well though: that sounds as if the DW scheme has been processed...? :confused:

**Comment by Lestropie** [comment]
`utilized_dw_scheme`? Or I'm happy with `original_dw_scheme`.

**Comment by jdtournier** [comment]
Yes, `dw_scheme_as_processed` might give slightly the wrong impression. I was shooting for `dw_scheme_as_used_in_processing`, but that's getting a little long-winded... Rob's `utilised_dw_scheme` is closer to the mark. How about `dw_scheme_used`...?

**Comment by Lestropie** [comment]
`prior_dw_scheme`?

**Comment by jdtournier** [comment]
Happy with `prior_dw_scheme`.

**Comment by thijsdhollander** [comment]
Sound good to me too. :+1:

**Pull request merged**
