### PR TITLE
Proposed solution for Eigen alignment issues

### PR DESCRIPTION
**Pull request by jdtournier**
carries on from #833, merging into `tag_0.3.16`

### CODE REVIEW

**Comment by jdtournier** [comment]
Merged #882 here to simplify later merge with #785 - refer to #882 for details on new `row()` method.

**Comment by jdtournier** [comment]
OK, this one is good to go, in sync with `tag_0.3.16`, and the only remaining test failing is `tckmap`. Feel free to merge with `tag_0.3.16` if you're happy with the changes.

**Comment by jdtournier** [comment]
OK, just merged `tag_0.3.16` into this branch, and all tests now succeed. Had to relax one of the tests on `dwidenoise`, but no big deal. Everyone happy to merge this?

**Comment by draffelt** [comment]
:+1:

**Pull request merged**
