### PR TITLE
Fix issues with MP-PCA denoising

### PR DESCRIPTION
**Pull request by dchristiaens**
These changes address two major issues with `dwidenoise`:

1. **MP matrix ratio**: This relates to a long standing issue, reported [here](http://community.mrtrix.org/t/dwi-denoising/1221), [here](http://community.mrtrix.org/t/denoising-residuals/1715), and [here](http://community.mrtrix.org/t/dwidenoise-correct-use/586/4), where we found that MP-PCA denoising performs poorly when the no. DWIs (M) is close to the total patch size (N). We also found that cases where M<N and M>N can lead to very different noise maps. We have discussed this issue with Jelle and agreed that the asymmetry stems from the definition of gamma = (M-P)/N in the paper, where P is the number of signal components. In recent work by a colleague at King's ([paper](https://arxiv.org/abs/1812.05954); Fig.4) we also found this definition of gamma to cause the biased noise estimates in near-square matrices, and proposed an alternative definition gamma = (M-P)/(N-P) that leads to more precise estimates. I have now also made this change in the `dwidenoise` code, pending Jelle's approval.

2. **Edge voxel handling**: As reported in #771, the original implementation skipped voxels at the edge of the image, potentially leading to different noise characteristics near the image boundaries when the mask extends to n=(patch size - 1)/2 voxels from the image bounding box. This is now addressed by using a non-centred patch in these voxels. The noise level is then effectively constant in n+1 voxels next to the image boundary, and the SVD spectrum is truncated at this noise level in all affected voxels.

Given that both of these are major changes to the output users can expect, I think this should be merged into a next release and properly documented in the changelog. I will draft in due time.

This PR is provisional while we discuss with NYU; don't merge yet.

### CODE REVIEW

**Comment by thijsdhollander** [comment]
> Given that both of these are major changes to the output users can expect, I think this should be merged into a next release and properly documented in the changelog. I will draft in due time.

:+1:  All good.  Yes, definitely via `dev` due to the changed output.

**Comment by dchristiaens** [comment]
Now that Lucilio's paper is out, I have done some work on `dwidenoise` to bring these changes to release. These updates add a capability to revert to the noise level estimator as used in Veraart et al. (2016), implemented with an option `-estimator` that is set by default to the improved formula introduced in Cordero-Grande et al. (2019).

There is one vital caveat though: the "legacy" option `-estimator Exp1` will match the current `master` branch *if and only if* the patch size (N) exceeds the number of DWIs (M) in the dataset (notwithstanding the changes in edge handling). This corresponds to the case evaluated in Jelle's paper. Part of the problem that triggered our search for a new estimator was that the formula's used for cases M < N and M > N in current master are incompatible. In other words, there was an asymmetry in the way both cases were treated, for instance leading to a different degree of denoising on matrices X and X^T in testing. I consider this a bug, and think it is unnecessarily complicated to maintain this behaviour since users who wish to have full "legacy" behaviour can achieve so through the `git` history. Therefore, the recent updates allow users to choose the noise level estimator used in Jelle's paper, rather than Lucilio's, but will not revert to the exact same output as before. This is thus a major update to the command, best merged in as part of the next release and documented clearly on the changelog.

For the same reason, we will also need to update the test data.

**Comment by dchristiaens** [comment]
Complex input data is now supported transparently. Input images with complex datatype will be processed as such. Their output will also be complex. Real input images, on the other hand, are processed as real so there is no performance penalty. It only took me three days to get this working... 🙄

The testing data has been updated. If Travis agrees this should be ready to merge.

**Comment by dchristiaens** [comment]
Updated user docs too. Merging and closing this PR.

**Pull request merged**
