### PR TITLE
Check emptiness of containers using empty()

### PR DESCRIPTION
**Pull request by daljit46**
As suggested by clang-tidy (see #2828), emptiness of containers should not be checked by using `size()` but we should  use `empty()`. Other than readability, this also has potential performance benefits as size() may not be constant-time.

This PR replaces all such instances of `size()` with `empty()` using `clang-tidy`.

### CODE REVIEW

**Comment by Lestropie** [comment]
@daljit46: The executable - library version mismatch issue reported in #2822 is now occurring within the CI; eg.:
```
bitset: [ERROR] executable was compiled for a different version of the MRtrix3 library!
bitset: [ERROR]   bitset version: 3.0.4-869-g3a2db299
bitset: [ERROR]   library version: 3.0.4-623-g4f3836b9-dirty
bitset: [ERROR] Running ./build again may correct error
```

**Comment by Lestropie** [comment]
If I had to guess, I'd say that because I'm dealing with a lot of pre-`cmake` PRs that I have to explicitly merge to `dev`, if I run the old `build` script, which generates `core/version.cpp`, then use `cmake`, the old `core/version.cpp` is getting used by the compiler rather than the version of that file that `cmake` is supposed to be generating.

**Comment by Lestropie** [comment]
Unfortunately `clang-tidy` doesn't like some of my rearrangement of string formation...
Some of them I'm a little surprised by; wondering if there's a way to instruct `clang-tidy` to be content with a given structure as long as it doesn't violate general rules, rather than forcing it to be *exactly* as `clang-tidy` determines? I don't want to disable `clang-format` for little things like this.

@daljit46:

1.  Can spreading string concatenation across multiple files be triggered to happen *only* if maximal columns is violated? I've been trying to newline string formation based on punctuation as it's more human-readable.
    eg.:
    ```
    --- ./src/dwi/tractography/SIFT/model.h	(original)
    +++ ./src/dwi/tractography/SIFT/model.h	(reformatted)
    @@ -157,8 +157,10 @@
             ++num_tracks;
             max_index = std::max(max_index, i);
           }
    -      WARN("Only " + str(num_tracks) + " tracks read from input track file;"
    -           " expected " + str(contributions.size()));
    +      WARN("Only " + str(num_tracks) +
    +           " tracks read from input track file;"
    +           " expected " +
    +           str(contributions.size()));
           contributions.resize(max_index + 1);
         }
       }
    ```

2.  If function parameters are spread across multiple lines and aligned using indentation so as not to exceed maximal width, is it possible to have `clang-tidy` accept that rather than newlining on the parenthesis?
    eg.:
    ```
    --- ./core/file/dicom/patient.cpp	(original)
    +++ ./core/file/dicom/patient.cpp	(reformatted)
    @@ -58,10 +58,8 @@
     }
     
     std::ostream &operator<<(std::ostream &stream, const Patient &item) {
    -  stream << MR::printf("  %-30s %-16s %10s\n",
    -                       item.name.c_str(),
    -                       format_ID(item.ID).c_str(),
    -                       format_date(item.DOB).c_str());
    +  stream << MR::printf(
    +      "  %-30s %-16s %10s\n", item.name.c_str(), format_ID(item.ID).c_str(), format_date(item.DOB).c_str());
     
    ```

3.  If composing a long boolean expression, and it can't fit on one line, I'd prefer to have one line per item rather than sometimes putting multiple on a line just because they fit:
    ```
    --- ./cmd/mrtransform.cpp	(original)
    +++ ./cmd/mrtransform.cpp	(reformatted)
    @@ -424,8 +423,7 @@
 
       // Detect FOD image
       const bool is_possible_fod_image =
    -      input_header.ndim() == 4 &&
    -      input_header.size(3) >= 6 &&
    +      input_header.ndim() == 4 && input_header.size(3) >= 6 &&
           input_header.size(3) == (int)Math::SH::NforL(Math::SH::LforN(input_header.size(3)));
```

**Comment by Lestropie** [comment]
@jdtournier: Given I tweaked some of the DICOM code (just collapsing unnecessary nested `if` statements), it might be worth running the private DICOM tests.

**Comment by jdtournier** [comment]
Going through the DICOM tests (which needed some tweaks to work from `dev`), there are a few failures, I'll look into them when I have a minute this afternoon.

**Comment by jdtournier** [comment]
OK, seems issues are already present in `dev` anyway. Investigations ongoing...

**Comment by jdtournier** [comment]
OK, that'll be due to #2691 being on `master`, but not on `dev`. Means it's time to merge `master` back to `dev`... Not looking forward to it, there's going to be a mountain of conflicts in there with all the cmake changes that have happened since the last time... :weary:

**Comment by Lestropie** [comment]
Merging so that this larger set of changes can be resolved against other PRs. If it turns out that the minor changes to the DICOM handling implemented in here do in fact cause problems (previously couldn't be verified because was awaiting #2893), that can be addressed in its own PR.

**Pull request merged**
