### PR TITLE
Final checks before 3.0.4 release 

### PR DESCRIPTION
**Pull request by jdtournier**

### CODE REVIEW

**Comment by jdtournier** [comment]
OK, both macOS package builds are failing... @bjeurissen, any chance you could look into what's going on with the [packaging of native package](https://github.com/MRtrix3/mrtrix3/actions/runs/3694289134)?

**Comment by bjeurissen** [comment]
> OK, both macOS package builds are failing... @bjeurissen, any chance you could look into what's going on with the [packaging of native package](https://github.com/MRtrix3/mrtrix3/actions/runs/3694289134)?

Also fails on my system:
```
EXEC <<
CMD: clang++ -mmacosx-version-min=10.13 -L/Users/ben/tmp/macos-installer/mrtrix3/lib -lz -ltiff -lpng -lfftw3 qt_moc.o qt.o -o qt /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5OpenGL.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Svg.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Widgets.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Gui.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Network.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Core.dylib -framework OpenGL -framework AGL
EXIT: 0
>>

EXEC <<
CMD: /var/folders/2w/lwh0qfqn1px8k_9v0_kgwd6c0000gn/T/tmpgw10nbn3/qt
EXIT: -6
STDERR:
dyld[26587]: Library not loaded: '@rpath/libQt5OpenGL.5.dylib'
  Referenced from: '/private/var/folders/2w/lwh0qfqn1px8k_9v0_kgwd6c0000gn/T/tmpgw10nbn3/qt'
  Reason: tried: '/usr/local/lib/libQt5OpenGL.5.dylib' (no such file), '/usr/lib/libQt5OpenGL.5.dylib' (no such file)
```

**Comment by bjeurissen** [comment]
> > OK, both macOS package builds are failing... @bjeurissen, any chance you could look into what's going on with the [packaging of native package](https://github.com/MRtrix3/mrtrix3/actions/runs/3694289134)?
> 
> Also fails on my system:
> 
> ```
> EXEC <<
> CMD: clang++ -mmacosx-version-min=10.13 -L/Users/ben/tmp/macos-installer/mrtrix3/lib -lz -ltiff -lpng -lfftw3 qt_moc.o qt.o -o qt /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5OpenGL.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Svg.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Widgets.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Gui.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Network.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Core.dylib -framework OpenGL -framework AGL
> EXIT: 0
> >>
> 
> EXEC <<
> CMD: /var/folders/2w/lwh0qfqn1px8k_9v0_kgwd6c0000gn/T/tmpgw10nbn3/qt
> EXIT: -6
> STDERR:
> dyld[26587]: Library not loaded: '@rpath/libQt5OpenGL.5.dylib'
>   Referenced from: '/private/var/folders/2w/lwh0qfqn1px8k_9v0_kgwd6c0000gn/T/tmpgw10nbn3/qt'
>   Reason: tried: '/usr/local/lib/libQt5OpenGL.5.dylib' (no such file), '/usr/lib/libQt5OpenGL.5.dylib' (no such file)
> ```

Is this a consequence of https://github.com/MRtrix3/mrtrix3/commit/6650a00115dc40bdf57c13c29d90a9bbca66cb9f ?

**Comment by bjeurissen** [comment]
> > > OK, both macOS package builds are failing... @bjeurissen, any chance you could look into what's going on with the [packaging of native package](https://github.com/MRtrix3/mrtrix3/actions/runs/3694289134)?
> > 
> > 
> > Also fails on my system:
> > ```
> > EXEC <<
> > CMD: clang++ -mmacosx-version-min=10.13 -L/Users/ben/tmp/macos-installer/mrtrix3/lib -lz -ltiff -lpng -lfftw3 qt_moc.o qt.o -o qt /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5OpenGL.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Svg.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Widgets.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Gui.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Network.dylib /Users/ben/tmp/macos-installer/mrtrix3/lib/libQt5Core.dylib -framework OpenGL -framework AGL
> > EXIT: 0
> > >>
> > 
> > EXEC <<
> > CMD: /var/folders/2w/lwh0qfqn1px8k_9v0_kgwd6c0000gn/T/tmpgw10nbn3/qt
> > EXIT: -6
> > STDERR:
> > dyld[26587]: Library not loaded: '@rpath/libQt5OpenGL.5.dylib'
> >   Referenced from: '/private/var/folders/2w/lwh0qfqn1px8k_9v0_kgwd6c0000gn/T/tmpgw10nbn3/qt'
> >   Reason: tried: '/usr/local/lib/libQt5OpenGL.5.dylib' (no such file), '/usr/lib/libQt5OpenGL.5.dylib' (no such file)
> > ```
> 
> Is this a consequence of [6650a00](https://github.com/MRtrix3/mrtrix3/commit/6650a00115dc40bdf57c13c29d90a9bbca66cb9f) ?

confirmed that this is where the issue was introduced

**Comment by bjeurissen** [comment]
Ok, workaround available as mentioned above. This will make sure the binaries can be built, but we might have to revert  (part of) https://github.com/MRtrix3/mrtrix3/commit/6650a00115dc40bdf57c13c29d90a9bbca66cb9f is a future release, to make sure others don't run into the same issue.

**Comment by jdtournier** [comment]
OK, thanks @bjeurissen! All packages have been built OK now... We can move to the next stage. But you're right, we'll need to figure out better solutions for that glitch fairly quickly...

**Comment by jdtournier** [comment]
Ok, spoke too soon. On Linux, the conda package installs fine, but fails to run due to failing to find Qt5.15. It looks like it's expecting to find that exact version, which must be what it was compiled with. But my conda setup was stuck with qt5.12, even following a full update. I expect we'll need to update the recipe to mandate Qt5.15... 

Not sure whether that also happens with the macOS conda package, but I expect it might. Probably best to rebuild both packages with the correct runtime dependencies specified. I'll get onto that ASAP.

**Comment by bjeurissen** [comment]
Might work out fine if you apply the same fix for the Linux conda package?

**Comment by bjeurissen** [comment]
The outstanding issues for the macOS package have been worked-around in: https://github.com/MRtrix3/macos-installer/tree/shebang_fix (both the python and the script version issues). If we merge that to master of macos-installer, we should be good.

**Comment by jdtournier** [comment]
Good to hear. Happy with that, feel free to go ahead!

**Pull request merged**
