### PR TITLE
Macosx touchpad fixes

### PR DESCRIPTION
**Pull request by jdtournier**
This fixes up the touchpad scrolling issue on MacOSX (although there is residual weirdness due to the way MacOSX emulates scroll acceleration with a regular mouse). It also fixes up pinch-to-zoom (this had been implemented previously, but never tested), and adds handling of panning using the touchpad - as far as I can tell, this is triggered by a long motionless single touch (not press) and drag. 

Calling all Macbook users to test these changes!

### CODE REVIEW

**Comment by chunhungyeh** [comment]
The functions for panning (with one finger), scrolling (with two fingers), and moving crosshair (with three fingers) are working pretty well. Very interesting! :)

The pinch-to-zoom one is quite hard to control as it goes very fast.

**Comment by jdtournier** [comment]
OK, thanks for the feedback. This is going to have to wait until someone with a Macbook shows up here for testing - everything worked fine on the Macbook Pro that I was testing this on last week, The `e->scaleFactor()` bit is supposed to return the fractional change in the zoom factor, which should really track what's on the touchpad exactly. If this is not reported correctly by Qt, I'm not too sure what the best way to fix it would be. @maxpietsch has  a Macbook Air - @chunhungyeh, is this what you have too...? Maybe it's specific to these models...

**Comment by jdtournier** [comment]
Just tested this on my ridiculously underpowered Windows 10 netbook: pinch to zoom works just as expected, both for the touchpad and the touchscreen. Can't figure out what the gesture is for panning on the touchpad, but  with the touchscreen, I can pan around with 2 fingers on the screen. :+1:

**Comment by chunhungyeh** [comment]
Mine is Macbook Pro (built in early 2013).

**Comment by thijsdhollander** [comment]
> Just tested this on my ridiculously underpowered Windows 10 netbook: pinch to zoom works just as expected, both for the touchpad and the touchscreen. Can't figure out what the gesture is for panning on the touchpad, but with the touchscreen, I can pan around with 2 fingers on the screen.

Ok, now I have a seriously good reason to install MRtrix on my good old first generation Surface. :smile:  Is there a gesture for scrolling (through slices)?

**Comment by jdtournier** [comment]
> Is there a gesture for scrolling (through slices)?

Couldn't find one. Problem being that scrolling is actually panning in most 2D applications...

**Comment by maxpietsch** [comment]
Turns out the zoom problem is due to a bug in qt's pinch function (since qt 5.4.1) which was fixed in qt 5.6.1: https://bugreports.qt.io/browse/QTBUG-48138

Happy to merge!

**Comment by jdtournier** [comment]
Cool! @chunhungyeh: any chance you could verify this? And merge if that fixes it for you too?

**Comment by chunhungyeh** [comment]
Tested: updating to Qt5.6.1 fixes the problem.

**Pull request merged**
