### PR TITLE
str() function: Fix for unsupported types

### PR DESCRIPTION
**Pull request by Lestropie**
Awaiting testing on Ubuntu 16.04, which fails compilation on current master: see [here](http://community.mrtrix.org/t/compile-error-on-ubuntu-16-04/183).

### CODE REVIEW

**Comment by thijsdhollander** [comment]
Slightly related, but maybe not worth a full blown issue: with all the Eigen shenanigans lately, should the installation instructions mention, or stress more clearly, that it's in peoples' best interests to use the latest non-beta version of Eigen?  It sounds trivial, but it seems some (linux) distributions may come with a pre-installed older version, and if people aren't confronted with an error at the `./configure` stage (because Eigen is in fact present), they may run into issues later on when compiling.  And that's even still a reasonably good scenario (it may be worse if things compile but there's significant bugs in an older or beta version of Eigen).

**Comment by jdtournier** [comment]
I'm not convinced the issue is that `Eigen::Transpose` lacks the `Scalar` typedef, as you mentioned in the community post - that shouldn't cause any ambiguity, the compiler should default to the standard implementation (return 0). I have a suspicion the problem might be that they've added a `value_type ` typedef to that class... I'd need to check, but if that's the case, it's going to be difficult to fix. In this case, we might need to check whether this is a change the Eigen devs intended to make long-term, or just a temporary glitch...

In the meantime, the changes here look sensible, although they might change behaviour a bit, forcing full precision in places where they weren't before? I wonder whether this might affect things a little... Stuff like the output of `mrinfo`, etc. - I remember there was an issue where subtle rounding errors caused the voxel size to show up as 2.4999999999 instead of 2.5 or something...

**Comment by thijsdhollander** [comment]
> I remember there was an issue where subtle rounding errors caused the voxel size to show up as 2.4999999999 instead of 2.5 or something.

About that: I still keep running into these kinds of things all the time.  The most notable place where this happens is actually in the `mrview` GUI, for many different numerical text boxes (i.e., things as simple as the window range).  Entering a number like "0.1", and then seeing it immediately changed to "0.0999999997" or "0.1000000003" or something upon hitting Enter or clicking in another field.  Same thing with certain parameters being either visualised in `mrinfo`, or actually being saved in headers (i.e., tracking parameters, etc...).

**Comment by jdtournier** [comment]
@thijsdhollander: I think the MRView issue is due to the way these changes are actually applied. When you change some of these parameters, this triggers a redraw, where the parameters are re-calculated based on everything else, and the UI is update to match. This is to allow changing these parameters using the mouse interactions or keyboard shortcuts as well, which are handled completely separately from the view tool (by necessity, the view too won't necessarily even exist by then).

For `mrinfo`, `tckinfo`, and the like, the issue is likely to be either double->float conversions happening somewhere, and/or other operations happening somewhere along the line - in the case of NIfTI for example, the transform is either scaled by the voxel size (if the sform) or stored as a quaternion (if the qfrom), as floats in both cases; so it requires some operations to compute the MRtrix3 internal representation...

**Comment by Lestropie** [comment]
> that shouldn't cause any ambiguity, the compiler should default to the standard implementation (return 0)

I'd have thought that on `master`, if neither `Scalar` nor `value_type` are defined, it would run the `std::numeric_limits<X>::max_digits10` version? I had assumed that would cause a compiler error. The change in 4a4d53a should force precision to zero for non-arithmetic types.

>  I have a suspicion the problem might be that they've added a value_type typedef to that class...

Having both `Scalar` and `value_type` defined would make sense in terms of the compiler error. But I don't see the latter anywhere in their beta code. I'll install the beta code and see if I can reproduce.

> The most notable place where this happens is actually in the mrview GUI, for many different numerical text boxes (i.e., things as simple as the window range).

#81 is related. For instance, if the user enters a value manually, the precision displayed should be based on the user entry; whereas if it's a sliding value, the precision should be based on the rate of change of the value per pixel.

**Comment by Lestropie** [comment]
Eigen 3.2.8:
```
namespace internal {
template<typename MatrixType>
struct traits<Transpose<MatrixType> > : traits<MatrixType>
{
  typedef typename MatrixType::Scalar Scalar;
  typedef typename nested<MatrixType>::type MatrixTypeNested;
  typedef typename remove_reference<MatrixTypeNested>::type MatrixTypeNestedPlain;
  typedef typename traits<MatrixType>::StorageKind StorageKind;
  typedef typename traits<MatrixType>::XprKind XprKind;
  enum {
    RowsAtCompileTime = MatrixType::ColsAtCompileTime,
    ColsAtCompileTime = MatrixType::RowsAtCompileTime,
    MaxRowsAtCompileTime = MatrixType::MaxColsAtCompileTime,
    MaxColsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
    FlagsLvalueBit = is_lvalue<MatrixType>::value ? LvalueBit : 0,
    Flags0 = MatrixTypeNestedPlain::Flags & ~(LvalueBit | NestByRefBit),
    Flags1 = Flags0 | FlagsLvalueBit,
    Flags = Flags1 ^ RowMajorBit,
    CoeffReadCost = MatrixTypeNestedPlain::CoeffReadCost,
    InnerStrideAtCompileTime = inner_stride_at_compile_time<MatrixType>::ret,
    OuterStrideAtCompileTime = outer_stride_at_compile_time<MatrixType>::ret
  };
};
}
```

Eigen 3.3 beta 1:
```
namespace internal {
template<typename MatrixType>
struct traits<Transpose<MatrixType> > : public traits<MatrixType>
{
  typedef typename ref_selector<MatrixType>::type MatrixTypeNested;
  typedef typename remove_reference<MatrixTypeNested>::type MatrixTypeNestedPlain;
  enum {
    RowsAtCompileTime = MatrixType::ColsAtCompileTime,
    ColsAtCompileTime = MatrixType::RowsAtCompileTime,
    MaxRowsAtCompileTime = MatrixType::MaxColsAtCompileTime,
    MaxColsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
    FlagsLvalueBit = is_lvalue<MatrixType>::value ? LvalueBit : 0,
    Flags0 = traits<MatrixTypeNestedPlain>::Flags & ~(LvalueBit | NestByRefBit),
    Flags1 = Flags0 | FlagsLvalueBit,
    Flags = Flags1 ^ RowMajorBit,
    InnerStrideAtCompileTime = inner_stride_at_compile_time<MatrixType>::ret,
    OuterStrideAtCompileTime = outer_stride_at_compile_time<MatrixType>::ret
  };
};
}
```

\o/

**Comment by jdtournier** [comment]
> I'd have thought that on master, if neither Scalar nor value_type are defined, it would run the std::numeric_limits<X>::max_digits10 version? I had assumed that would cause a compiler error. 

It does run `std::numeric_limits<X>::max_digits10()`, but that shouldn't cause a compiler error, since [the non-specialised version of that function returns zero](http://en.cppreference.com/w/cpp/types/numeric_limits/max_digits10). So thinking about it, it seems the change in this pull request shouldn't make any difference...(?)

> Having both Scalar and value_type defined would make sense in terms of the compiler error. But I don't see the latter anywhere in their beta code.

Maybe from an inherited class...?

**Comment by Lestropie** [comment]
> It does run std::numeric_limits<X>::max_digits10(), but that shouldn't cause a compiler error, since the non-specialised version of that function returns zero. So thinking about it, it seems the change in this pull request shouldn't make any difference...(?)

Suspect so. It's more explicit, but nothing a code comment couldn't have solved.

> Maybe from an inherited class...?

It's in there somewhere. This compiles:
```
auto temp = response.transpose();
typename decltype(temp)::value_type temp2;
```
See 7f055ce for proposed fix.

**Comment by jdtournier** [comment]
Yes, I was thinking something like this latest commit might be the simplest fix... Happy with that.

**Comment by Lestropie** [comment]
Merged; @thijsdhollander Feel free to open another issue RE: setting precisions if you want. But we'd need to decide whether to reduce the default precision for `default_type`, or go through and explicitly provide a precision in those cases where 15 digits is not desirable.

(From memory running `str()` with a precision of 6 will change 2.4999999999 to 2.5 rather than 2.50000)

**Comment by Lestropie** [comment]
Just noting this for later: At least on my Windows box, `str()` seems to be setting 6 decimal places rather than 6 significant figures for floats, which is then highlighting rounding errors compared to older code.

**Pull request merged**
