### PR TITLE
Container recipe updates following 3.0.3 release

### PR DESCRIPTION
**Pull request by Lestropie**
Pairs with MRtrix3/containers#21.

Plan is to push update to `latest` tag on DockerHub in order to make the fix to #2360 available.

Note that this update does *not* address the additional dependencies that will need to be satisfied in order to resolve #2279 (addition of container recipes) with #2197 (new `dwi2mask`).

Instructions on DockerHub will also need to be updated to reflect expectation of obtaining file `fslinstaller.py`.

### CODE REVIEW

**Comment by Lestropie** [comment]
I have checked that both Docker and Singularity containers build, and execute `dwifslpreproc` including the flag that was causing failure in #2360.

Unusually, I found now that when I tried to use the Singularity container [via direct invocation](https://mrtrix.readthedocs.io/en/3.0.3/installation/using_containers.html#id1), i.e. "`MRtrix3.sif mrinfo file.mif`", it didn't work, I would instead get the help page for the *MRtrix3* command. The change in 489bffe seems to deal with this.

I have one more small modification to test before proposing, then will seek review on this so that I can move on cleanly to #2428 and #2388.

**Comment by Lestropie** [comment]
Okay, final thing I wanted to experiment with (#2458) did not work as initially intended, so I'm not going to add anything to this PR. I'll look into a solution for that separately, it's not requisite for `3.0.4`. So seeking review.

**Comment by Lestropie** [comment]
As of a635c0d I get warning-less `mrview` execution on both Docker and Singularity (built both from `Singularity` recipe file and from conversion from DockerHub). If anybody wants to test on a different system, in addition to the code here you can try `docker://mrtrix3/mrtrix3:test_3.0.4`.

**Comment by Lestropie** [comment]
Turns out I'm having a bunch of problems getting `mrview` working on Xubuntu 20.04 that I didn't have previously. Could not get it working on Docker or Singularity, on 3.0.3 or what will become 3.0.4 (including suggested changes in the documentation), and regardless of how the Singularity container was built. So I need to keep experimenting here. Not sure what's changed.

Quick observation:

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```
can seemingly be fixed with:
```
export LIBGL_ALWAYS_INDIRECT=1
```

**Comment by Lestropie** [comment]
On my Arch Linux laptop, can confirm `mrview` works without error for both Docker and Singularity (regardless of whether the latter was built from the Singularity recipe file or from the Dockerhub container). However my Xubuntu desktop at work failed across the board. Would very much appreciate an independent test to find out which of these is the odd one out.

**Comment by Lestropie** [comment]
The system on which I was having trouble with container-executed `mrview` is now dead. So in the absence of anyone independently reproducing the same issue, I can only advocate for merging this and re-assessing if any user reports an issue with `3.0.4`.

**Review by jdtournier — APPROVED** [review]

**Pull request merged**
