### PR TITLE
mrpad transform fix, take 2

### PR DESCRIPTION
**Pull request by jdtournier**
This should fix the issues in #1500 - but requires an explicit branch for the merge. In the spirit of #1482, I've  re-used the original `mrpad_transform_fix` branch for this, and added the equivalent branch to manage the merge commit on the `test_data` repo. Hopefully this'll all go to plan...

### CODE REVIEW

**Comment by jdtournier** [comment]
Failed at the first hurdle... OK, rebasing to `dev` now.

**Comment by jdtournier** [comment]
OK, wasn't expecting that one... Failing in the Python3 pylint tests:
```
## testing "lib/mrtrix3/_5ttgen/gif.py"...
 [ ERROR ]
************* Module mrtrix3._5ttgen.gif
lib/mrtrix3/_5ttgen/gif.py:21:2: W0611: Unused import os (unused-import)
lib/mrtrix3/_5ttgen/gif.py:21:2: W0611: Unused import os (unused-import)
lib/mrtrix3/_5ttgen/gif.py:28:2: W0611: Unused import os (unused-import)
```
We can probably just remove the [first of these](https://github.com/MRtrix3/mrtrix3/blob/dev/lib/mrtrix3/_5ttgen/gif.py#L21) (line 21), since it genuinely is unused. But the [second one](https://github.com/MRtrix3/mrtrix3/blob/dev/lib/mrtrix3/_5ttgen/gif.py#L28) (line 28) is [used within the call](https://github.com/MRtrix3/mrtrix3/blob/dev/lib/mrtrix3/_5ttgen/gif.py#L47). I'm not sure why it's complaining, but I'm guessing the `os` module has by that stage already been imported by the main script? It seems odd in any event... 

Also odd is the fact that it passed its tests before... Maybe this is a new update from `pylint`? Also, the line is currently guarded by a `#pylint: disable=unused-variable` comment, but the message suggests the way to disable it is with an `unused-import` option. Again, maybe it's a new one? In which case, it'll be a right pain to manage if that option didn't exist in previous versions...

**Comment by jdtournier** [comment]
At least all the other tests pass OK. I've just tried to fix the GIF `5ttgen` algorithm. Turns out the issue on line 28 was probably related to the `sys` module being unused, but there's probably a glitch in `pylint` that causes it to blame the first module listed on the import line... In any event, I'd like to make sure @Lestropie is happy with those changes...

**Comment by jdtournier** [comment]
OK, I've now merged, I'm pretty sure those [changes to the GIF algorithm](https://github.com/MRtrix3/mrtrix3/pull/1505/files#diff-9690071d65e7b7f9d7e8fcf87a32bab4) are OK - @Lestropie: feel free to fix this if I've messed it up...

**Comment by Lestropie** [comment]
> In which case, it'll be a right pain to manage if that option didn't exist in previous versions...

Shouldn't be: I've endeavoured to use such directives only when absolutely necessary in my own code.

> Turns out the issue on line 28 was probably related to the `sys` module being unused, but there's probably a glitch in `pylint` that causes it to blame the first module listed on the import line

Can confirm that `pylint` does indeed do this.

**Comment by Lestropie** [comment]
> +1 −0		population_template/in/s1.mif.gz
> +1 −0		population_template/in/s2.mif.gz

Seems you have managed to revert [this commit](https://github.com/MRtrix3/test_data/commit/80fabad95d9f5985e544c3fc8ee8420218c39a46) in the data module. See corresponding [test on `dev`](https://github.com/MRtrix3/mrtrix3/blob/dev/testing/tests/population_template).

**Comment by jdtournier** [comment]
> Seems you have managed to revert this commit in the data module.

I did see it, but it's on the `appveyor` branch - not merged to `dev` or `master`, so I left it alone... What my history shows:
```
*   583c713 - (origin/mrpad_transform_fix) Merge remote-tracking branch 'origin/master' into dev (25 hours ago) <J-Donald Tournier>
|\  
| * 179845c - (HEAD, origin/master, origin/HEAD) mrpad: fix missing test data change (6 days ago) <Max Pietsch>
| * 9279f56 - mrpad: header transform bugfix requires changed test data (6 days ago) <Max Pietsch>
| | *   cf6c5fa - (origin/appveyor) Merge commit 'f6f225f' into appveyor (4 months ago) <Robert Smith>
| | |\  
| |_|/  
|/| |   
* | | f6f225f - (origin/dev) fixel2voxel: Update data to reflect #1352 (5 months ago) <Robert Smith>
|/ /  
*   583c713 - (origin/mrpad_transform_fix) Merge remote-tracking branch 'origin/master' into dev (25 hours ago) <J-Donald Tournier>
```

I've now just merged the `mrpad_transform_fix` branch into `dev` though (to match the corresponding merge on the main repo). I'm not sure what to do with this `appveyor` branch though: is the corresponding change to the testing already on `dev`...?

**Pull request merged**
