### PR TITLE
mrview: go to volume slot #848

### PR DESCRIPTION
**Pull request by maxpietsch**
Added "go to volume..." entry in the image menu. issue: #848

### CODE REVIEW

**Comment by thijsdhollander** [comment]
@maxpietsch I really like this addition, even just for the fact that it can be accessed with a shortcut key combination, and the number field gets selected automatically; so everything can be done keyboard-wise.  Awesome!

Only thing is the key combination itself: I appreciate you went for `Shift+G` because `G` was already taken by the background colour selection one.  But the latter is definitely a less basic operation (and people surely haven't got too used to the key for that one, I reckon), and one that you typically wouldn't do as frequently as switching volumes in a large dataset.  So what I'd suggest is:

- Tie the new "Go to volume..." to just `G`
- If the background one is going to become a `Shift+...` anyway, tie it to `Shift+B` (makes more sense than `G` even, but simple `B` in that case is already taken by the colour bar, which is still a more basic toggle than the background colour)

Just typing `G`, a number and hitting `Enter` would definitely make this a really handy thing that I'd use frequently, even in smaller datasets, to go to a specific volume across `mrview` sessions. :+1:

**Comment by thijsdhollander** [comment]
Small addition: `Shift+G` could even become a "Go to volume group...`, would be very consistent with the keys for next/previous volume vs volume group.

**Comment by jdtournier** [comment]
I like the G / Shift-G shortcut idea for volume / volume group control. That was always a funny shortcut to set the background colour anyway... Not sure what to assign that action to now, maybe U for 'underlay colour'? We could also modify the text in the menu to match...?

**Comment by maxpietsch** [comment]
Happy with `G` and `shift + g`. Do we need a shortcut for the background colour? Doesn't strike me to be a thing that one would need constantly.

**Comment by jdtournier** [comment]
> Do we need a shortcut for the background colour? Doesn't strike me to be a thing that one would need constantly.

I was having the same thought... Happy to drop the shortcut altogether if everyone is happy with that.

**Comment by maxpietsch** [comment]
Done. Shortcuts: `g` and `shift+g`. for volume and volume group. Removed background colour shortcut.

**Comment by maxpietsch** [comment]
In case anyone want the background shortcut back: background could become canvas: `Shift+c` is still free I think.

**Comment by maxpietsch** [comment]
Feel free to press the button before master changes again :)

**Pull request merged**
