### PR TITLE
mrview: fix volume render on ATI hardware

### LINKED ISSUE #285: partial screen refresh with ATI hardware on Linux
The screen refresh is often incomplete when running MRView on ATI hardware - only parts of the display are actually updated, and different bits get updated at different times. I've now seen it with Qt4 & Qt5, and on Ubuntu 12.04 & 14.04. I'll try running a debug version on one of those systems, see if there's anything obvious.

### PR DESCRIPTION
**Pull request by jdtournier**
Fixes #285. After quite a bit of investigating, problem turned out to be that ATI hardware/drivers can't handle it when the data for each vertex in a vertex buffer object are not aligned at 32-bit boundaries.

Suggesting merging to `master` since this fixes a (very) long-standing bug that's been eating away at me for years... And it's very unlikely to cause issues anyway.

### CODE REVIEW

**Comment by jdtournier** [comment]
Thanks for all the testing. Ideally, I'd like that tested on macOS and Windows, and also on other ATI systems if anyone had access to one?

**Comment by maxpietsch** [comment]
All good in macOS with an Intel HD Graphics 3000 OpenGL Engine, GL version: 3.3 INTEL-10.2.37.

**Comment by bjeurissen** [comment]
Tested on my iMac using an ATI-card:
```
mrview: [INFO] GL renderer:  AMD Radeon R9 M295X OpenGL Engine
mrview: [INFO] GL version:   4.1 ATI-1.51.8
mrview: [INFO] GL vendor:    ATI Technologies Inc.
```

No apparent issues!

**Comment by jdtournier** [comment]
Yep! Thanks to everyone for all the testing! I'll merge once the testing completes...

**Comment by jdtournier** [comment]
TravisCI gets stuck with this:

> The job exceeded the maximum time limit for jobs, and has been terminated.

Already tried restarting. Any ideas...?

**Comment by Lestropie** [comment]
Had that once recently myself, in that case just re-running that one job resulted in success; so I restarted it again. Not sure if it has to do with the TravisCI move to Trusty. We might need to ask Travis for more build time...

**Comment by jdtournier** [comment]
Yes, weird... Maybe some glitch with TravisCI that we'll have to keep an eye on. Seems OK now though.

**Pull request merged**
