### PR TITLE
mrview: Fix compilation warnings on Qt 5.15

### PR DESCRIPTION
**Pull request by Lestropie**
Attempted fix for CI testing failures on MacOSX, seemingly due to use of Qt 5.15.

### CODE REVIEW

**Comment by Lestropie** [comment]
This now passes CI, and will need to be merged prior to any other CIs, but need to make sure that the `mrview` interface still works as expected using both mouse and touchpad on both Qt 5.15 and earlier. I don't have a mouse on me and don't have advanced touchpad features set up.

**Comment by Lestropie** [comment]
Note: Seems to be a partial duplicate of 8322af1c, which wasn't PR'd. Solutions there may be fractionally cleaner, as well as more extensive.

**Comment by chunhungyeh** [comment]
Tested on my macOS laptop with Qt 5.15.0, 5.14.1 and 5.14.2, I did not observe any malfunction when using a mouse or trackpad.

**Comment by jdtournier** [comment]
Turns out I'd made very similar changes recently for the same reason, and pushed to the `qt_fix_obsolete_warnings` branch without creating a pull request... Sorry!

I've taken a slightly different strategy, and there's also a few other fixes in there, so I've merged my changes on top of yours. It should all work out... 🤞

**Comment by jdtournier** [comment]
OK, just noted that you'd already seen my non-PR commit. What about my changes did you think was not sufficiently clean?

**Comment by Lestropie** [comment]
> What about my changes did you think was not sufficiently clean?

Other way around:

> 8322af1 ... Solutions there may be fractionally cleaner

**Comment by jdtournier** [comment]
>Other way around:

Doh! Sorry...

**Comment by jdtournier** [comment]
Closed with #2080

**Pull request closed without merging**
