### PR TITLE
Fix compilation of big object files in MINGW debug builds

### PR DESCRIPTION
**Pull request by daljit46**
Addresses #2896

### CODE REVIEW

**Comment by Lestropie** [comment]
Overcame the original issue, but did not compile successfully. Get a massive compiler output; here's some random snippets:

```
C:/msys64/mingw64/bin/ld: core/CMakeFiles/mrtrix-core.dir/math/stats/glm.cpp.obj:glm.cpp:(.text$_ZN5Eigen15PlainObjectBaseINS_6MatrixIdLin1ELin1ELi1ELin1ELin1EEEE12_set_noaliasINS_7ProductINS_9TransposeINS1_IdLin1ELin1ELi0ELin1ELin1EEEEENS_15DiagonalWrapperIKNS1_IdLin1ELi1ELi0ELin1ELi1EEEEELi1EEEEERS2_RKNS_9DenseBaseIT_EE+0x4b): undefined reference to `void Eigen::internal::call_assignment_no_alias<Eigen::Matrix<double, -1, -1, 1, -1, -1>, Eigen::Product<Eigen::Transpose<Eigen::Matrix<double, -1, -1, 0, -1, -1> >, Eigen::DiagonalWrapper<Eigen::Matrix<double, -1, 1, 0, -1, 1> const>, 1>, Eigen::internal::assign_op<double, double> >(Eigen::Matrix<double, -1, -1, 1, -1, -1>&, Eigen::Product<Eigen::Transpose<Eigen::Matrix<double, -1, -1, 0, -1, -1> >, Eigen::DiagonalWrapper<Eigen::Matrix<double, -1, 1, 0, -1, 1> const>, 1> const&, Eigen::internal::assign_op<double, double> const&)'
...
C:/msys64/mingw64/bin/ld: core/CMakeFiles/mrtrix-core.dir/math/stats/glm.cpp.obj:glm.cpp:(.text$_ZNK5Eigen9DenseBaseINS_13CwiseBinaryOpINS_8internal22scalar_conj_product_opIddEEKNS_9TransposeIKNS_5BlockIKNS6_IKNS_7ProductINS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEENS_7InverseINS7_INS7_INS5_IS9_EENS_15DiagonalWrapperIKNS8_IdLin1ELi1ELi0ELin1ELi1EEEEELi1EEES9_Li0EEEEELi0EEELi1ELin1ELb0EEELi1ELin1ELb1EEEEEKNS6_IKNS5_IKS9_EELin1ELi1ELb0EEEEEE5reduxINS2_13scalar_sum_opIddEEEEdRKT_+0x39): undefined reference to `Eigen::EigenBase<Eigen::CwiseBinaryOp<Eigen::internal::scalar_conj_product_op<double, double>, Eigen::Transpose<Eigen::Block<Eigen::Block<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Inverse<Eigen::Product<Eigen::Product<Eigen::Transpose<Eigen::Matrix<double, -1, -1, 0, -1, -1> >, Eigen::DiagonalWrapper<Eigen::Matrix<double, -1, 1, 0, -1, 1> const>, 1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, 0> const, 1, -1, false> const, 1, -1, true> const> const, Eigen::Block<Eigen::Transpose<Eigen::Matrix<double, -1, -1, 0, -1, -1> const> const, -1, 1, false> const> >::cols() const'
...
C:/msys64/mingw64/bin/ld: core/CMakeFiles/mrtrix-core.dir/math/stats/glm.cpp.obj:glm.cpp:(.text$_ZN5Eigen8internal15unary_evaluatorINS_9TransposeIKNS_5BlockIKNS_7ProductINS4_INS2_INS_13MatrixWrapperINS_5ArrayIdLin1ELi1ELi0ELin1ELi1EEEEEEENS2_IKNS_6MatrixIdLin1ELin1ELi0ELin1ELin1EEEEELi0EEENS_7InverseINS4_INS4_ISB_NSF_INS4_INS4_INS2_ISB_EENS_15DiagonalWrapperIKNSA_IdLin1ELi1ELi0ELin1ELi1EEEEELi1EEESB_Li0EEEEELi0EEESD_Li0EEEEELi0EEELi1ELin1ELb1EEEEENS0_10IndexBasedEdED2Ev+0x14): undefined reference to `Eigen::internal::evaluator<Eigen::Block<Eigen::Product<Eigen::Product<Eigen::Transpose<Eigen::MatrixWrapper<Eigen::Array<double, -1, 1, 0, -1, 1> > >, Eigen::Transpose<Eigen::Matrix<double, -1, -1, 0, -1, -1> const>, 0>, Eigen::Inverse<Eigen::Product<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Inverse<Eigen::Product<Eigen::Product<Eigen::Transpose<Eigen::Matrix<double, -1, -1, 0, -1, -1> >, Eigen::DiagonalWrapper<Eigen::Matrix<double, -1, 1, 0, -1, 1> const>, 1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, 0>, Eigen::Transpose<Eigen::Matrix<double, -1, -1, 0, -1, -1> const>, 0> >, 0> const, 1, -1, true> const>::~evaluator()'
...
C:/msys64/mingw64/bin/ld: core/CMakeFiles/mrtrix-core.dir/math/stats/glm.cpp.obj:glm.cpp:(.text$_ZSt6fill_nIPjxjET_S1_T0_RKT1_+0x44): undefined reference to `unsigned int* std::__fill_n_a<unsigned int*, long long, unsigned int>(unsigned int*, long long, unsigned int const&, std::random_access_iterator_tag)'
...
C:/msys64/mingw64/bin/ld: core/CMakeFiles/mrtrix-core.dir/math/stats/glm.cpp.obj:glm.cpp:(.rdata$_ZTIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEE+0x10): undefined reference to `typeinfo for Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >'
core/CMakeFiles/mrtrix-core.dir/math/stats/glm.cpp.obj:glm.cpp:(.pdata$_ZNK5Eigen7MapBaseINS_5BlockINS_5ArrayIdLin1ELin1ELi0ELin1ELin1EEELin1ELi1ELb1EEELi0EE4rowsEv+0x8): relocation truncated to fit: IMAGE_REL_AMD64_ADDR32NB against `.xdata$_ZNK5Eigen7MapBaseINS_5BlockINS_5ArrayIdLin1ELin1ELi0ELin1ELin1EEELin1ELi1ELb1EEELi0EE4rowsEv'
...
core/CMakeFiles/mrtrix-core.dir/math/stats/glm.cpp.obj:glm.cpp:(.pdata$_ZNK5Eigen15DenseCoeffsBaseINS_12CwiseUnaryOpINS_8internal17scalar_inverse_opIdEEKNS_5BlockINS_5ArrayIdLin1ELin1ELi0ELin1ELin1EEELin1ELi1ELb1EEEEELi0EE5coeffEx+0x4): relocation truncated to fit: IMAGE_REL_AMD64_ADDR32NB against `.text$_ZNK5Eigen15DenseCoeffsBaseINS_12CwiseUnaryOpINS_8internal17scalar_inverse_opIdEEKNS_5BlockINS_5ArrayIdLin1ELin1ELi0ELin1ELin1EEELin1ELi1ELb1EEEEELi0EE5coeffEx'
core/CMakeFiles/mrtrix-core.dir/math/stats/glm.cpp.obj:glm.cpp:(.pdata$_ZNK5Eigen15DenseCoeffsBaseINS_12CwiseUnaryOpINS_8internal17scalar_inverse_opIdEEKNS_5BlockINS_5ArrayIdLin1ELin1ELi0ELin1ELin1EEELin1ELi1ELb1EEEEELi0EE5coeffEx+0x8): additional relocation overflows omitted from the output
```

Re-running multiple times, it's consistently `math/stats/glm.cpp` that fails.

While I think it might be a different error message to what I've seen previously, wondering if it could be a 2GB / 4GB RAM filesystem limit.

**Comment by daljit46** [comment]
Very strange, I just tried with a fresh installation of MSYS2 and I didn't encounter this problem. This could potentially be because of using the 32-bit version of some package (possibly `binutils`). I can see that on master we're also using `D_FILE_OFFSET_BITS=64`, so perhaps you try that (`-DCMAKE_CXX_FLAGS="D_FILE_OFFSET_BITS=64"`)?

**Comment by daljit46** [comment]
Just to make sure I created a test repo to build mrtrix3 in debug mode [here](https://github.com/daljit46/mrtrix3-debug-mingw-test/blob/main/.github/workflows/build.yml) and it seems [to work](https://github.com/daljit46/mrtrix3-debug-mingw-test/actions). So I'm inclined to think that there is something peculiar with your MSYS2 installation that's causing the problem. Could you send me the entire verbose build log (`--verbose` during build)? Teams or Pastebin would work.

**Review by Lestropie — APPROVED** [review]
Have come back to this branch and it now works with an freshly updated MSYS2.

**Pull request merged**
