### PR TITLE
docs: add first line of description to command list

### PR DESCRIPTION
**Pull request by jdtournier**
Addresses #904.

### CODE REVIEW

**Comment by jdtournier** [comment]
As before, I used the `doctest` branch - results can be previewed [here](http://mrtrix.readthedocs.io/en/doctest/reference/commands_list.html).

**Comment by thijsdhollander** [comment]
stop-the-presses

Didn't @Lestropie already tackle this in the `tag_0.3.16` branch with a proper `SYNOPSIS` field, as well as new `USAGE` and `DESCRIPTION` fields?  ...results of which can be viewed [here](http://mrtrix.readthedocs.io/en/tag_0.3.16/reference/commands_list.html)... as well as on individual commands' pages, e.g. [see here](http://mrtrix.readthedocs.io/en/tag_0.3.16/reference/commands/dwi2fod.html). (and the same for the list of scripts and individual scripts' pages)

**Comment by jdtournier** [comment]
Oh dear... It does seem I have been wasting my time. It's high time we merged this `tag_0.3.15` Frankenstein already.

I'll can this pull request then...

**Comment by Lestropie** [comment]
Yes, I mentioned the idea in #881 but never generated an issue for that alone. I thought I drew attention to it at some point when it was done; don't recall.

Given this and #934, there might need to be a little more discipline around issue listing / assignment / updates. I'm particularly guilty in that there were a lot of things I knew I would need to do for the Stanford coding sprint, many of which I listed explicitly but some things just kind of got done when they were needed; #934 was probably one of the latter. The period of time that `0.3.16` has been listed (opened September last year!) is contributing, as is the fact that issues closed via commit messages don't actually get closed until the relevant commit is merged to master, so there's a lot sitting there listed as "open" that are actually already done.

Open to ideas or suggestions of things we can try to do to avoid this sort of thing (without getting buried in micro-management). It really does suck when work gets unnecessarily duplicated.

**Comment by jdtournier** [comment]
> Yes, I mentioned the idea in #881 but never generated an issue for that alone. 

Nope, you did: #904 ... which is why I thought I'd give it a crack. No harm done, it didn't take long. 

> It really does suck when work gets unnecessarily duplicated.

Sure, but it's not such a big deal for a small changeset like this. It's going to happen from time to time. It would be more important for larger changes, and then it would really pay to push an issue or pull request up on GitHub so others can raise the alarm (thanks @thijsdhollander :wink:).

**Pull request closed without merging**
