### PR TITLE
New mask cleaning filter

### PR DESCRIPTION
**Pull request by thijsdhollander**
Implementation of a strategy akin to that shown in #615 .

### CODE REVIEW

**Comment by draffelt** [comment]
Thijs, just wondering if this is robust enough to have it performed automatically at the end of dwi2mask? Or have you not tested it on enough data to know?

**Comment by thijsdhollander** [comment]
(so, for reference, as we just discussed: the answer seems to be a quite safe "yes"; I'll wait for a little more testing and if positive, add it at the end of `dwi2mask` too)

**Comment by jdtournier** [comment]
> just wondering if this is robust enough to have it performed automatically at the end of dwi2mask? 

I'm assuming this approach would only work for human (adult) brains? Should we provide this as an optional step? Or (probably better) provide an option to opt out? Or probably better again, provide an option to provide a custom template brain & mask so the approach could be trivially extended to other species or neonates, etc?

**Comment by thijsdhollander** [comment]
Slight confusion here: so it's the technique I described a bit further in that issue (not the initial proposed registration-to-template approach).  It should generalise for a range of non-adult and/or non-human cases; but not perse all exotic cases that one may run into.  For any case in the realm of the exotic stuff, one should of course consider whether the basic current `dwi2mask` approach holds up any way.

But apart from that: even if we would add the step as a default extra step, there will definitely be an opt-out option (the one that will provide/change the default parameter of the method; if set to 0, it would be opt-out).

**Comment by jdtournier** [comment]
Ah OK, this is purely about the removing crap connected via thin bridges approach. All good, sounds perfectly sensible to me!

**Comment by thijsdhollander** [comment]
I've done quite a bit more testing on a wide range of data today; all looks good, and setting the parameter by default to 2 seems to be pretty safe for typical resolutions.  I've gone ahead and added the proposed changes to `dwi2mask` too; but as mentioned, there's an easy opt-out way as well.

It's in principle ready to be merged.  Feel free to test in the mean time; if no distressing findings pop up, I'll eventually merge it. :-)

**Comment by draffelt** [comment]
:+1:

**Comment by thijsdhollander** [comment]
Ok, did some final testing; nothing distressing so far for human subjects.  If (not) needed for other/specific applications, there's always opt-out.  I'll merge for now.  If something weird does turn up for anyone, we can always make it opt-in (rather than opt-out) in the future; it would only be a matter of changing the default value "2" in `dwi2mask` to "0".

**Pull request merged**
