### PR TITLE
dwi2response manual: avoid checking and calculating a brain mask

### PR DESCRIPTION
**Pull request by bjeurissen**
For the manual response function estimation, a brain mask is not needed or supported. However, currently, a brain mask is always calculated if one is not provided. This is unnecessary and can also lead to crashes whenever dwi2mask fails (e.g. exotic data, simulations, ... exactly the use-cases where you would use manual response estimation).

### CODE REVIEW

**Comment by bjeurissen** [comment]
The eigen 3.4 issue has now also made it into the CI :(

**Comment by Lestropie** [comment]
Testing string equivalence of the selected algorithm within `dwi2response` is not the ideal solution from a code hierarchy perspective. It would be preferable for algorithms to define a function that returns a value indicating whether or not that particular algorithm wishes for a brain mask to be defined / calculated for it.

**Comment by bjeurissen** [comment]
> Testing string equivalence of the selected algorithm within `dwi2response` is not the ideal solution from a code hierarchy perspective. It would be preferable for algorithms to define a function that returns a value indicating whether or not that particular algorithm wishes for a brain mask to be defined / calculated for it.

Agreed!

**Review by jdtournier — APPROVED** [review]
Seems OK to me. Ready to merge, @Lestropie?

**Pull request merged**
