### PR TITLE
DICOM import & dcminfo: Enhancements

### PR DESCRIPTION
**Pull request by Lestropie**
Back-end changes necessary to support some work I'm doing locally. Details in 3a9ff73 commit message.

@jdtournier: Please make sure this doesn't bork your DICOM test suite.

### CODE REVIEW

**Comment by jdtournier** [comment]
OK, I ran it through my DICOM test suite - everything checks out _apart_ from some of the Siemens localisers. Here's the output from one of those:
```
mrinfo: [ 11%] reading DICOM series "localizer_sf"... 
mrinfo: [WARNING] error reading tag (0029,1020):
mrinfo: [WARNING] incomplete use of string "0x10" in conversion to type "m"
mrinfo: [ 22%] reading DICOM series "localizer_sf"... 
mrinfo: [WARNING] error reading tag (0029,1020):
mrinfo: [WARNING] incomplete use of string "0x10" in conversion to type "m"
mrinfo: [ 33%] reading DICOM series "localizer_sf"... 
mrinfo: [WARNING] error reading tag (0029,1020):
mrinfo: [WARNING] incomplete use of string "0x10" in conversion to type "m"
mrinfo: [ 44%] reading DICOM series "localizer_sf"... 
mrinfo: [WARNING] error reading tag (0029,1020):
mrinfo: [WARNING] incomplete use of string "0x10" in conversion to type "m"
mrinfo: [ 56%] reading DICOM series "localizer_sf"... 
mrinfo: [WARNING] error reading tag (0029,1020):
mrinfo: [WARNING] incomplete use of string "0x10" in conversion to type "m"
mrinfo: [ 67%] reading DICOM series "localizer_sf"... 
mrinfo: [WARNING] error reading tag (0029,1020):
mrinfo: [WARNING] incomplete use of string "0x10" in conversion to type "m"
mrinfo: [ 78%] reading DICOM series "localizer_sf"... 
mrinfo: [WARNING] error reading tag (0029,1020):
mrinfo: [WARNING] incomplete use of string "0x10" in conversion to type "m"
mrinfo: [ 89%] reading DICOM series "localizer_sf"... 
mrinfo: [WARNING] error reading tag (0029,1020):
mrinfo: [WARNING] incomplete use of string "0x10" in conversion to type "m"
mrinfo: [100%] reading DICOM series "localizer_sf"
mrinfo: [WARNING] slice gap detected (maximum gap: 7mm)
mrinfo: [ERROR] unexpected phase encoding table matrix dimensions
mrinfo: [ERROR] error opening image "../Siemens Trio - mosaic/"
```
I think the warnings will probably end up demoted to `-debug` with #1999. But the main error is at the end. I reckon these shouldn't be treated as errors, but reported with a warning, and the PE information ignored and kept out of the header. It shouldn't be considered fatal if the PE information is inconsistent... What do you think?

**Comment by Lestropie** [comment]
I can't reproduce the warnings... can you send some data?

0029 1020 is a Siemens CSA ("OBCSASeriesHeaderInfo" in the dictionary), and gets parsed by `CSAEntry`. Whatever it is, it looks like it should ideally be going to either a string or a dedicated hexadecimal converter. I'm not sure for what type "`T`" `typeid(T).name()` comes out as "`m`" though. Chris Rorden says [here](https://neurostars.org/t/reading-csa-series-header-info-from-a-pydicom-object/2722/2) that contents of that specific tag are unpredictable, so maybe it should be ignored altogether if our `CSAEntry` parser isn't robust to it.

**Comment by jdtournier** [comment]
OK, it still borks with the same error message... 

I had a bit of a dig around the code to chase this down. The error is emitted in the [PhaseEncoding::get_scheme()](https://github.com/MRtrix3/mrtrix3/blob/3.0_RC4/core/phase_encoding.cpp#L118-L119) when it is invoked from [Header::realign_transform()](https://github.com/MRtrix3/mrtrix3/blob/3.0_RC4/core/header.cpp#L527) (which is invoked by [Header::open()](https://github.com/MRtrix3/mrtrix3/blob/3.0_RC4/core/header.cpp#L146-L147)), because the PE table at this point is a 3×3 matrix, when it's expected to be *n*<sub>volumes</sub>×4:
```
mrinfo [core/phase_encoding.cpp: 118]: result = 1 0 0                                                                         
1,0,0
0,1,0
```
The code that was enclosed in a try/catch clause in befb66e actually runs successfully, but the PE table just before [this point in DICOM::Frame::get_PE_scheme()](https://github.com/MRtrix3/mrtrix3/blob/befb66e/core/file/dicom/image.cpp#L652-L654) is:
```
mrinfo [core/file/dicom/image.cpp: 651]: pe_scheme = 1 0 0 0
1 0 0 0
0 1 0 0
```
and that last column adds up to zero, so fails the subsequent test, with the (unexpected?!?) result that it returns just the first 3 columns... I'm not sure why that's there, but it's pretty clear that there's an expectation that it should have 4 columns later on...?

**Comment by Lestropie** [comment]
The intent is for all code handling phase encoding information to be compatible with matrices with or without the total readout time column (not too dissimilarly to how the diffusion gradient table handling is intended to work on matrices with at least four columns but optionally more). So the check in `PhaseEncoding::get_scheme()` is contrary to that intent. I'll change that and see if I can get code to bork anywhere else with 3-column data.

**Pull request merged**
