### PR TITLE
New script dwicat

### PR DESCRIPTION
**Pull request by jvohryzek**
Hey Robert,
Could you get it approved by some other developer. 

Best
Lena & Jakub

### CODE REVIEW

**Comment by Lestropie** [comment]
Closes #1428.

**Comment by Lestropie** [comment]
Manually setting average *b*=0 intensity would be pretty easy. What I actually wanted to do here, but couldn't convince myself that my math was correct, was to intensity-match all protocols to all other protocols, producing a scaling factor *matrix*, and then scale each protocol individually in such a way as to converge their intensities toward a common target, rather than arbitrarily using the first scan as the "target" intensity.

**Comment by treanus** [comment]
Hi developpers,

I did a git checkout dev and tried dwicat.

`dwicat part1.mif part2.mif full.mif`

Get the error:

```
[ERROR] mrhistmatch scale 1b0.mif 0b0.mif 1rescaledb0.mif (dwicat:84)
dwicat: [ERROR] Information from failed command:
dwicat:
        mrhistmatch: [ERROR] mrhistmatch currently only works on 3D images
```

**Comment by jdtournier** [comment]
The script relies on updates to the supporting executables, which need to be recompiled. You need to run `./build` after checking out the `dev` branch to get it to work.

**Comment by treanus** [comment]
> The script relies on updates to the supporting executables, which need to be recompiled. You need to run `./build` after checking out the `dev` branch to get it to work.

Works fine now.

@jdtournier Thx

**Pull request merged**
