### PR TITLE
dwidenoise: implementation of Jelle Veraart's MP-PCA denoising 

### PR DESCRIPTION
**Pull request by jdtournier**
Here it is. Still to do before merging:

- generate test data, upload to `test_data` repo, and add relevant tests

- create a documentation page on readthedocs describing the method briefly, and providing a few hints for QA and diagnostics.

### CODE REVIEW

**Comment by jdtournier** [comment]
OK, tests added, but I notice they fail for some of the other commands - I assume this will be due to changes in the test data for `tag_0.3.15`. The tests for `dwidenoise` pass fine, so let's not worry about the  failures until we've merged into `tag_0.3.15`...

**Comment by Lestropie** [comment]
> I notice they fail for some of the other commands - I assume this will be due to changes in the test data for tag_0.3.15

Correct.

**Comment by jdtournier** [comment]
Ok, I'll merge this now, we can add the doc later, before the big merge to `master`

**Comment by jdtournier** [comment]
Seems I can't merge now due to conflicts. @lestropie, you're probably best placed to fix them, they'll be due to conflicts between `master` and `tag_0.3.15`...

**Comment by Lestropie** [comment]
I probably won't be able to get to it until Tuesday. You want it merged into `tag_0.3.15`, right?

**Comment by jdtournier** [comment]
@lestropie: yes, this branch is for merging into `tag_0.3.15` - but I reckon all you need to do is merge `master` into `tag_0.3.15`, that should then allow a straightforward merge for this pull request.

**Pull request merged**
