### PR TITLE
Configure remove linker optimisation flags

### PR DESCRIPTION
**Pull request by jdtournier**
as discussed in #1243

### CODE REVIEW

**Comment by chunhungyeh** [comment]
Doesn't look good:
```

REPORT: 
MRtrix build type requested:

REPORT: release

REPORT: 

REPORT: Detecting OS: darwin
EXEC <<
CMD: sw_vers -productVersion
EXIT: 0
STDOUT:
10.13.3
>>


REPORT: OS X deployment target: 10.13

REPORT: Looking for compiler [clang++]:
EXEC <<
CMD: clang++ --version
EXIT: 0
STDOUT:
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
>>


REPORT: Apple LLVM version 9.0.0 (clang-900.0.39.2)

REPORT: Checking for C++11 compliance:

COMPILE /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmpdpVLKm.cpp:
---

#include <cstddef>
struct Base {
    Base (int);
};
struct Derived : Base {
    using Base::Base;
};

int main() {
  Derived D (int); // check for contructor inheritance
  return 0;
}

---
EXEC <<
CMD: clang++ -c -std=c++11 -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.13 /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmpdpVLKm.cpp -o /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmpdpVLKm.o
EXIT: 0
>>

EXEC <<
CMD: clang++ /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmpdpVLKm.o -Wl,--sort-common,--as-needed -mmacosx-version-min=10.13 -o a.out
EXIT: 1
STDERR:
ld: unknown option: --sort-common
clang: error: linker command failed with exit code 1 (use -v to see invocation)
>>

error deleting temporary file "a.out": No such file or directory
REPORT: test failed (see configure.log for details)

REPORT: Looking for compiler [g++]:
EXEC <<
CMD: g++ --version
EXIT: 0
STDOUT:
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
STDERR:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
>>


REPORT: Apple LLVM version 9.0.0 (clang-900.0.39.2)

REPORT: Checking for C++11 compliance:

COMPILE /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmpvTCDKt.cpp:
---

#include <cstddef>
struct Base {
    Base (int);
};
struct Derived : Base {
    using Base::Base;
};

int main() {
  Derived D (int); // check for contructor inheritance
  return 0;
}

---
EXEC <<
CMD: g++ -c -std=c++11 -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.13 /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmpvTCDKt.cpp -o /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmpvTCDKt.o
EXIT: 0
>>

EXEC <<
CMD: g++ /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmpvTCDKt.o -Wl,--sort-common,--as-needed -mmacosx-version-min=10.13 -o a.out
EXIT: 1
STDERR:
ld: unknown option: --sort-common
clang: error: linker command failed with exit code 1 (use -v to see invocation)
>>

error deleting temporary file "a.out": No such file or directory
REPORT: test failed (see configure.log for details)

ERROR: no suitable compiler found!



  Set the CXX environment variable to inform 'configure' of the path to the
  compiler on your system, as follows:
    $ export CXX=/usr/bin/g++-5.5
    $./configure
  (amend with the actual path to the compiler on your system)

  If you are using a compiler other than gcc or clang, you can also set the CXX_ARGS
  environment variable to specify how your compiler expects different arguments
  to be presented on the command line, for instance as follows:
    $ export CXX_ARGS="-c CFLAGS SRC -o OBJECT"
    $ ./configure


  See the file 'configure.log' for details. If this doesn't help and you need
  further assistance, please post on the MRtrix3 community forum
  (http://community.mrtrix.org/), and make sure to include the full contents of
  the 'configure.log' file.
```

If I remove ``--sort-common`` from ``ld_flags`` and ``ld_lib_flags``:
```

REPORT: 
MRtrix build type requested:

REPORT: release

REPORT: 

REPORT: Detecting OS: darwin
EXEC <<
CMD: sw_vers -productVersion
EXIT: 0
STDOUT:
10.13.3
>>


REPORT: OS X deployment target: 10.13

REPORT: Looking for compiler [clang++]:
EXEC <<
CMD: clang++ --version
EXIT: 0
STDOUT:
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
>>


REPORT: Apple LLVM version 9.0.0 (clang-900.0.39.2)

REPORT: Checking for C++11 compliance:

COMPILE /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmp0FQNYF.cpp:
---

#include <cstddef>
struct Base {
    Base (int);
};
struct Derived : Base {
    using Base::Base;
};

int main() {
  Derived D (int); // check for contructor inheritance
  return 0;
}

---
EXEC <<
CMD: clang++ -c -std=c++11 -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.13 /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmp0FQNYF.cpp -o /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmp0FQNYF.o
EXIT: 0
>>

EXEC <<
CMD: clang++ /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmp0FQNYF.o -Wl,--as-needed -mmacosx-version-min=10.13 -o a.out
EXIT: 1
STDERR:
ld: unknown option: --as-needed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
>>

error deleting temporary file "a.out": No such file or directory
REPORT: test failed (see configure.log for details)

REPORT: Looking for compiler [g++]:
EXEC <<
CMD: g++ --version
EXIT: 0
STDOUT:
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
STDERR:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
>>


REPORT: Apple LLVM version 9.0.0 (clang-900.0.39.2)

REPORT: Checking for C++11 compliance:

COMPILE /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmpWGZUbN.cpp:
---

#include <cstddef>
struct Base {
    Base (int);
};
struct Derived : Base {
    using Base::Base;
};

int main() {
  Derived D (int); // check for contructor inheritance
  return 0;
}

---
EXEC <<
CMD: g++ -c -std=c++11 -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.13 /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmpWGZUbN.cpp -o /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmpWGZUbN.o
EXIT: 0
>>

EXEC <<
CMD: g++ /var/folders/j7/pqtdjgfj0kb0rfl1kmz08njh0000gn/T/tmpWGZUbN.o -Wl,--as-needed -mmacosx-version-min=10.13 -o a.out
EXIT: 1
STDERR:
ld: unknown option: --as-needed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
>>

error deleting temporary file "a.out": No such file or directory
REPORT: test failed (see configure.log for details)

ERROR: no suitable compiler found!



  Set the CXX environment variable to inform 'configure' of the path to the
  compiler on your system, as follows:
    $ export CXX=/usr/bin/g++-5.5
    $./configure
  (amend with the actual path to the compiler on your system)

  If you are using a compiler other than gcc or clang, you can also set the CXX_ARGS
  environment variable to specify how your compiler expects different arguments
  to be presented on the command line, for instance as follows:
    $ export CXX_ARGS="-c CFLAGS SRC -o OBJECT"
    $ ./configure


  See the file 'configure.log' for details. If this doesn't help and you need
  further assistance, please post on the MRtrix3 community forum
  (http://community.mrtrix.org/), and make sure to include the full contents of
  the 'configure.log' file.
```

**Comment by maxpietsch** [comment]
As suggested in #1243, I've modified the linker flags to use link-time-optimisation on macOS but none of the other flags as they are not supported. Compiles with `clang 9.0.0` and `g++ 7.1.0` on macOS.

**Comment by maxpietsch** [comment]
LTO seems to break some exception handling in `transformcompose`. That and the additional time linking takes and a not measurable effect on the time the test for `tckgen` takes, we've decided to take it out for now.

**Comment by Lestropie** [comment]
Given Jimmy has tested on both Linux & Mac, I reckon we should merge this into `dev`, and that will make it easier for Mac users working on other development branches to merge this in.

**Pull request merged**
