### PR TITLE
Update dev from master

### PR DESCRIPTION
**Pull request by jdtournier**
This will need to be done from time to time - see discussion on #1120...

### CODE REVIEW

**Comment by jdtournier** [comment]
I guess it's still useful to have to open a pull request to merge `master` back into `dev` then... :wink:
TravisCI errors out for Python3 while fetching dependencies with this error message:
```
Installing collected packages: isort, wrapt, enum34, singledispatch, lazy-object-proxy, backports.functools-lru-cache, astroid, mccabe, configparser, pylint, docutils, commonmark, recommonmark, Pygments, imagesize, pytz, babel, snowballstemmer, MarkupSafe, Jinja2, alabaster, sphinxcontrib-websupport, typing, sphinx, sphinx-rtd-theme
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/isort'
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
The command "pip install pylint recommonmark sphinx sphinx-rtd-theme" failed and exited with 2 during .
Your build has been stopped.
```

Looks related to the docs up to date changes in #1103 - any idea how to fix this one, @Lestropie...?

**Comment by Lestropie** [comment]
I spotted this in the #1049 tests as well... I'm not quite sure how the tests passed in #1103 but are now subsequently failing; my guess is a coincidental correlation between these changes and a TravisCI back-end alteration. 

Possible fixes:

- Only perform the documentation test under Python3; I deliberately set up the test to run on both Python versions just in case a warning was issued by `sphinx` in one environment but not the other, but it's not mission-critical.

- `sudo: true` in `.travis.yml` (don't know if this has other ramifications...?)

- Change base distribution for TravisCI testing, e.g. `dist: trusty`

- The website provided in the (second) error message indicates a necessity for additional installations; some in `pip`, others in the general package manager. Apparently certificates in Python2 are not particularly secure by default...

What I think I'll do is set up a dummy PR to `dev`, and muck around to see what succeeds in TravisCI. If there's a clear winner, I'll implement just that fix into this PR.

**Comment by jdtournier** [comment]
Yes, pretty strange... I reckon it would be enough to perform the tests under be python 3 only if that can be done... See how you go.

**Comment by Lestropie** [comment]
OK fixed. Took me enough attempts though :-/

**Comment by jdtournier** [comment]
> Took me enough attempts though :-/

:rofl: yes, we noticed... 

Good effort though :+1:

**Pull request merged**
