### PR TITLE
Statistical inference: Use Z-statistic

### PR DESCRIPTION
**Pull request by Lestropie**
Extension of #1543, but listing on its own in order to be better able to describe the change and link to such.

@maxpietsch provided me with [this link](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=fsl;eb9b9693.1712) in relation to an issue I've had surrounding per-fixel per-subject design matrix exclusion. Initial tests suggest that it may not have fully resolved that specific issue, but I think it's a worthwhile change to be making more broadly.

With this change, both t-tests and F-tests are immediately converted to Z-statistics; it is these Z-statistics that are then fed as the input to the statistical enhancement algorithm.

This provides a number of benefits:

- Empirical behaviour of statistical enhancement algorithms should be consistent across different cohort sizes.

- Statistic becomes pivotal across hypotheses, which is necessary for strong FWE control (#1580) in the absence of non-stationarity correction.

- For F-tests:

    - Any elements with p>=0.5 (z<=0.0) do not contribute to statistical enhancement.

    - Distribution of statistical measure is no different to that of a t-statistic.

    This is a much more elegant solution to the issue described in #1068, and also results in much faster CFE execution for F-tests due to decreased cluster size at small values of *h* (and doesn't require the awkward gymnastics of internally storing `sqrt(F)` which is what I did in #1068).

- Statistic remains pivotal even when the rank of the design matrix varies between those elements tested (e.g. if subject data are differentially cropped due to FoV & subject motion, such that valid diffusion data are not available for all fixels for all subjects). This *should* improve stationarity of statistical inference when per-subject per-fixel exclusion is used, though my initial tests suggest it wasn't a panacea to the particular issue I was observing.

Change has minimal effect on execution time: lookup tables for direct t->z and F->z conversion are constructed on demand based on the relevant full analytic transformations (with some mathematical trickery to avoid floating-point precision issues), and Hermite interpolation is performed on this table. Total lookup-based transformation precision is approx. that of single-precision floating-point, i.e. 6 significant figures.

Enhancement parameters should not I think need to be modified: the experiments used to determine those parameters could simply be re-interpreted as having been done based on simulated-z rather than simulated-t effects.

There's a unit test added in there specifically for the inverse error function calculations; I also have a standalone command that has been used to verify the operation of the lookup tables, which I might try to coax into a unit test.

### CODE REVIEW

**Comment by Lestropie** [comment]
One catch found here: `Eigen::betainc()` is not available in Eigen 3.2, only in Eigen 3.3. So either the minimum installation requirements will need to be bumped, or a custom implementation of that function will be required, or an environment variable will need to be used to toggle use of the Z-transformation depending on detection of the availability of that function at config time.

**Comment by Lestropie** [comment]
7820da1 adds support for Eigen 3.2 (should probably test both Eigen versions as part of CI...). Currently the Eigen function will be used if available, and this alternative used otherwise (the outcomes of F->Z transformations, which incorporates this calculation, are identical to at least 6 significant figures).

**Comment by jdtournier** [comment]
Alternatively, we could simply add Eigen as a git submodule, now that there's an [officially maintained git repo](https://github.com/eigenteam/eigen-git-mirror)...?

**Comment by Lestropie** [comment]
While that's definitely an option, I think it's a packaging / distribution / installation question that extends well beyond the scope of this PR, so probably needs to be had separately. I kinda need to merge this into `stats_enhancements` so that I can resolve with #1662.

**Pull request merged**
