### PR TITLE
preserve b-value scaling for b-zero #2231

### PR DESCRIPTION
**Pull request by dchristiaens**
Please see #2231 for discussion. Do I have permission to close this off?

### CODE REVIEW

**Comment by Lestropie** [comment]
It seems to me as though the line [`0 0 0 >BZeroThreshold`] is fundamentally ambiguous. It could be a post-acquisition reconstructed mean intensity within a shell, or it could be a *b*=0. Perhaps the former could only possibly apply if that volume is the last in a series? So perhaps:

1. Incorporate this proposed change, so that volumes with [`0 0 0`] direction are rescaled to *b*=0;
2. If such a rescaling occurs for the last volume in a series, issue a warning level message that the data need to be checked in case this is in fact a trace-weighted image that needs to be removed via `mrconvert -coord 3`.

?

**Comment by dchristiaens** [comment]
> 2\. If such a rescaling occurs for the last volume in a series, issue a warning level message that the data need to be checked in case this is in fact a trace-weighted image that needs to be removed

I am hesitant about any sort of behaviour that depends on a particular ordering in the series. If you think a warning message is needed, I would prefer to issue one for every dataset that contains at least one ambiguous gradient table entry.

**Comment by Lestropie** [comment]
> If you think a warning message is needed, I would prefer to issue one for every dataset that contains at least one ambiguous gradient table entry.

That was actually my first thought, but I pulled it back for some reason; happy to go with that. Perhaps just the content of the warning message itself could be changed if it's the final volume that's identified; i.e. there's a stronger hypothesis that interpretation of that volume as a b=0 is likely to be erroneous.

**Comment by jdtournier** [comment]
Happy enough with this, but we need to figure out why tests currently fail for `dwi2tensor` and `tckgen`. Might be that our test data are actually affected by the very issue this is dealing with...?

**Review by jdtournier — DISMISSED** [review]

**Review by jdtournier — APPROVED** [review]

**Pull request merged**
