### PR TITLE
dwibiascorrect ANTS N4BiasFieldCorrection parameters re-tuned

### PR DESCRIPTION
**Pull request by thijsdhollander**
It looks like biasfield correction is becoming my personal nightmare of sorts... :fearful: :scream: 

So when I retuned the N4 parameters last time, it seemed to improve things for `dwi2mask` for all data that I had access to... until now.  @Lestropie ran into / spotted a case where the opposite was true: the corrected data got slightly too large intensities towards the edge of the FOV (basically extrapolation from the bias field estimated in the brain mask).  This then becomes an issue for `dwi2mask`, where it automatically thresholds the b=3000-ish data (b=0 is not a problem).  The role of that bit of data though, is to essentially give a rough brain parenchyma mask (b=0 gives a rough CSF mask).  If that one fails, and there are no other shells to play that role decently, you only end up with a CSF + few bits of edge-of-FOV crap.  That's already a fail at that stage, but the crap-cleaning filter makes things even worse thereafter (but again: at that stage all was lost already, so it doesn't matter any more).

The answer is to re-tune the N4 parameters once more.  The trick is to keep them smooth enough; there's really only so much you can estimate from an average b=0 (T2w) contrast...  N4 was really only designed to perform well on a T1w image sadly.  So we just keep it smooth enough, so we still gain from correcting the gross effects of a bias field (if a gross effect is present).  That'll help `dwi2mask` as well as `dwi2response tournier` (or any dwi2response algo that runs tournier at some stage).  In a decent multi-tissue FBA (or other analysis), you can at some stage perform `mtnormalise` any way, which takes care of things much more decently.

Alright, lots of words for a simple pull request: this comes from extensive tuning and should work decently for what can decently be done at that stage in a pipeline.  Since this does change behaviour, it's gotta go `dev` sadly... but it's quite important again for people doing FBA... so it may not be a bad idea to think towards a tagged release in the near future.

I think it'd be worthwhile to at least have another tagged release (candidate) before the "release release", so we can get a bunch of features on `master` again.  It'd be good if the actual true "release" doesn't have to come with too many other features other than the benefits of a release (i.e. some kind of binaries distribution (mechanism).  What do people reckon?

Feel free to test the dwibiascorrect changes if you've got the time.  I'm quite convinced they're another change for the better, after careful tuning.  I'll be looking to at least merge them into `dev` relatively soon if nobody comes across important examples that would argue against the changes.  Speak up if you feel strongly about this, or remain silent forever (or until the next issue arises). :smile:

### CODE REVIEW

**Comment by Lestropie** [comment]
Do you feel as though this change is compromising the quality of the bias field correction? Because if so, we might be able to retain the better performance of the current settings within the brain, and instead more directly address what happens outside the brain.

As an example: With `dwibiascorrect -fsl`, it applies a multiplicative factor to each voxel in the input mask, which is somehow scaled so that the values are distributed around 1.0, and voxels outside the mask remain unchanged. So that can lead to weird effects at the edge of the mask, where a voxel in the mask can be multiplied by e.g. 1.3 but the adjacent voxel is unaffected. So even just performing this would solve the reported issue, but obviously comes with a different non-ideal behaviour, especially if the masking process is imperfect.

So a couple of thoughts. Firstly, the factors coming out of N4 are nowhere near centred around 1.0, which makes applying a "default" scaling outside the mask difficult (and may be consequential for #1096 as well, if that overall factor varies a lot between subjects and `dwiintensitynorm` isn't used). But we could, for example, optimise the bias field within a brain mask, apply the estimated field within a *dilated* brain mask, and then null values outside of the dilated brain mask. That would hopefully allow reasonable correction at the outer extent of the brain; and limiting the extent to which that field is applied outside the brain would prevent the effect reported here (i.e. brightness in the FoV corners) from appearing.

Alternatively, rather than putting a hard threshold on how far outside the brain mask the field can be applied vs. nulling the image data, we could do something like what Max tried in #1016, i.e. smoothly constrain the bias field toward 1.0 the further away you get from the brain mask. This would require first re-scaling the N4 bias field so that it is in fact centred around 1.0 within the brain mask; though that's probably not a bad idea to add to the script anyways.

Just riffing...

**Comment by thijsdhollander** [comment]
> Do you feel as though this change is compromising the quality of the bias field correction?

Nope.  This new parameter set is a bit less aggressive in (over)fitting.  The quality, as in "accuracy" is hard to assess.  As I mentioned, the problem is mostly that what can be done realistically of a T2w contrast at a low spatial resolution is very limited.  Aggressive fitting is riskier, because if the algorithm fails to separate white matter and grey matter as intensity classes / peaks in the histogram (which it often does), it'll end up being an over-fit, with more wacky extrapolation beyond the brain mask.  The new choices are simply "safer", and may as such actually be "better" for lower quality datasets as well.

> Because if so, we might be able to retain the better performance of the current settings within the brain, and instead more directly address what happens outside the brain.

So this shouldn't be needed.

I wouldn't add heuristic mechanisms to N4, because there's not a lot that can be safely relied upon.  Intensity normalisation, as you mention, is indeed something that isn't there inherently.  Also, the main goal of actually adding `dwibiascorrect` again to the pipeline, is to produce better brain masks, so relying too much on the brain mask estimated before N4 (in the `dwibiascorrect` script) is also not a safe idea.

The normalisation issue with respect to response function averaging, by the way, is also not too big of a deal.  Data will typically not be entire orders of magnitude different between subjects, and response functions have already been shown to be varying very, very little between subjects of a similar species.  If anything, that response function averaging step is just to provide a certain feeling of elegance.  In most (e.g. FBA) studies, you won't notice any impact of significance depending on whether you got your (set of) responses from all subjects, a particular group, or even a single subject.

More important though, is what a certain response function represents, i.e., which area(s) of the brain it typically gets estimated from.  That's where the bias field versus the tournier algorithm comes into play, since the latter one is (by conscious design) biased towards higher amplitude responses.  So it's not entirely unimportant to try and correct gross bias field effects before response function estimation.  This is where these new proposed N4 parameters should come into play, hopefully making this again a little bit more robust.

**Comment by thijsdhollander** [comment]
Just a reminder:

> Feel free to test the dwibiascorrect changes if you've got the time. I'm quite convinced they're another change for the better, after careful tuning. I'll be looking to at least merge them into dev relatively soon if nobody comes across important examples that would argue against the changes. Speak up if you feel strongly about this, or remain silent forever (or until the next issue arises).

I'll be looking to merge (to `dev` of course) sometime this week.  ...with the hope it gets some extra inherent testing on `dev` dev of course.

**Comment by Lestropie** [comment]
I don't really have a large amount of data from different sites / acquisitions, so can't really contribute to the assessment here over and above the problematic data I sent you.

**Comment by Lestropie** [comment]
Will this change be enough to sort out #944 @bjeurissen?

**Comment by thijsdhollander** [comment]
I'll merge this for now to `dev`, since it resolved the issue, and I've seen it work decently on a few other cases.  Maybe in the future, we could indeed allow the parameters to be set via the script, so people are aware that defaults are involved and they can be overridden in case it makes sense for particular data... but I'm not going to lose too much sleep over it.  Over all the changes we've made to this internally at some point, and via other mechanisms to correct for bias fields or normalise, I've barely ever seen an impact on our (FBA) studies' results.  This is never going to be perfect (the data doesn't even have the specificity to resolve the solution to this problem uniquely).  Even if spatially biased, as long as it's somewhat consistent across subjects in spatial behaviour, this isn't a big issue for sufficiently powered fixel- or voxel-wise studies.

**Pull request merged**
