### PR TITLE
dwi2mask overhaul (replacement PR)

### PR DESCRIPTION
**Pull request by Lestropie**
#2088 is broken due to me wiping my fork (completely forgetting that that's where the `dwi2mask` updates were...) and GitHub refusing to re-establish the PR link; so relisting.

Given that the other OHBM Hackathon *MRtrix3* project has matured to a preview release and should become a part of `3.1.0`, I wanted to clear this off of my desk; there's also been a couple of private discussion threads where having this finalised would be beneficial. Listing as a full PR rather than a draft in the hope of getting some fresh eyes & opinions on it, but I will probably try to make some test data before merging.

There's some brain masking approaches that I tried to get working as a `dwi2mask` algorithm but couldn't get anything reasonable out of them, I still have the code if anyone wants to try themselves:
https://github.com/GUR9000/Deep_MRI_brain_extraction
https://pypi.org/project/deepbrain/
I'm open to implementing further algorithms to wrap existing approaches, but such approaches need to be compatible with T2-weighted images, and many newer brain extraction approaches are T1w tailored.

Because it's coming from my fork I don't have things set up to preview the documentation, but you can see the relevant raw pages:
https://github.com/Lestropie/mrtrix3/blob/dwi2mask/docs/dwi_preprocessing/masking.rst
https://github.com/Lestropie/mrtrix3/blob/dwi2mask/docs/reference/commands/dwi2mask.rst

@jdtournier: I thought about having hyperlinks in the `dwi2mask` help pages to the new dedicated docs page on the topic. But this would require parallel gymnastics to those used for getting version-matched hyperlinks into the SH-related binaries prior to tagging. Want to do it anyway?
**Edit**: If doing so, should also add links to the [`dwi2response` docs page](https://mrtrix.readthedocs.io/en/latest/constrained_spherical_deconvolution/response_function_estimation.html) in the `dwi2response` help pages.

Tagging @wtsyeda and @RicardoRios46 so that they're aware of the progress given their contributions.

### CODE REVIEW

**Comment by Lestropie** [comment]
I'd also like to take a bias-field-corrected DWI series, artificially introduce bias fields separately along the three spatial axes, and run each of the algorithms, see how each responds. Masking in the presence of a bias field is vital for `dwifslpreproc` and `dwibiascorrect`.

**Comment by Lestropie** [comment]
I can only conclude here that there's a bug in GitHub's diff reporting in submodules.

Target branch `MRtrix3/mrtrix3:dev`, currently 7e3634e, [points](https://github.com/MRtrix3/mrtrix3/tree/7e3634e7d72c8ac1eb79057f909ebcd59b6ae702/testing/scripts) to [`MRtrix3/script_test_data` b89990f](https://github.com/MRtrix3/script_test_data/tree/b89990f5aae924e5cf9d61938ebe209ad2152a90) (which also happens to be where the `dev` branch of `script_test_data` is currently pointing).

Source branch `Lestropie/mrtrix3:dwi2mask`, currently 0ff4f58, [points](https://github.com/Lestropie/mrtrix3/tree/0ff4f5868f24bb9ac2daff66b516de13c9ad5c39/testing/scripts) to [`MRtrix3/script_test_data` c92b8ef](https://github.com/MRtrix3/script_test_data/tree/c92b8efdb614acb157c098fdaab6f3a50496a56c) (which also happens to be where the `dwi2mask` branch of `script_test_data` is currently pointing).

b89990f is the sole parent of c92b8ef, and only adds new files in new directory `dwi2mask`.

Yet GitHub reports a conflict in `testing/scripts/data` for this PR.

When you [query the changes to `testing/scripts/data` in this PR](https://github.com/MRtrix3/mrtrix3/pull/2197/files#diff-02ff12b5892d5d2ecf3ee4f22268bbdc3d737eb6339045e93149e3bb0bb49538), it reports changes over and above those of addition of the new directory `dwi2mask`. What it's *actually* showing is, instead of the [differences between c92b8ef and b89990f](https://github.com/MRtrix3/script_test_data/compare/b89990f5aae924e5cf9d61938ebe209ad2152a90...c92b8efdb614acb157c098fdaab6f3a50496a56c) (as should be the case for this PR), the [differences between c92b8ef and *`master` on `script_test_data`*](https://github.com/MRtrix3/script_test_data/compare/1ffb5ed3dfb10c8667037919b818b11616265001...c92b8efdb614acb157c098fdaab6f3a50496a56c), which is currently [1ffb5ed](https://github.com/MRtrix3/script_test_data/tree/1ffb5ed3dfb10c8667037919b818b11616265001). So my suspicion is that in the reporting of submodule diffs and the checking of fast-forward capability to see if the PR is conflict-free, submodule changes are erroneously being compared against the submodule's `master` branch, rather than the commit of that submodule to which the PR's target branch is pointing.

**Comment by jdtournier** [comment]
Don't think issue is with GitHub, issue happens on local merge too:
```
$ git merge --no-ff Lestropie/dwi2mask 
Failed to merge submodule testing/scripts/data (not checked out)
Auto-merging testing/scripts/data
CONFLICT (submodule): Merge conflict in testing/scripts/data
Removing testing/binaries/tests/dwi2mask
Auto-merging docs/index.rst
Auto-merging docs/fixel_based_analysis/st_fibre_density_cross-section.rst
Auto-merging docs/fixel_based_analysis/mt_fibre_density_cross-section.rst
Removing core/filter/dwi_brain_mask.h
Auto-merging cmd/maskfilter.cpp
Removing cmd/dwi2mask.cpp
Auto-merging bin/dwifslpreproc
Automatic merge failed; fix conflicts and then commit the result.
```
Looking at the status:
```
$ git status 
On branch dev
Your branch is up to date with 'github/dev'.

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:
	modified:   .gitignore
        ... (lots more files)

Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both modified:   testing/scripts/data
```

Digging a bit further, the issue isn't whether b89990f is the sole parent of c92b8ef, but it's the fact that the history of the branches to be merged _on the main repo_ have diverged for that file:
```
$ git log --oneline --decorate --graph dwi2mask dev -- testing/scripts/data/
* 69bd58fc8 Add tests for Python dwi2mask
| * 7e3634e7d Testing: Update dwinormalise group test and data
| * 6c9a4dee5 (github/script_testing) Update 5ttgen hsvs -template test
| * 1b5fed974 Update dwi2response msmt_5tt tests and relevant data
|/  
* 61cb088d4 Add tests for 5ttgen hsvs
* af4207196 dwi2response revisions
* 481ae2bc4 Testing: Relax 5ttgen fsl test
* 2fdf5d5ca Testing: Move dwibiascorrect data
* e2ea118da Re-arrange test data
```
The merge on the parent repo doesn't have much insight into the submodule repo, it just keeps a SHA1 of it, and all it can see if that this SHA1 has been modified differently on the two branches to be merged. I think the solution here is to merge `dev` back into your branch on your local system, fix the conflict by adding the latest SHA1 for the `testing_scripts_data` submodule (presumably c92b8efd), commit and push that back...?

**Comment by Lestropie** [comment]
Of course... my `git fetch` wasn't updating the forked repo :man_facepalming: 

-----

In other news:
```
logging to "testing_dwi2mask.log"
fetching requisite test data... OK
building testing commands... OK
Erasing old script test output directory... OK
running "testing/scripts/tests/dwi2mask"... 16 of 16 passed
```

**Comment by Lestropie** [comment]
Now includes content of Lestropie/mrtrix3#2.

Would like to merge and encourage more widespread evaluation prior to `3.1.0`.

**Comment by Lestropie** [comment]
One other thing to confirm that nobody's unhappy with here is the naming of the additional `maskfilter` operation "`bigblob`". This integrates [ largest connected component -> inversion -> largest connected component -> inversion ] into a single operation, since it's a common chain. But open to suggestions for a better name.

**Comment by jdtournier** [comment]
> One other thing to confirm that nobody's unhappy with here is the naming of the additional maskfilter operation "bigblob". This integrates [ largest connected component -> inversion -> largest connected component -> inversion ] into a single operation, since it's a common chain. But open to suggestions for a better name.

Not sold on the 'bigblob' name - though it does have a certain appeal. 

Just a thought, but given its mode of operation and the intention behind it, might it not be more appropriate to make that available as an option within the connected component filter, simply by adding `-fill` to the options alongside `-largest`...? Just an idea, but I reckon a command like:
```
maskfilter in.mif connect -largest -fill out.mif
```
would make sense?

**Comment by Lestropie** [comment]
> ... as an option within the connected component filter, simply by adding `-fill` to the options alongside `-largest`

As long as `-fill` additionally applies to the `connect` filter *without* `-largest`, I *think* that works better. `-largest` is already slightly awkward in that it changes the nature of the output image from integer to bitwise; if `-fill` would then additionally be only applicable in instances where `-largest` is already used. you'd end up with two degrees of separation from the default filter operation. But if `-fill` and `-largest` are effectively independent, I'm good with that.

Just need to think about what to do if the filling of one component results in inclusion of voxels that are already in another component (e.g. concentric shells), since that result can't be stored as an integer label image.

**Comment by Lestropie** [comment]
So it turns out there's more gymnastics involved in adding a fill operation to the connected component algorithm than foreseen, the implementation code ends up branching between fill and not moreso than the overlap if wanting to support filling in the absence of `-largest`.

So I think it in fact makes more sense to remove `maskfilter bigblob` and instead have a new filter `fill`, and just have various `dwi2mask` algorithms use ` ... - | maskfilter connect -largest - | maskfilter - fill - | ...`. If somebody wants to spatially fill *multiple* connected components, that can be done in a loop with `maskfilter connect; mrcalc $INDEX -eq - | maskfilter - fill - | ...`, and then they can themselves choose to not deal with the prospect of resulting overlaps.

**Pull request merged**
