### PR TITLE
FEAT: New command connectomeedit

### PR DESCRIPTION
**Pull request by matteofrigo**
This PR adds the connectomeedit python script to the bin folder. At this stage, it provides basic manipulations of connectivity matrices and tests need to be added.
The PR partially addresses issue #714.

@Lestropie where should I put the tests? Is there a dedicated folder for tests of python scripts?

### CODE REVIEW

**Comment by Lestropie** [comment]
> @Lestropie where should I put the tests? Is there a dedicated folder for tests of python scripts?

See #1614. Will depend on which of the two PRs is merged first as to how to go about it. Also getting the test data submodules to sync up with the main repo can be a nightmare, so I'll likely need to walk you through this step by step once you've derived the relevant data & tests.

**Comment by matteofrigo** [comment]
Tests should no longer be a problem for this command, as I rewrote the script in cpp and added tests in the canonical way.

**Comment by Lestropie** [comment]
Hi @matteofrigo,

Sorry it's taken me forever to get to this. Too many things going on in parallel...

The command looks pretty simple so there's not a whole lot that can go wrong. A couple of requests to prep for merge (if you can't get to these let me know and I can make a new branch and do it myself):

- `MR::connectome::check()` can be run without providing the number of nodes, and in that case it simply won't verify the size of the matrix against such a number. So pulling the number of nodes from the size of the matrix itself means it's then being needlessly compared to itself.

- After doing an explicit merge of the latest version of our `dev` branch into your branch and recompiling, run the script `docs/generate_user_docs.sh`, and commit both the resulting new file `docs/reference/commands/connectomeedit.rst` and updated file `docs/reference/commands_list.rst`.

Cheers
Rob

**Comment by matteofrigo** [comment]
Hi @Lestropie , I'll edit the things you suggested in the close future.
Thank you for guiding me through the contribution process!
Cheers,
mf

**Comment by matteofrigo** [comment]
Hi @Lestropie ,
I did the changes committed and pushed.
Hope everything is correct.
Cheers,
Matteo

**Comment by Lestropie** [comment]
Thanks for the contribution! :+1:

**Comment by matteofrigo** [comment]
Thanks to you!

**Pull request merged**
