### PR TITLE
Drop python2 support

### LINKED ISSUE #2047: Drop python2 support?
Python2 is no longer supported by the Python developers since January 2020: https://www.python.org/doc/sunset-python-2/.

And major Linux distributions like Debian and Ubuntu as well as macOS have now also deprecated python2. This means they ship with python3 instead of 2 and have changed all shebangs in python scripts to #!/usr/bin/python3.

The general idea that seems to be adhered to by both Linux and macos seems to be: Installing 'python' will always install the deprecated python2 and calling 'python' will always run deprecated python2. This also means that any package still using #!/usr/bin/python will have python2 as a (deprecated) dependency. Ultimately, the idea is that you always call 'python3' or install 'python3-foo' and that running 'python' and installing 'python-foo' should become a thing of the past.

E.g.: https://wiki.debian.org/Python/2Removal: 

> port upstream package to python3 (or file upstream bug): make sure package doesn't call python at build- or compile time (as there won't be a python package and no python command in bullseye, only python3.)

and https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3#.2Fusr.2Fbin.2Fpython: 

> /usr/bin/python is a symbolic link to /usr/bin/python2 and belongs to the python2 package. This also means that packages that require /usr/bin/python (usually due to shebangs) de facto require Python 2.
...
Since Fedora 26, there is no python package, only python3 and python2. python is virtually provided from python2.

So the "python-is-python3" package that I mentioned I installed on ubuntu 20.04, is only an ugly workaround that will break software that still relies on the deprecated python2 and the right way forward seems to be to update all our python scripts to use #!/usr/bin/python3 instead... This would also mean that we effectively drop support for python2.

Any thoughts on this?

### LINKED ISSUE #2190: dwifslpreproc: a python inconsistancy.
Please use this form for *bug reports only*; for installation problems, and general questions and support, please consult the [community forum](http://community.mrtrix.org/search?expanded=true).

The bug is described at https://community.mrtrix.org/t/dwifslpreproc-error-on-a-cluster/4144/2

A clear and concise description of what the bug is; including if appropriate
how the observed behaviour differs from that expected.

dwifslpreproc does not run with python2.7

Please provide the following information:

OS =  Linux on the HPC.

### LINKED ISSUE #2210: distutils.spawn.find_executable to shutil.which
The *MRtrix3* Python API depends on the `distutils` module for the `find_executable()` function. Apparently usage of this module is discouraged in favour of `setuptools`, and it is indeed [intended for deprecation](https://www.python.org/dev/peps/pep-0632/#id13). But even then, with `setuptools` being to "download, build, install, upgrade, and uninstall Python packages", it's not necessarily a sensible dependency to have.

As of Python 3.3, the widely-used `shutil` module has [the `which()` function](https://docs.python.org/3.8/library/shutil.html#shutil.which), which serves the same purpose.

So if following through with #2047, I would suggest making the minimum dependency 3.3 ([released Sep 2012](https://www.python.org/downloads/release/python-330/)), and making use of this function throughout.

### PR DESCRIPTION
**Pull request by Lestropie**
Closes #2210.

Closes #2047.

Will eventually resolve #2190.

Should consider resolving #2191 here.

Made a bit of a list in 3a856ce as to what changed, but would appreciate some reflection on whether or not there's anywhere else in the code base that required gymnastics to support both Python 2 and 3 that I may have missed.

### CODE REVIEW

**Comment by jdtournier** [comment]
All looks sensible, other than the first thing: changing the interpreter on the shebang to `python3`. I don't think that's the recommended way of doing things...? It might work on Ubuntu, but it's not guaranteed to work on other standard distros. Are there recommendations around this from the python community?

**Comment by jdtournier** [comment]
Ok, forget that last comment, it is indeed the recommendation on this PEP:
https://www.python.org/dev/peps/pep-0394/

**Comment by jdtournier** [comment]
CI is failing due to lots of these errors during `pylint`:
```
Bad option value 'import-outside-toplevel' (bad-option-value)
```
A quick look online reveals that [this check is available as of pylint version 2.4](http://pylint.pycqa.org/en/latest/whatsnew/2.4.html). But the version dragged in by `apt-get` on the GitHUb runners is 1.8.3:
```
Unpacking pylint3 (1.8.3-1) ...
```
which explains the errors. 

Previously, `bad-option-value` was also disabled in the config, but that was removed in 3a856ce1 - which is why the issue only arises now. 

So, two options:
- reinstate `bad-option-value` in `pylint.rc`
- modify all occurrences of `#pylint: disable=import-outside-toplevel` to additionally have `bad-option-value`, e.g. `#pylint: disable=bad-option-value,import-outside-toplevel` (as [suggested here](https://github.com/PyCQA/pylint/issues/3312#issuecomment-571082824)).

**Comment by Lestropie** [comment]
Installing `pylint` via `pip` rather than `apt-get` brings in 2.6.0 rather than 1.8.3.

**Comment by Lestropie** [comment]
Minor clarification here: While the Python scripts in `bin/` will as of `3.1.0` explicitly invoke `python3`, do we want to retain compatibility with Python2 in auxiliary scripts (e.g. `build`, `configure`), or force Python3 there also? This has ramifications for what to do with `configure`: it either needs to ensure that it is itself running on Python3, or if running on Python2 (and such is permitted at our end), it needs to do an explicit check for the presence of `/usr/bin/python3` as a compulsory dependency.

**Pull request merged**
