### PR TITLE
Pipe handler: ensure deletion of piped images even if not loaded

### PR DESCRIPTION
**Pull request by jdtournier**
This is in response to an [issue raised on the forum](https://community.mrtrix.org/t/unix-tmp-becomes-full/3879?u=jdtournier), where the user reports `/tmp` filling up within a day of use. As I was responding, I noticed that `mrinfo` wasn't deleting images piped into it. I'm pretty sure this wasn't ever the intention... Yet this has been the behaviour for a very long time, as far as I can tell. :facepalm: 

This applies to any command that opens the header only, without actually loading the image itself (e.g. I expect the `-template` option used in various commands would also be affected). This should fix the issue everywhere it occurs... Note that the same images are (presumably correctly) deleted in the signal handler, but this is only invoked when a signal is raised - not in normal operation.

I think this is a fairly critical bug to fix, but I'd also want to make sure that the fix isn't going to break expectations elsewhere. Can anyone think of any reason why `mrinfo` and similar commands _shouldn't_ delete images piped into them....? 

Also, am I correct in assuming that some of our scripts may be using pipes into `mrinfo` as part of normal operation? If so, that would definitely explain the `/tmp` filesystem filling up fast...

### CODE REVIEW

**Comment by maxpietsch** [comment]
> Can anyone think of any reason why mrinfo and similar commands shouldn't delete images piped into them

When a temporary image is fed into a script, the script might want to query the input header information before doing anything with it. Adding an option in `mrinfo` to not delete temporary files could be useful.

On a related note: Would it be possible to delay the deletion of temporary images to once the command finishes? Currently, the below fails:
```
a=$(mrconvert 0.mif -)
b=$(mrcat $a $a -)
```
while 
```
a=$(mrconvert 0.mif -)
b=$(mrcalc $a $a -add -)
```
works.

**Comment by Lestropie** [comment]
> When a temporary image is fed into a script ...

Can't be done; no piping support.

**Comment by jdtournier** [comment]
> When a temporary image is fed into a script, the script might want to query the input header information before doing anything with it. 

Yes, that's precisely the kind of usage I'm worried the current 'fix' might conflict with. So the question is: does anything we do rely on this currently?

> Adding an option in mrinfo to not delete temporary files could be useful.

That's an option, although it'll be messy - would need hooks deep into the backend. But realistically, I think usage like that above should be handled with a proper named output - not a dangling pipe. So I'm not enormously keen on offering the option.

> Would it be possible to delay the deletion of temporary images to when the command finishes? 

Yes, but that's up to the individual commands to manage the lifetime of the relevant objects. The example you show is a case in point: the fix here is to open all headers (or images) up front, and not allow them to go out of scope until processing is finished.

An alternative would be to register the files with an additional `atexit()` handler. This is actually what I was going to try first, by hooking into the signal handling backend (I've actually just pushed a branch that was originally supposed to do that, but ended up different). The issue there is that this would need to be a different handler than the signal handler, since we also register output piped images to be deleted on error - we can't assume all these files should be deleted on normal exit. But it can certainly be done - and might admittedly be a cleaner solution for the reasons you raised here.

**Comment by jdtournier** [comment]
> Can't be done; no piping support.

Ok, good to hear. One less thing to worry about...

**Comment by jdtournier** [comment]
>> Can't be done; no piping support.
>
> Ok, good to hear. One less thing to worry about...

Though this doesn't rule out internal commands _within_ a script using pipes fed into `mrinfo`...?

**Comment by Lestropie** [comment]
> Though this doesn't rule out internal commands within a script using pipes fed into mrinfo...?

Technically no; but given there's both an `image.Header` class for capturing header information and an `image.mrinfo()` function, I doubt such is done anywhere.

**Comment by maxpietsch** [comment]
> Can't be done; no piping support.

I did't mean piping images into scripts but using temporary images stored in bash variables as a workaround that automatically deletes temporary files upon completion.

The current implementation of `image.Header` class calls `mrinfo` which would delete these: https://github.com/MRtrix3/mrtrix3/blob/master/lib/mrtrix3/image.py#L34. If `mrinfo` had a flag to not delete files, this could be used there. 

If we decided that we do not support temporary files as input to scripts that'd be fine but I think that's an unnecessary limitation.

Not related to this PR but one more issue with scripts is the usage of `mrconvert_keyval` on output (for instance in `dwishellmath`). Supporting temporary input files would require parsing this information at the beginning of the script.
```
dwishellmath $a mean mean.mif
dwishellmath: Generated scratch directory: /Users/mp/data/dwishellmath-tmp-A7VUCH/
Command:  mrconvert /var/folders/0_/x_fhlh1n76bd5hnk6rcmyzg40000gn/T/mrtrix-tmp-Qt9Lyw.mif /Users/mp/data/dwishellmath-tmp-A7VUCH/in.mif -strides 0,0,0,1
dwishellmath: Changing to scratch directory (/Users/mp/data/dwishellmath-tmp-A7VUCH/)
Command:  dwiextract -shells 0 in.mif - | mrmath -axis 3 - mean shell-00.mif
Command:  dwiextract -shells 400 in.mif - | mrmath -axis 3 - mean shell-01.mif
Command:  dwiextract -shells 1000 in.mif - | mrmath -axis 3 - mean shell-02.mif
Command:  dwiextract -shells 2600 in.mif - | mrmath -axis 3 - mean shell-03.mif
Command:  mrcat -axis 3 shell-00.mif shell-01.mif shell-02.mif shell-03.mif out.mif
Command:  mrconvert out.mif /Users/mp/data/mean.mif

dwishellmath: [ERROR] mrconvert out.mif /Users/mp/data/mean.mif (dwishellmath:60)
dwishellmath: [ERROR] Information from failed command:
dwishellmath:
              mrconvert: [ERROR] Unable to obtain header key-value entries from spec "/var/folders/0_/x_fhlh1n76bd5hnk6rcmyzg40000gn/T/mrtrix-tmp-Qt9Lyw.mif"
dwishellmath:
dwishellmath: [ERROR] For debugging, inspect contents of scratch directory: /Users/mp/data/dwishellmath-tmp-A7VUCH/
dwishellmath: Scratch directory retained; location: /Users/mp/data/dwishellmath-tmp-A7VUCH/
```

**Comment by jdtournier** [comment]
Based on this morning group meeting, this is the list of changes we discussed:

- [X] Need to mark piped images for deletion and cleanup at command exit
- [X] Also prevent output to TTY on platforms that support it (Linux / macOS)
- [X] Add option to not delete piped images? Might be useful in scripts and various other situations. 
- [ ] Add functionality to discard outputs - e.g. add special NULL filename?
- [ ] Update to docs to clarify what happens with dangling pipes

**Comment by jdtournier** [comment]
OK, I reckon this one is ready to go. Slight concern with the NULL image feature, hard to argue that's a bug fix...

**Comment by jdtournier** [comment]
OK, I've moved the `NULL` image feature over to its own pull request (#2131) to `dev` for inclusion in the next minor release - it's really not a bug fix...

Everything else here is good to go, I reckon.

**Comment by Lestropie** [comment]
The topic of not deleting piped images when specifically `mrinfo` is invoked ([ed2f35e](https://github.com/MRtrix3/mrtrix3/pull/2125/commits/ed2f35e2a056055195f98695dd83bd4fe1a1df71) in particular) will be relevant for #1392.

**Pull request merged**
