### PR TITLE
Compute total SH power by default

### PR DESCRIPTION
**Pull request by dchristiaens**
As discussed in #530.

### CODE REVIEW

**Comment by jdtournier** [comment]
Not sure I like the option name `-full` - doesn't really convey what it means, I'd almost expect this to mean the overall power, which is now the default. How about `-per_order`, `-per_band`, `-per_l` or something like that...?

**Comment by thijsdhollander** [comment]
As I suggested in https://github.com/MRtrix3/mrtrix3/issues/530#issuecomment-208652023 , I'd keep the default behaviour as before, and add a `-total` option.  That'll also guarantee that people relying on it, are not affected.

...and then mostly clearly document the definitions being used of course.  I reckon that's what caused the most confusion in the first place.

**Comment by thijsdhollander** [comment]
There could even be an option to output the powers without the `(2*l+1)` normalisation as well (for completeness sake).

**Comment by jdtournier** [comment]
> There could even be an option to output the powers without the (2*l+1) normalisation as well (for completeness sake).

So this is where I'm not sure. Can you think of any reason to normalise in the first place...?

**Comment by thijsdhollander** [comment]
Doesn't need to be there for me (I typically only eyeball the power spectrum's contrasts, so scaling is not relevant for me).  I did notice that particular scaling as well in Flavio's anisotropic power maps ISMRM abstract. (there he applies the scaling per band, sums all bands except the 0 one)

**Comment by dchristiaens** [comment]
OK, renamed the option and provided some more docs. One last thing I'm wondering is if we should divide the output with 4*pi. Then it should exactly equal the mean squared amplitude (the docs now say "linearly proportional").

**Comment by jdtournier** [comment]
> One last thing I'm wondering is if we should divide the output with 4*pi.

Fine by me. Again, it just needs to be documented...

**Comment by jdtournier** [comment]
We good to merge...?

**Comment by jdtournier** [comment]
Just looking at the test: is there any way we can have a more exact test here? A tolerance of 200 seems rather extreme... Maybe you can add an additional test that checks for regressions specifically against  the current output of the command (assuming you've checked it behaves as expected)?

**Comment by dchristiaens** [comment]
Just added the rescaling with 4*pi to have an exact implementation of Parseval's theorem. Now the command is good to go as far as I'm concerned, if you agree.

Regarding the tests, I thought it would be nice to test correspondence to the mean-squared-amplitude directly. But the test image dwi.mif contains 60 directions, so the SH fit is obviously smoothing a few things out. This yields a max-abs-error of about 150, hence I put the tolerance to 200. Relative to amplitudes up to 500^2 that's a relative error below 0.001. So I think it's OK, but I also agree it looks bad on first sight... A better way may be doing it the other way around: start from an SH image and sample this to evaluate the mean-squared amplitude, akin to my first post on this thread.

**Comment by jdtournier** [comment]
OK, so that tolerance of 200 isn't actually as bad as it sounds. I'll merge.

**Pull request merged**
