### PR TITLE
configure: fix Qt parameter parsing for MacOS

### PR DESCRIPTION
**Pull request by jdtournier**
Fix detection of parameters for compiling with Qt on macOS. Requires testing on other platforms...

### CODE REVIEW

**Review by bjeurissen — APPROVED** [review]
Works for me (on Mac)!

**Comment by jdtournier** [comment]
Doesn't work for me on Linux...

**Comment by jdtournier** [comment]
OK, works with that last commit. That will also need double-checking on macOS and MSYS2.

**Comment by Lestropie** [comment]
Tested OK on MSYS2.

**Pull request merged**
