### PR TITLE
Links to config options

### PR DESCRIPTION
**Pull request by jdtournier**
Potential fix for #1380. 

This uses the
```    
.. option:: Name
```    
directive, which can be linked to elsewhere via ``:option:`Name` ``. [Details here](http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-option). 

So far, I've only added one instance of a direct link, but it seems to work ([preview here](https://mrtrix3-dev.readthedocs.io/en/links_to_config_options/troubleshooting/performance_and_crashes.html#scripts-crashing-due-to-storage-requirements), look for `ScriptTmpDir`). 

Thoughts welcome. We can add to this now or as we go.

### CODE REVIEW

**Comment by jdtournier** [comment]
This probably ought to go to `dev`, but I'll keep it based on `master` for now to keep the file change list as-is. We can rebase prior to merging.

**Comment by Lestropie** [comment]
Thoughts on rebasing to `master`? (@jdtournier couldn't make up his mind it seems)

There's some fixes in here that could do with going there, and the new hyperlinks are unlikely to cause issues. If it stays on `dev` we probably need to cherry-pick 
e66061c, f847385 and 0860fc5 onto `master`.

**Comment by jdtournier** [comment]
No idea why I've rebased this 3 times in a row on the same day... It was a whole 3 weeks ago, absolutely no recollection of my thought processes at the time. 

These changes are documentation only, I'm happy for them to go to `master`. I'll rebase (again) and update.

**Comment by jdtournier** [comment]
OK, rebasing to `master` is a bad idea, it'll bring in a batch of `dev` stuff given that I merged `dev` into this branch a while back... I'll cherry-pick the relevant commits and create a fresh pull request.

**Comment by jdtournier** [comment]
OK, fresh version on #1417 - I'll close this, it'll make its way back to `dev` the regular way...

**Pull request closed without merging**
