### PR TITLE
Fix drag & drop on Windows for mrview

### PR DESCRIPTION
**Pull request by daljit46**
Should address #1373

### CODE REVIEW

**Review by Lestropie — CHANGES_REQUESTED** [review]
Confirmed resolves issue on my Windows machine. But only for specifically dragging & dropping main images. There are also toolbars where a user may attempt to drag & drop a file, which this changeset currently won't resolve. Would suggest functionalising the decoding of filesystem paths from a drop event, and make use of it across those multiple contexts:

- Overlay tool
- Connectome tool
- Fixel plot
- Tractography tool
- ROI editor

Note that the ODF display tool is intentionally omitted from this list: this is because the *type* of ODF cannot be reliably inferred from just the input image data alone, and so the user is forced to nominate the type of ODF by clocking on the corresponding button.

**Comment by daljit46** [comment]
To address your comment, I've now introduced a new `MR::GUI::MRView::QtHelpers` namespace which contains a `url_to_std_string` helper function that is used when handling drop events. 
One thing I'm not sure is where should `qthelpers.h` should reside. Currently, it's in `src/gui/mrview` but perhaps it makes more sense in `src/gui`?

**Comment by Lestropie** [comment]
-   Tried to test, but for some reason `libmrtrix-gui.dll` was not built. Fresh build directory, QT5. Will continue trying.
-   I think that this would be better targeted at `master` rather than `dev` given that it is a bug fix.

**Review by Lestropie — APPROVED** [review]
Fixed non-compilation by bringing up to date with `dev`.

Tested drag & drop on the listed toolbars.

Do maintain this should be back-propagated to `master`. But given the code formatting changes would cause conflicts across the board, could maybe merge this, manually re-implement on `master`, and then on `dev` accept only the `dev`-based change?

**Comment by daljit46** [comment]
> Do maintain this should be back-propagated to `master`. But given the code formatting changes would cause conflicts across the board, could maybe merge this, manually re-implement on `master`, and then on `dev` accept only the `dev`-based change?

Sounds good to me.

**Pull request merged**
