### PR TITLE
Tag 0.3.15

### PR DESCRIPTION
**Pull request by Lestropie**
An accumulation of changes that will all be pushed at once and the 0.3.15 tag will be formed. In part these are all being done together because they either change the user interface, or the default behaviour. Awaiting addition of `dwidenoise` command.

### CODE REVIEW

**Comment by Lestropie** [comment]
@maxpietsch `transformconvert` is failing assertions. About to have a look, but you're probably going to want to look at it even if I can find the solution myself.

**Comment by maxpietsch** [comment]
OK, I'll check what is failing.

**Comment by thijsdhollander** [comment]
Just did a completely fresh clone (deleted the mrtrix folder entirely before it for optimal cleanness) after the merge, followed by a `./configure release -dev` and a `./build`, but the latter one ended with:

```
...
(442/442) [LB] release/bin/tsfinfo
[SH] ./scripts/mrtrix_bash_completion
[DOC] generating user documentation (./docs)

/home/thijs/mrtrix3/docs/generate_user_docs.sh:

Error: please specify a directory
```

(the "`...`" part went fine)

**Comment by Lestropie** [comment]
@thijsdhollander I think this issue has come up once before, when the documentation page for `dirsplit` was erroneously deleted. There appears to be another linux binary called `dirsplit`, which, if executed with the `__print_usage_rst__` argument, produces this error. Running a `git status` should confirm (the `dirsplit` doc page should be empty).

**Comment by jdtournier** [comment]
[So there is](http://linux.die.net/man/1/dirsplit)! The question then is, why is the MRtrix3 version not being invoked preferentially? Does the `generate_user_docs.sh` script not set the PATH, or invoke commands using their relative paths?

**Comment by thijsdhollander** [comment]
That seems to be it indeed. `git status` returns

```
	modified:   docs/reference/commands/dirsplit.rst
	modified:   docs/reference/commands_list.rst
```

and `dirsplit.rst` is empty!

**Comment by Lestropie** [comment]
OK, must have flared up because of 8f1e685. I changed it to build the list of commands from the `cmd/` directory rather than `bin/`, so that when switching between git branches you don't accidentally add documentation for binaries that are lying around having been built on other branches.

**Comment by maxpietsch** [comment]
@Lestropie generate_user_docs still picks up scripts that may lie in the script folder

**Comment by Lestropie** [comment]
If it's lying in the scripts folder and hasn't been committed to a branch, then yes. Don't think there's anything that can be done about that, short of querying git. But you [no longer have to place a script in that directory in order to use the scripts library](http://mrtrix.readthedocs.io/en/latest/tutorials/FAQ.html#making-use-of-python-scripts-library), so just keeping such files out of there until they're committed to a branch is a better option.

**Comment by maxpietsch** [comment]
Oh, didn't know that. Neat :)

**Pull request merged**
