### PR TITLE
mrview: add config option to show ortho view in a row

### PR DESCRIPTION
**Pull request by jdtournier**
Adds a config file option `MRViewOrthoAsRow` to show the 3 orthoview panes in a row, e.g.:
Screenshot from 2020-01-23 14-08-27

Any use...?

### CODE REVIEW

**Comment by maxpietsch** [comment]
> Any use...?

Yes, useful for screenshots and widescreen monitors! I'd make it a view menu item or at east view tool option.

**Comment by jdtournier** [comment]
I knew someone would suggest that...

Ok, that would be easy to add, but this is one option that would really benefit from being persistent (i.e. automatically written back to the config file if modified in the UI). That would require a few additions to the config file handling - I'd been meaning to do this for some time, but it's pretty low priority... Also relates to #1868. And I'd be inclined to write that to a different config file than the main one to avoid the risk of inadvertently clobbering it. But that could easily be left for some other time...

**Comment by jdtournier** [comment]
BTW: I reckon this would live as a little check box in the view tool (it's similar to the lightbox mode's settings for number of rows & columns, for instance). Are you interested in taking that on...? :grin:

**Comment by maxpietsch** [comment]
I've spent quite some time on adding a little checkbox... Nearly there I think but I need some help with connecting the QT slot. Does not compile when I uncomment [this line](https://github.com/MRtrix3/mrtrix3/pull/1894/commits/86a483e778d65c9dd08db79a070520a2047e8523#diff-946b56617a4ae8cfde2faecc0c250589R1073).

**Comment by Lestropie** [comment]
@jdtournier: I'd make it a checkbox option in the View tool. :stuck_out_tongue_winking_eye: 

> I need some help with connecting the QT slot.

Why should you not be made to suffer as we have suffered? :smiling_imp:

I'll try to have a peek.

**Comment by jdtournier** [comment]
As far as I can tell, all you were missing was:
```
#include "gui/mrview/mode/ortho.h"
```
in `src/gui/mrview/tool/view.cpp`...

I've made other changes though. Incoming...

**Comment by maxpietsch** [comment]
There is still a bug in it: switching between ortho and other views makes the checkbox and the display inconsistent (until the checkbox is clicked once or twice depending on the default).

**Comment by jdtournier** [comment]
OK, I think that'll fix it. I'd forgotten that modes gets destroyed and constructed between switches - they're not persistent...

**Pull request merged**
