### PR TITLE
NIfTI: check consistency of sform and qform

### PR DESCRIPTION
**Pull request by jdtournier**
As discussed in #1210

Could still do with added FAQ or similar in documentation...

### CODE REVIEW

**Comment by Lestropie** [comment]
@jdtournier: Check that you're happy with that description in the docs.

**Comment by Lestropie** [comment]
I'm happy to go with that. Users will still get a warning in the case of any ambiguity once this is merged. Docs would need to be updated in addition to the code.

**Comment by jdtournier** [comment]
I have to say, I'm not that sure. I distinctly remember someone having issues due to us using the`qform` preferentially (I think there was a time when that was the default behaviour), when interacting with some other package... I think maybe we should add a config file option to allow users to decide for themselves? That way we could adopt what seems to be the spirit of the standard, but allow users to maintain the current behaviour if it causes problems for them. What do you think?

**Comment by Lestropie** [comment]
I thought of a config file entry on the way home but forgot to post it... Definitely let's do that.

I agree using `qform` is more consistent between the standard and *MRtrix3*'s own convention. So if a config file entry would catch that potential problematic case that was a long time ago and the details can't be remembered... I reckon go for that.

**Comment by jdtournier** [comment]
Good to hear, let's do that.

About that issue I mentioned just earlier, thinking about it some more, I think the problem was that at the time, we were only writing out the `sform`, and that other package relied exclusively on the `qform`. So it's a moot point anyway...

**Comment by Lestropie** [comment]
```
# command: tckgen SIFT_phantom/dwi.mif -algo seedtest -seed_random_per_voxel SIFT_phantom/mask.mif 27 tmp.tck -force && tckmap tmp.tck -template SIFT_phantom/dwi.mif - | testing_diff_image - tckgen/SIFT_phantom_seeds.mif [ ERROR ]
tckgen: [WARNING] existing output files will be overwritten
tckgen: preloading data for "SIFT_phantom/dwi.mif"...  [==================================================]
tckgen: [  0%]        1 seeds,        1 streamlines,        1 selected
tckgen: [  1%]       38 seeds,       38 streamlines,       38 selected
tckgen: [  1%]       39 seeds,       39 streamlines,       39 selected
tckgen: [  2%]       79 seeds,       79 streamlines,       79 selected
tckgen: [  4%]      157 seeds,      157 streamlines,      157 selected
tckgen: [  8%]      313 seeds,      313 streamlines,      313 selected
tckgen: [ 16%]      624 seeds,      624 streamlines,      624 selected
tckgen: [ 32%]     1246 seeds,     1246 streamlines,     1246 selected
tckgen: [ 64%]     2490 seeds,     2490 streamlines,     2490 selected
tckgen: [100%]     3888 seeds,     3888 streamlines,     3888 selected
tckmap: mapping tracks to image...  [==================================================]
testing_diff_image: [ERROR] images "/tmp/mrtrix-tmp-iQigO4.mif" and "tckgen/SIFT_phantom_seeds.mif" do not match within absolute precision of 0 (28 vs 27)
testing_diff_image: [ERROR] images "/tmp/mrtrix-tmp-iQigO4.mif" and "tckgen/SIFT_phantom_seeds.mif" do not match within absolute precision of 0 (26 vs 27)
testing_diff_image: [ERROR] exception thrown from one or more threads "loop threads"
```

o.0

**Comment by Lestropie** [comment]
Just discovered another confound related to this and other issues.

SPM's "Coregister: Estimate" functionality, which is commonly used for inter-modality intra-subject rigid-body registration, directly modifies the `sform` of the input NIfTI, but does *not* modify the `qform`. As such, if *MRtrix3* loads the `qform`, while a command-line warning is issued about this fact, such warnings are often ignored, and the image will appear in `mrview` as though the registration has not yet been performed.

**Comment by maxpietsch** [comment]
ANTs' (and ITK's) NIfTI handling differs again: 
`Therefore it can only use qform when reading a NIFTI-1 image. When writing NIFTI output, only the qform is written; the sform is replaced with zeros.`
https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F

**Comment by Lestropie** [comment]
> When writing NIFTI output, only the qform is written; the sform is replaced with zeros.

That's not so much of a concern; if anything *MRtrix3* is quite happy if one is set and the other is not. The problem with SPM is specifically because it modifies the sform in place but leaves the qform untouched. So if the qform is filled with valid data before that operation takes place, then after that operation, both will be flagged as being valid and both will contain valid data, yet they will be different from one another; hence the ambiguity.

**Pull request merged**
