### PR TITLE
Mrview transform tool

### PR DESCRIPTION
**Pull request by jdtournier**
Yet another old branch that's been sitting there gathering dust (for more than 2 years now...). 

This adds a tool to allow manual rigid-body transformations to be applied to the main image. The idea is similar to the clip planes handling: once activated, all camera actions apply to the main image's transform, rather than to the camera. This allows manual alignment to another image by e.g. loading the image to be registered to in the overlay, activating this tool, manipulating the image to align, then deactivating this tool and saving the image. Seems to work pretty well for this specific task... 

This does bring in quite a few changes to allow tools to override the mode's handling of camera manipulations, and also modifies the view tool to use this functionality. It also finally removes the Math::Versor class, which was just a thin wrapper to Eigen::Quaternion anyway. But there is a scope for a few bugs to have crept in, because of these changes and because of the substantial conflicts that the merge threw up...

### CODE REVIEW

**Comment by maxpietsch** [comment]
I noticed one small issue: The direction of left-click rotations is reversed in ortho-view and 3D view when the tool is on vs when it's off. Right-click rotations and translations are not affected.

**Comment by jdtournier** [comment]
Thanks Max, I hadn't spotted that. Should be fixed with that last commit.

**Comment by maxpietsch** [comment]
When no image is loaded, mrview sometimes segfaults when the tool is switched on and the (camera) orientation (and/or position?) is changed (a lot?):

```
Process 92237 launched: '/Users/mp/mrtrix3_dev3/bin/mrview' (x86_64)
Process 92237 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x90)
    frame #0: 0x0000000100165908 mrview`MR::GUI::MRView::Tool::Transform::pan_event(MR::GUI::ModelViewProjection const&) + 344
mrview`MR::GUI::MRView::Tool::Transform::pan_event:
->  0x100165908 <+344>: movaps 0x90(%rax), %xmm0
    0x10016590f <+351>: movaps %xmm0, -0x70(%rbp)
    0x100165913 <+355>: movaps %xmm0, -0xd0(%rbp)
    0x10016591a <+362>: movaps 0xa0(%rax), %xmm0
Target 0: (mrview) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x90)
  * frame #0: 0x0000000100165908 mrview`MR::GUI::MRView::Tool::Transform::pan_event(MR::GUI::ModelViewProjection const&) + 344
    frame #1: 0x0000000100165a5d mrview`non-virtual thunk to MR::GUI::MRView::Tool::Transform::pan_event(MR::GUI::ModelViewProjection const&) + 13
    frame #2: 0x00000001000f0c4f mrview`MR::GUI::MRView::Mode::Base::pan_event() + 63
    frame #3: 0x0000000100069a37 mrview`MR::GUI::MRView::Window::gestureEventGL(QGestureEvent*) + 119
    frame #4: 0x00000001000699ab mrview`MR::GUI::MRView::Window::GLArea::event(QEvent*) + 27
    frame #5: 0x0000000100b05c1d QtWidgets`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
    frame #6: 0x0000000100b0798c QtWidgets`QApplication::notify(QObject*, QEvent*) + 2940
    frame #7: 0x00000001019db994 QtCore`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
    frame #8: 0x0000000100b55ac0 QtWidgets`___lldb_unnamed_symbol319$$QtWidgets + 5584
    frame #9: 0x0000000100b52875 QtWidgets`___lldb_unnamed_symbol316$$QtWidgets + 5445
    frame #10: 0x0000000100b572e7 QtWidgets`___lldb_unnamed_symbol325$$QtWidgets + 1191
    frame #11: 0x0000000100b08902 QtWidgets`QApplication::notify(QObject*, QEvent*) + 6898
    frame #12: 0x00000001019db994 QtCore`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
    frame #13: 0x0000000100b0bff7 QtWidgets`QApplicationPrivate::translateRawTouchEvent(QWidget*, QTouchDevice*, QList<QTouchEvent::TouchPoint> const&, unsigned long) + 2887
    frame #14: 0x0000000100b5d6b0 QtWidgets`___lldb_unnamed_symbol431$$QtWidgets + 1152
    frame #15: 0x0000000100b05c1d QtWidgets`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
    frame #16: 0x0000000100b07055 QtWidgets`QApplication::notify(QObject*, QEvent*) + 581
    frame #17: 0x00000001019db994 QtCore`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
    frame #18: 0x00000001010df10e QtGui`QGuiApplicationPrivate::processTouchEvent(QWindowSystemInterfacePrivate::TouchEvent*) + 5262
    frame #19: 0x00000001010c2adb QtGui`QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 219
    frame #20: 0x0000000108be8778 libqcocoa.dylib`___lldb_unnamed_symbol684$$libqcocoa.dylib + 40
    frame #21: 0x00007fff30ed9b21 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #22: 0x00007fff30ed9ac0 CoreFoundation`__CFRunLoopDoSource0 + 103
    frame #23: 0x00007fff30ed98d4 CoreFoundation`__CFRunLoopDoSources0 + 209
    frame #24: 0x00007fff30ed8740 CoreFoundation`__CFRunLoopRun + 1272
    frame #25: 0x00007fff30ed7bd3 CoreFoundation`CFRunLoopRunSpecific + 499
    frame #26: 0x00007fff2fa2d65d HIToolbox`RunCurrentEventLoopInMode + 292
    frame #27: 0x00007fff2fa2d2a9 HIToolbox`ReceiveNextEventCommon + 356
    frame #28: 0x00007fff2fa2d127 HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 64
    frame #29: 0x00007fff2e09dba4 AppKit`_DPSNextEvent + 990
    frame #30: 0x00007fff2e09c380 AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
    frame #31: 0x00007fff2e08e09e AppKit`-[NSApplication run] + 658
    frame #32: 0x0000000108be75e8 libqcocoa.dylib`___lldb_unnamed_symbol665$$libqcocoa.dylib + 2648
    frame #33: 0x00000001019d7b0f QtCore`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
    frame #34: 0x00000001019dbfe2 QtCore`QCoreApplication::exec() + 130
    frame #35: 0x0000000100166e25 mrview`run() + 85
    frame #36: 0x0000000100166afb mrview`main + 75
    frame #37: 0x00007fff6857d7fd libdyld.dylib`start + 1
    frame #38: 0x00007fff6857d7fd libdyld.dylib`start + 1
```

**Comment by jdtournier** [comment]
OK, thanks for the report. That shouldn't happen - these handlers shouldn't be invoked if no image is loaded. Let me know if that last commit fixes it...

**Comment by maxpietsch** [comment]
I think this fixes it. In c0fb794, I changed the event's return value to true. Now good to merge as far as I can tell.

**Comment by jdtournier** [comment]
Oops. Thanks, yes, that makes more sense...

**Pull request merged**
