### PR TITLE
command_history: Only use quotes when needed

### PR DESCRIPTION
**Pull request by Lestropie**
`command_history` was giving me the irrits trying to read it with all the quotation marks everywhere, so I had a go at getting rid of them all. Could do with extra eyes to check if I've overlooked any cases.

### CODE REVIEW

**Comment by jdtournier** [comment]
Yes, I've been thinking this would be a nice addition. But I reckon your `argv_quoted()` is a bit OTT: I  don't get why you're quoting the string if it contains a path separator? Also, on Windows `PATH_SEPARATOR` is defined as `"\\/"` - the two characters that could be used as path delimiters (especially when using MSYS2), and I don't think your logic matches that (?).

I reckon it would be sufficient to use [std::string::find_first_of()](https://en.cppreference.com/w/cpp/string/basic_string/find_first_of) to check whether:
```C++
string.find_first_of (" \t\n:&|<>*?[];#\$`()") != std::string::npos
```
I think I've got the main ones in that list... It doesn't need to be perfect, I don't think - as long as it catches 99.9% of what we're likely to encounter in the wild. Anything not contained in that list is probably so weird that it might cause all sorts of other issues anyway...

Also: I'd enclose in single quote (`'`), not double quotes: this provides stronger guarantees in that the shell performs no interpretation whatsoever on single-quoted strings, but still performs variable and command substitution for double-quoted strings.

And if we _really_ want to cover all cases, we'd probably also need to double-escape the backslash, and escape any single quotes...

**Comment by jdtournier** [comment]
> In that case it should really be called PATH_SEPARATORS

Sure, we could do that. And better still, document it with a Doxygen comment...

> I was trying to go for the conservative option of identifying strings where it's safe to omit the quotations, as opposed to identifying strings where the quotations are necessary. 

Actually, looking back at what you have, the thing that jarred really boils down to that path separator misunderstanding. I think your approach is just as clean, to be honest. Ignore me, let's stick with your test.

The point about using single quotes, and escaping any single quotes or backslashes still stands, but that's a distinct issue.

**Comment by Lestropie** [comment]
OK, think I got it:
```
$ mrconvert test_in.mif test_out.mif
mrconvert: [100%] copying from "test_in.mif" to "test_out.mif"
$ mrinfo test_out.mif
...
command_history:   mrconvert test_in.mif test_out.mif  (version=3.0_RC3-188-gc7ec14f2-dirty)
...

$ mrconvert test_in.mif test_out\ space.mif
mrconvert: [100%] copying from "test_in.mif" to "test_out space.mif"
$ mrinfo test_out\ space.mif 
...
command_history:   mrconvert test_in.mif 'test_out space.mif'  (version=3.0_RC3-188-gc7ec14f2-dirty)
...

$ mrconvert test_in.mif test_out\\backslash.mif
mrconvert: [100%] copying from "test_in.mif" to "test_out\backslash.mif"
$ mrinfo test_out\\backslash.mif
...
command_history:   mrconvert test_in.mif 'test_out\\backslash.mif'  (version=3.0_RC3-188-gc7ec14f2-dirty)
...

$ mrconvert test_in.mif "test_out'singlequote.mif"
mrconvert: [100%] copying from "test_in.mif" to "test_out'singlequote.mif"
$ mrinfo test_out\'singlequote.mif
...
command_history:   mrconvert test_in.mif 'test_out\'singlequote.mif'  (version=3.0_RC3-188-gc7ec14f2-dirty)
...
```

Not yet tested on Windows though.

Also, I suspect it was [this usage](https://github.com/MRtrix3/mrtrix3/blob/master/core/file/path.h#L51-L55) that threw me off w.r.t. `PATH_SEPARATOR`:
```
    inline std::string dirname (const std::string& name)
    {
      size_t i = name.find_last_of (PATH_SEPARATOR);
      return (i == std::string::npos ? std::string ("") : (i ? name.substr (0,i) : std::string (PATH_SEPARATOR)));
    }
```
So on Windows, if a file is stored at the MSYS2 root, `dirname()` will currently return "`\/`". Probably not a huge issue.

**Comment by jdtournier** [comment]
TravisCI is having a few issues at the moment, for some reason. We keep getting errors at the `apt-get install` stage:
```
apt-get install failed
$ cat ~/apt-get-update.log
Get:1 http://apt.llvm.org/trusty llvm-toolchain-trusty-6.0 InRelease [4,236 B]
Ign:2 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 InRelease
Get:3 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release [2,495 B]
Get:6 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release.gpg [801 B]
Ign:4 http://toolbelt.heroku.com/ubuntu ./ InRelease
Ign:8 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:7 http://toolbelt.heroku.com/ubuntu ./ Release
Ign:9 http://mirror.jmu.edu/pub/ubuntu trusty InRelease
Get:10 http://mirror.jmu.edu/pub/ubuntu trusty-updates InRelease [65.9 kB]
Get:11 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease [15.4 kB]
Get:5 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]
Get:12 http://apt.llvm.org/trusty llvm-toolchain-trusty-6.0/main amd64 Packages [6,575 B]
Ign:12 http://apt.llvm.org/trusty llvm-toolchain-trusty-6.0/main amd64 Packages
Get:13 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease [61.4 kB]
Get:14 https://dl.hhvm.com/ubuntu trusty InRelease
Get:15 http://apt.llvm.org/trusty llvm-toolchain-trusty-6.0/main i386 Packages [6,571 B]
Ign:15 http://apt.llvm.org/trusty llvm-toolchain-trusty-6.0/main i386 Packages
Get:16 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4/multiverse amd64 Packages [11.8 kB]
Ign:17 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
Get:12 http://apt.llvm.org/trusty llvm-toolchain-trusty-6.0/main amd64 Packages [6,575 B]
Ign:12 http://apt.llvm.org/trusty llvm-toolchain-trusty-6.0/main amd64 Packages
Get:15 http://apt.llvm.org/trusty llvm-toolchain-trusty-6.0/main i386 Packages [6,571 B]
Ign:15 http://apt.llvm.org/trusty llvm-toolchain-trusty-6.0/main i386 Packages
Get:12 http://apt.llvm.org/trusty llvm-toolchain-trusty-6.0/main amd64 Packages [31.2 kB]
Err:12 http://apt.llvm.org/trusty llvm-toolchain-trusty-6.0/main amd64 Packages
  Hash Sum mismatch
Get:18 http://mirror.jmu.edu/pub/ubuntu trusty-backports InRelease [65.9 kB]
Get:15 http://apt.llvm.org/trusty llvm-toolchain-trusty-6.0/main i386 Packages [31.2 kB]
Err:15 http://apt.llvm.org/trusty llvm-toolchain-trusty-6.0/main i386 Packages
  Hash Sum mismatch
Get:20 http://dl.google.com/linux/chrome/deb stable Release [1,189 B]
Get:21 http://mirror.jmu.edu/pub/ubuntu trusty-security InRelease [65.9 kB]
Get:22 https://dl.hhvm.com/ubuntu trusty/main amd64 Packages [1,815 B]
Get:23 http://dl.google.com/linux/chrome/deb stable Release.gpg [819 B]
Get:24 http://mirror.jmu.edu/pub/ubuntu trusty Release [58.5 kB]
Get:25 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease [15.4 kB]
Get:26 http://mirror.jmu.edu/pub/ubuntu trusty Release.gpg [933 B]
Get:27 http://mirror.jmu.edu/pub/ubuntu trusty-updates/universe Sources [259 kB]
Get:28 http://mirror.jmu.edu/pub/ubuntu trusty-updates/main amd64 Packages [1,366 kB]
Get:29 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease [15.4 kB]
Get:30 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main amd64 Packages [190 kB]
Get:31 http://mirror.jmu.edu/pub/ubuntu trusty-updates/main i386 Packages [1,290 kB]
Get:32 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease [15.4 kB]
Get:33 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main i386 Packages [189 kB]
Get:34 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,112 B]
Get:35 http://mirror.jmu.edu/pub/ubuntu trusty-updates/restricted amd64 Packages [21.4 kB]
Get:36 http://mirror.jmu.edu/pub/ubuntu trusty-updates/restricted i386 Packages [21.1 kB]
Get:37 http://mirror.jmu.edu/pub/ubuntu trusty-updates/universe amd64 Packages [602 kB]
Get:38 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty InRelease [15.4 kB]
Get:39 http://mirror.jmu.edu/pub/ubuntu trusty-updates/universe i386 Packages [589 kB]
Get:40 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease [15.5 kB]
Get:41 http://mirror.jmu.edu/pub/ubuntu trusty-updates/multiverse amd64 Packages [16.0 kB]
Get:42 http://mirror.jmu.edu/pub/ubuntu trusty-updates/multiverse i386 Packages [16.5 kB]
Get:43 http://mirror.jmu.edu/pub/ubuntu trusty-backports/main amd64 Packages [14.7 kB]
Get:44 http://mirror.jmu.edu/pub/ubuntu trusty-backports/main i386 Packages [14.7 kB]
Get:45 http://mirror.jmu.edu/pub/ubuntu trusty-backports/restricted amd64 Packages [40 B]
Get:46 http://mirror.jmu.edu/pub/ubuntu trusty-backports/restricted i386 Packages [40 B]
Get:47 http://mirror.jmu.edu/pub/ubuntu trusty-backports/universe amd64 Packages [52.5 kB]
Get:48 http://mirror.jmu.edu/pub/ubuntu trusty-backports/universe i386 Packages [52.4 kB]
Get:49 http://mirror.jmu.edu/pub/ubuntu trusty-backports/multiverse amd64 Packages [1,392 B]
Get:50 http://mirror.jmu.edu/pub/ubuntu trusty-backports/multiverse i386 Packages [1,376 B]
Get:51 http://mirror.jmu.edu/pub/ubuntu trusty-security/universe Sources [95.2 kB]
Hit:52 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release
Get:53 http://mirror.jmu.edu/pub/ubuntu trusty-security/main amd64 Packages [947 kB]
Get:54 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main amd64 Packages [1,710 B]
Hit:55 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
Get:57 http://mirror.jmu.edu/pub/ubuntu trusty-security/main i386 Packages [873 kB]
Get:58 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages [1,702 B]
Get:59 http://mirror.jmu.edu/pub/ubuntu trusty-security/restricted amd64 Packages [18.1 kB]
Get:60 http://mirror.jmu.edu/pub/ubuntu trusty-security/restricted i386 Packages [17.8 kB]
Get:61 http://mirror.jmu.edu/pub/ubuntu trusty-security/universe amd64 Packages [307 kB]
Get:62 http://mirror.jmu.edu/pub/ubuntu trusty-security/universe i386 Packages [294 kB]
Get:63 http://mirror.jmu.edu/pub/ubuntu trusty-security/multiverse amd64 Packages [4,721 B]
Get:64 http://mirror.jmu.edu/pub/ubuntu trusty-security/multiverse i386 Packages [4,876 B]
Get:65 http://mirror.jmu.edu/pub/ubuntu trusty/universe Sources [7,926 kB]
Get:67 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main amd64 Packages [3,482 B]
Get:68 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main i386 Packages [3,482 B]
Get:70 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main amd64 Packages [7,494 B]
Get:71 http://mirror.jmu.edu/pub/ubuntu trusty/main amd64 Packages [1,743 kB]
Get:72 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main i386 Packages [7,640 B]
Get:73 http://mirror.jmu.edu/pub/ubuntu trusty/main i386 Packages [1,739 kB]
Get:75 http://mirror.jmu.edu/pub/ubuntu trusty/restricted amd64 Packages [16.0 kB]
Get:76 http://mirror.jmu.edu/pub/ubuntu trusty/restricted i386 Packages [16.4 kB]
Get:77 http://mirror.jmu.edu/pub/ubuntu trusty/universe amd64 Packages [7,589 kB]
Get:78 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main amd64 Packages [430 B]
Get:80 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages [430 B]
Get:81 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main amd64 Packages [94.7 kB]
Get:82 http://mirror.jmu.edu/pub/ubuntu trusty/universe i386 Packages [7,597 kB]
Get:85 http://mirror.jmu.edu/pub/ubuntu trusty/multiverse amd64 Packages [169 kB]
Get:86 http://mirror.jmu.edu/pub/ubuntu trusty/multiverse i386 Packages [172 kB]
Get:87 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty/main i386 Packages [93.0 kB]
Get:88 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main amd64 Packages [1,551 B]
Get:89 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main i386 Packages [1,551 B]
Fetched 34.9 MB in 4s (8,085 kB/s)
Reading package lists...
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch http://apt.llvm.org/trusty/dists/llvm-toolchain-trusty-6.0/main/binary-amd64/Packages  Hash Sum mismatch
E: Failed to fetch http://apt.llvm.org/trusty/dists/llvm-toolchain-trusty-6.0/main/binary-i386/Packages  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $TRAVIS_APT_OPTS install g++-7 clang-6.0 zlib1g-dev libqt4-opengl-dev python3 python-pip python3-pip" failed and exited with 100 during .
```
Restarting the job typically sorts it out though. Hopefully it'll eventually work itself out...

**Comment by jdtournier** [comment]
@Lestropie: struggling a bit to prevent AppVeyor from building the branch tip rather than the PR merge commit only (we don't need testing on the branch tip, it's redundant). I think I've got the settings right now (I've ticked the 'Do not build feature branches with open Pull Requests' checkbox on the AppVeyor settings), maybe it's just a matter of waiting for the changes to propagate through the system..?

**Comment by Lestropie** [comment]
I had to faff about a bit to get it set up correctly. Think the one you need is "Branches to build": Set to "Only branches listed below" and add "`master`" to the list, then make sure to hit "Save" at the bottom of the page.

I got an e-mail from AppVeyor saying I had access to the new account, but AppVeyor is still showing me only the [old project within my own account](https://ci.appveyor.com/project/Lestropie/mrtrix3/history). I can get to the [new project](https://ci.appveyor.com/project/MRtrix3/mrtrix3/history) via the CI links within GitHub, but I seem to only have read access (only have "Latest build" and "History" tabs; on the old project I also have "Deployments", "Events" and "Settings").

**Comment by Lestropie** [comment]
> the changes in the `argv_quoted()` call are basically two-fold:

> - the remaining tests after the first line (i.e. checking for : on Windows or the path separators) are redundant since they'll already trigger the first set of tests anyway (they're not alphanumeric, underscores, or hyphens).

> - why quote the string if it's a (Unix) path separator? That doesn't get interpreted by the shell in anyway, so I've added it to your list of explicitly allowed characters.

I think you're getting mixed up between my approach and your first proposed alternative? This is a *white-list*. Those conditions were there so that the presence of (either) path separator, and/or a "`:`" as the second character on Windows, would *not* trigger quotation. With your change in b0a70183, any Windows-style path will be quoted regardless of whether or not it contains problematic characters.

**Comment by jdtournier** [comment]
> I think you're getting mixed up between my approach and your first proposed alternative? This is a white-list. 

I _think_ that was my understanding... The points were:

- I think only the _Unix_ file separator should be allowed without quoting. The Windows one is a backslash, and if you copy/paste that onto the MSYS2 command-line, it _will_ escape the following character - not what you're after...

- For the colon, I reckon what you've got is probably OK - I just thought it should probably be escaped if encountered anywhere, since [it is a shell builtin](https://www.tldp.org/LDP/abs/html/special-chars.html#COLON0REF). But I agree it's unlikely to cause trouble in the context where you allow it. In fact, we could probably allow it regardless, to be fair: there's no chance of finding that colon on its own surrounded by white space (and hence interpretable by BASH) and _not_ quoted by the code as it stands... So maybe we could just whitelist it?

**Comment by jdtournier** [comment]
> Think the one you need is "Branches to build": Set to "Only branches listed below" and add "master" to the list, then make sure to hit "Save" at the bottom of the page.

I did that for both `master` and `dev`. Maybe this will only apply for new pull requests...? In any case, I've made sure only the pull request CI build is required for the merge, which is what matters. Let's see how we go.

> I got an e-mail from AppVeyor saying I had access to the new account, but AppVeyor is still showing me only the old project within my own account.

I had to log out and log back in again, as [per  these instructions](https://www.appveyor.com/docs/team-setup/#add-yourself-as-co-administrator). When I try to log back in, it asks whether I want to access my personal or organisation account. Do you get something like that...?

> I can get to the new project via the CI links within GitHub, but I seem to only have read access (only have "Latest build" and "History" tabs; on the old project I also have "Deployments", "Events" and "Settings").

OK, maybe that's to do with the restrictions for team members. Can you abort or restart a build, though...?

**Comment by Lestropie** [comment]
> The Windows one is a backslash, and if you copy/paste that onto the MSYS2 command-line, it will escape the following character - not what you're after...

:+1:

> I had to log out and log back in again, as per these instructions.

:+1: Got admin access to new account now.

**Comment by Lestropie** [comment]
> For the colon, ...

Probably safest to have a conservative white-list and leave it out. Besides, if there's a `C:\...`-like path, it's going to need to be quote-escaped due to the backslash regardless of whether or not the colon is white-listed.

> struggling a bit to prevent AppVeyor from building the branch tip rather than the PR merge commit only

Made the mistake of deleting the project within my own AppVeyor account, so now I can't go back and compare its settings with the new project :-/

-----

Happy for this to be merged if you are.

**Comment by jdtournier** [comment]
Merged. Let's keep an eye on the AppVeyor situation. I suspect we'll need to look at new pull requests to see whether it does in fact work as expected...

**Pull request merged**
