### PR TITLE
Regular merge of master hotfixes to dev

### PR DESCRIPTION
**Pull request by Lestropie**
Triggered in particular to grab file `.git-blame-ignore-revs` added in #2592 to be used in #2652.

Some minor conflicts arising from:

-   #2667 on `master` and removal of `MEMALIGN` in #2297 on `dev`
-   Surface VTK changes #2654 / #2656.
-   Independent changes to the binaries test data on both branches, which required explicit manual merging.
    (Also doing cleanup of branches over there to have branch tips reflect pointers on this repository and delete branches corresponding to merged PRs)

### CODE REVIEW

**Comment by Lestropie** [comment]
@MRtrix3/mrtrix3-devs Anyone help with the mac CI failure?

**Comment by daljit46** [comment]
I think it was just a backend issue with homebrew, I reran the test and I think it should pass now.

**Comment by jdtournier** [comment]
I think the same thing happened with an earlier PR we merged recently. Re-running the job seemed to work ok then, not sure why it failed the first time...

**Comment by daljit46** [comment]
It's probably this https://github.com/Homebrew/homebrew-core/issues/135315

**Pull request merged**
