### PR TITLE
mrtransform Jacobian modulation and explicit reorientation

### PR DESCRIPTION
**Pull request by maxpietsch**
This addresses #1484 and #1485:

- added option for modulation by the determinant of the Jacobian of the warp of by the determinant of the linear transformation.
- makes FOD reorientation a mandatory option if the number of volumes indicates a SH image with lmax >= 2

The new option-logic follows what we discussed a while back [here](https://github.com/MRtrix3/mrtrix3/issues/1485#issuecomment-460703161):
```
# sh.mif: lmax>=2, scalar.mif: number of volumes not in [6, 15, 28, 45, ...]
mrtransform sh.mif -reorient_fod bool ...  #  reorientation explicit
mrtransform sh.mif  ...  #  error: missing option -reorient_fod
mrtransform scalar.mif ...  #  fine
mrtransform scalar.mif -reorient_fod true ...  #  error

mrtransform sh.mif -reorient_fod true -modulate fod ... #  reorientation and aPSF modulation
mrtransform sh.mif -reorient_fod true -modulate jac ... #  reorientation and jacobian modulation, warning
mrtransform sh.mif -reorient_fod false -modulate jac ... #  jacobian modulation, warning
```

I implemented Jac modulation in the warp adapter (and filter) as this makes it independent of the dimensionality of the image and required the least changes. Alternatively, one could implement Jacobian modulation as a second step after warping which could be faster for images with more than 3 dimensions.

Feel free to break it!

### CODE REVIEW

**Comment by maxpietsch** [comment]
Is everyone happy to merge this PR? I would like to include changes in the workshop if possible.

**Comment by bjeurissen** [comment]
Should

```
mrtransform sh.mif -reorient_fod false -modulate jac
```

not just perform jacobian modulation of the raw intensities _without warning_? 

And do

```
mrtransform volumes.mif -modulate jac
```

and 

```
mrtransform scalar.mif -modulate jac
```
also work?

**Comment by maxpietsch** [comment]
Yes, Jacobian modulation works with any number of volumes.

Technically it's perfectly fine to perform jacobian modulation on SH images but I'd warn users that they might want to use FOD modulation instead to prevent the use of Jacobian modulation in the FBA pipeline. The warning is:

```
mrtransform sh.mif -warp warp.mif -modulate jac warped_j.mif -reorient_fod yes
mrtransform: [WARNING] Jacobian modulation performed with FOD reorientation. Did you mean FOD modulation?
```

**Comment by Lestropie** [comment]
Not crucial for merge, but something I've thought about in the context of other commands: it should be possible to add to the list of tests verification that the command in fact fails appropriately given a certain combination of input data & command-line options.

-----

> mrtransform: [WARNING] Jacobian modulation performed with FOD reorientation. Did you mean FOD modulation?

Presumably part of the design of this wording is that if the number of volumes is appropriate for an SH image, but FOD reorientation is explicitly disabled, then Jacobian modulation is entirely reasonable (it might just be that the number of volumes happens to correspond to an SH series by chance); whereas if the input data are to be interpreted as FOD data (as inferred from the request for FOD reorientation), then Jacobian modulation doesn't make a lot of sense. But I wonder if the current message is a bit too brief for users to disentangle such.

Maybe something like:

"Input image being interpreted as FOD data (user requested FOD reorientation); FOD-based modulation would be more appropriate for such data than the requested Jacobian modulation"

**Comment by jdtournier** [comment]
Happy to merge, but maybe you'd like to add the more explicit error message suggested by @Lestropie first...?

**Comment by maxpietsch** [comment]
> Presumably part of the design of this wording is that if the number of volumes is appropriate for an SH image, but FOD reorientation is explicitly disabled, then Jacobian modulation is entirely reasonable (it might just be that the number of volumes happens to correspond to an SH series by chance); whereas if the input data are to be interpreted as FOD data (as inferred from the request for FOD reorientation), then Jacobian modulation doesn't make a lot of sense.

Yes, I've modified the warning message as suggested. The logic behind it is [here](https://github.com/MRtrix3/mrtrix3/blob/ebb953e6e264d242790e1923419e0b200363b678/cmd/mrtransform.cpp#L426).

**Pull request merged**
