### PR TITLE
tcksift2: -output_debug to fixel directory format

### PR DESCRIPTION
**Pull request by Lestropie**
-   When `-output_debug` is specified, outputs will:
    - Be written to a user-specified sub-directory, rather than the current working directory.
    - Be in the fixel directory format if fixel data export is enabled (which it is by default at compile time).
    - No longer produce duplicates of data that are identical before and after filtering.
-   Fixes erroneous formatting of `tcksift2` terminal progress.
-   Adds an `INFO`-level message regarding the decrease in entropy resulting from the modulation of streamline weights. This is the appropriate way to quantify the way in which a filtered tractogram with many streamlines, but very few streamlines with large weights and most streamlines with very small weights, is comparable to a tractogram that simply has very few streamlines. Nothing is done with the data, it's just printed, but it may be an alternative way in which to look at the differential effects of regularisation.

### CODE REVIEW

**Comment by Lestropie** [comment]
f82756f was necessary to pass binary test suite. For the test data, 1D fixel data files have the same voxel spacing as the index image, but contain the identity transform. This change simply reforms the modifications to the content of `core/fixel/helpers.h` to duplicate this behaviour.

If there is a desire for fixel data files to contain the same spatial position information as the fixel image to which they refer, then this would require setting both the voxel spacing and the transform, which currently is not achieved even in the test data. My own position is that these data are irrelevant for fixel data, and should either be ignored entirely or indeed expected to not be present in image headers for fixel data files (#1664), or it should be possible to use other formats for fixel data (#2435).

**Comment by jdtournier** [comment]
Had a quick look, but 8137340 is a bit of a monster... Everything looks OK to me, but this all code that I'm not very familiar with, so I'm going to defer to your judgement on that one - I won't be able to review this in any meaningful sense of the word! But this is on `dev`, feel free to merge if you're happy with your changes.

**Comment by Lestropie** [comment]
I might generate some test data for `-output_debug` for both `tcksift` and `tcksift2`.

**Comment by jdtournier** [comment]
The main thing is to make sure normal operation is left unaffected. I don't think you necessarily need to add tests for debug outputs!

**Comment by Lestropie** [comment]
Won't bother verifying contents of debugging outputs, but having the test executions use that option at least proves that it executes successfully, and also makes it easy for anyone to look at the contents generated for the test data.

**Pull request merged**
