### PR TITLE
Reslice adapter: allow use with complex numbers

### PR DESCRIPTION
**Pull request by jdtournier**
Simple fix to enable `Adapter::Reslice` to work as expected. Required for complex number support in `mrpeek` (PR: mrtrix3/mrpeek#47).

### CODE REVIEW

**Comment by Lestropie** [comment]
- [ ] Requires assessment of proposed change in #2785 before merging.

**Comment by jdtournier** [comment]
closed in favour of #2785.

**Comment by jdtournier** [comment]
OK, not closed, but merged #2785 in here as that's how it was set up...

**Review by Lestropie — APPROVED** [review]
GitHub *might* accept my review on this one; depends on whether it considers your merge commit, or my commit, to be "the most recent"...

**Pull request merged**
