### PR TITLE
WIP registration: extension to multi contrast 

### PR DESCRIPTION
**Pull request by maxpietsch**
This branch contains the proposed extension of the linear and nonlinear registration to multi-contrast ODF registration. Currently, the syntax of `mrregister` is

```
     mrregister [ options ] image1 image2 [ + contrast1 contrast2 ... ]

        image1 image2  input image 1 ('moving') and input image 2 ('template')

        + contrast1 contrast2  optional list of additional input images used as
                     additional contrasts. Can be used multiple times.
                     contrastX and imageX must share the same coordinate
                     system. 
```

and that of `population_template`:

```
     population_template [ options ] input_dir template [ + input_dir
     template... ]

        input_dir template Pair of an input directory containing all images used
                     to build the template and the output template image. For
                     multi-contrast registration, provide multiple pairs
                     separated by a plus sign. Example: wm_dir template_wm.mif +
                     gm_dir template_gm.mif
```

I am not intending to merge this into master anytime soon, as I am not happy with the general command line interface. However, I think that this pull request and branch might be a good place to discuss and fix issues that might come up with the multi-contrast registration itself. Feel free to give it a spin and let me know what you think!

### CODE REVIEW

**Comment by maxpietsch** [comment]
As briefly discussed in #1016 with @thijsdhollander, I've added a filter to mrfilter that should generate an image that can be used to reliably initialise the centre of mass and rotation with image moments. The filter masks an input image using an initial mask that covers the area of interest and potentially much more. It is tailored to data with potentially high-intensity artifacts and masks as typically generated by dwi2mask. 

The process is quite lengthy (and slow) but the mains steps are: The initial mask is used to sample the intensity distribution's median and mad value. The range [`median - zlower * mad`,`median + zupper * mad`] is then used to define a mask from the largest connected region. Holes in this VOI can then be bridged using dilate and erode steps. The output image is the masked first input volume with intensity values above `median + zupper * mad` clipped to the minimum of `median + zupper * mad` and `median + 2.5 * mad`.

So far, this filter seems to be robust if the initial mask is half-way sensible and works best if artifacts can be spatially separated from the signal by a low-intensity boundary. However, I'd appreciate testing with different data!

For instance, with default parameters and input image and mask:
screenshot0000
the output image and mask are:
screenshot0002

Another example with default parameters and an input image with a large bias field:
screenshot0000
output:
screenshot0001

**Comment by bjeurissen** [comment]
@Lestropie @maxpietsch: the '+'s had me stumped the first time I tried the command. I would vote for leaving them out as in the msmt_csd command.

**Comment by maxpietsch** [comment]
As I've written in the top post, I am not happy with the command line parsing as it stands. Our current command line interface is not ideal for multi-tissue registration with any combination of (optional) spatial and angular resolution and becomes difficult to read and type quite quickly. I've been working on it in the `mrreg` branch and am going to continue working on it - once a thesis is written... I'd also like to split functions such as initialisation, linear and nonlinear registration and transformation. For a sneak preview, have a look at the 'mrreg' script in that branch.

**Comment by jdtournier** [comment]
@maxpietsch: is this likely to be a candidate for RC4...?

**Comment by maxpietsch** [comment]
Closing in favour of #1575

**Pull request closed without merging**
