### PR TITLE
3.1.0 update

### PR DESCRIPTION
**Pull request by Lestropie**
This draft PR will show the set of changes to be applied as the `3.1.0` update, and track progress of manual integration of updates into that changeset.

The plan is that `3.1.0` will contain the set of changes currently on `dev`, as well as a number of active PRs not yet merged to `dev`; however it will *not* include the transition to `cmake` in #2689. This *may* mean that it will also omit the `clang-format` changes in #2652, though I'll need to bear this out.

Here's what I think the process will look like:

1.  Initial tip of the `dev_sans_cmake` branch is 8672d5b81785aeae5c062c5e07b1c02f83cfd7d5; this is the merge of PR #2720. I determined this by looking at the parents of merge commit 05878e51d7bf6ec30dd4f6893813e11e6b6d5c42, which was the acceptance of #2689.

2.  Identify set of PRs that have been merged onto `dev` following the merge of #2689.

3.  For each of the items in the list determined from point 2 above:
    1.  Do a merge onto the `dev_sans_cmake` branch.

4.  For currently open PRs targeting `dev`:
    1.  Resolve against `dev`.
    2.  Merge to `dev`.
    3.  Manually merge to `dev_sans_cmake`.

### CODE REVIEW

**Comment by Lestropie** [comment]
It looks as though the base commit I chose *does* include the `clang-format` changes. #2652 was merged via 5b0ec654ba01d0a5f6da4b5c52e80d3e44665755 2023-08-24, while #2689 was merged via 05878e51d7bf6ec30dd4f6893813e11e6b6d5c42 2023-10-19. This is the opposite order to what I had expected. I think this probably gives weight to inclusion of `clang-format` changes in `3.1.0`, given this may also make the various manual merges from `dev` to `dev_sans_cmake` easier.

**Comment by Lestropie** [comment]
List below is relevant PRs merged onto `dev` since #2689 at time of posting.
Found by creating proposal PR from `dev` to `dev_sans_cmake`, looking for merge commits, omitting anything `cmake`-related.
Can tick off checkboxes as they are manually merged into `dev_sans_cmake`.

- [ ] #2791 
- [ ] #2788
- [ ] #2784
- [ ] #2782
- [ ] #2760
- [ ] #2761
- [ ] #2775
- [ ] #2764
- [ ] #2774
- [ ] #2745 
    (I'm unsure whether this can be utilised in the absence of `cmake`?)

**Comment by Lestropie** [comment]
I have addressed the [list of PRs merged to `dev` subsequently to #2689](https://github.com/MRtrix3/mrtrix3/pull/2812#issuecomment-1953322097) using cherry-picking. It's possible that instead doing this using rebasing may be preferable from the perspective of cleanliness of commit history for `3.2.0`, when `dev` will be getting merged to `master` and that will include the contents of `dev_sans_cmake` after this PR is merged. However I'm inexperienced with rebasing. I'll give it a go and see if I can make it work, and if so this pranch can be force-pushed.

**Comment by tclose** [comment]
What is the reasoning behind dropping cmake from this release?

**Comment by Lestropie** [comment]
Reasoning included regular ongoing issues on `dev`, requirement to change Python executable script handling (#2741), desire to alter packaging for distribution (#2807), possibility of further reorganisation of filesystem structure, lack of solution for external "projects" / "extensions" (ie. C++ code that compiles against the shared library / Python scripts that execute against the API). However it looks like we are now aborting this prospect and are going to include `cmake` in `3.1.0`.

**Pull request closed without merging**
