### PR TITLE
strip() function now also strips null characters

### PR DESCRIPTION
**Pull request by jdtournier**
This should sort out dangling null characters in DICOM fields - see #1347.

Not sure whether this needs to be merged to `master` though. It's a non-critical bug fix, might be better going to `dev`...

### CODE REVIEW

**Comment by jdtournier** [comment]
I should point out that most of these changes are cosmetic (update code to C++11 syntax). The only line that matters here is [this one](https://github.com/MRtrix3/mrtrix3/pull/1349/files?utf8=%E2%9C%93&diff=unified&w=1#diff-862ff24ad0989a05134c5351fc903920L165).

**Comment by thijsdhollander** [comment]
> It's a non-critical bug fix, might be better going to dev...

Yes, agreed.

**Comment by jdtournier** [comment]
Ok, rebasing onto `dev`. Note this brings all the hotfixes from `master` into `dev` too.

**Comment by jdtournier** [comment]
Everything also checks out on my local DICOM tests. :+1:

**Comment by thijsdhollander** [comment]
Looks good; I'll hit the button. :+1:

**Pull request merged**
