### PR TITLE
Global tractography

### PR DESCRIPTION
**Pull request by dchristiaens**
This branch adds a command `tckglobal`, which implements my multi-shell multi-tissue global tractography method.

The code is ported to the new syntax (#225), and builds without warnings on my Mac OS X and Ubuntu systems. I've added docs and I'll create a detailed wiki page for it too. This latest version was tested in many datasets, but anyone is invited to try and break it :-)

Finally, I will also add tests for Travis CI at some point, but currently there's no multi-shell data available in the testing repo. I guess we should add this for testing msdwi2fod too.

### CODE REVIEW

**Comment by jdtournier** [comment]
Happy to merge, but just thought I'd check whether you're happy for this to happen before we update the license (#31)? We also need to have a frank discussion about the copyright notice (#9). I'll get the discussion going on both of these issues in their respective threads...

**Comment by dchristiaens** [comment]
Regarding the global tractography code, ideally I adopt the same licence as the rest of MRtrix. Currently it's very simple: mrtrix is GPL thus tckglobal is GPL. I'm happy with a more permissive license along the lines of MPL or LGPL. However, I do want modifications to the algorithm implementation be made open source, and therefore think MIT or Apache licences are too permissive. Hence, should you decide to switch to MIT/Apache, I'd need to insert a separate license for this part of the library, or we should revisit the original plan to distribute it as a separate module after all. But I'd much rather have it go in the main library under MPL/LGPL terms.

**Comment by thijsdhollander** [comment]
I'd say, let's have it in the main one under MPL terms. :-)

**Comment by thijsdhollander** [comment]
Just checked some more: it all looks nice and solid!  I'd be happy to have a reference to the TODI paper included in the reference list though (possibly accompanied by a "(when using the -todi option)"), since you directly allow it as an optional output. :-)

I do like your choice to have certain more advanced parameter options clearly separated from the rest.  It's an approach of categorising options that might actually also work well for a few other MRtrix commands that are heavy on optional parameters...

**Comment by jdtournier** [comment]
OK, guess everyone's happy to merge this in... We can sort out any remaining issues later.

**Pull request merged**
