### PR TITLE
mrview: deactivate pan gesture to avoid #761

### LINKED ISSUE #761: Sticky move in mrview
I just got a shiny mac, and for some two touch combination on the touchpad, mrview gets stuck moving the image around in the window and no amount of clicking or esc seems to stop it; I usually have to quit and relaunch.

I compiled recently from Git (I can pull, recompile and test when plugged into AC again) against Qt5 from brew, in case that helps. Maybe it's a glitch in Qt or Mac, not mrview. Any tips would be helpful.

### PR DESCRIPTION
**Pull request by maxpietsch**
Deactivating the pan gesture to avoid spurious start and finish and sticky pan (remains in GestureUpdated state) reproducible by rendering things with latency, for instance via increased ODF render detail in ortho view mode:

Prior to this change with Qt 5.15.2:
```
QGestureEvent((QPanGesture(state=GestureStarted,lastOffset=0,0QPointF(0,0),offset=0,0,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureFinished,lastOffset=0,0QPointF(0,0),offset=0,0,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureStarted,lastOffset=0,0QPointF(0,0),offset=0,0,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureFinished,lastOffset=0,0QPointF(0,0),offset=0,0,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureStarted,lastOffset=0,0QPointF(0,0),offset=0,0,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureFinished,lastOffset=0,0QPointF(0,0),offset=0,0,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureStarted,hotSpot=961,577,lastOffset=0,0QPointF(0,0),offset=-150,-143,acceleration=1,delta=-150,-143)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-150,-143QPointF(-150,-143),offset=-243,-210,acceleration=1,delta=-93,-67)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-210QPointF(-243,-210),offset=-243,-210,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-210QPointF(-243,-210),offset=-243,-210,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-210QPointF(-243,-210),offset=-243,-210,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-210QPointF(-243,-210),offset=-246,-209,acceleration=1,delta=-3,1)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-246,-209QPointF(-246,-209),offset=-246,-209,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-246,-209QPointF(-246,-209),offset=-244,-91,acceleration=1,delta=2,118)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-244,-91QPointF(-244,-91),offset=-243,-81,acceleration=1,delta=1,10)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-81QPointF(-243,-81),offset=-243,-82,acceleration=1,delta=0,-1)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureUpdated,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
QGestureEvent((QPanGesture(state=GestureFinished,hotSpot=961,577,lastOffset=-243,-82QPointF(-243,-82),offset=-243,-82,acceleration=1,delta=0,0)))
...
```
fixes #761
related: 5687708623505a

### CODE REVIEW

**Comment by jdtournier** [comment]
OK, so removing the pan gesture fixes the problem? I'm not sure what I'm looking at with all this output...

**Comment by maxpietsch** [comment]
Yes, not "grabbing" pan gestures solves the issue. 

The output above is Qt debug output I added when `mrview` is started in debug mode. It shows the type and state of the gesture whenever the GUI parses a gesture. I did not voluntarily use pan gestures. When the sticky pan happens, PanGestures with GestureUpdated state are reported repeatedly printed even without touching the touchpad (`delta=0,0`).

BTW, explicitly unregistering `QTapAndHoldGesture` did not solve the issue. Unregistering the pan gesture or not grabbing it did solve it.

**Comment by jdtournier** [comment]
OK, good to hear. I guess there's still quite a bit of cleaning up to be done before we can merge this...?

**Comment by maxpietsch** [comment]
I was thinking of leaving the Qt debug output there in debug mode but happy to remove it.

**Comment by jdtournier** [comment]
No issues with leaving the debug output in debug mode if you feel like it. 

I was looking more at the pan gesture handler - [these lines](https://github.com/MRtrix3/mrtrix3/pull/2310/commits/df7fd41e897d8aaf1d66e6ee75a0f198c3d74de2#diff-b7f50c4315e4905ded1140df924a71895d9c99682901de58f06efa6d4727ca83R1818-R1822). Is that still required?

**Review by jdtournier — APPROVED** [review]

**Pull request merged**
