### PR TITLE
Add registration and fixel-based analysis tools and documentation

### PR DESCRIPTION
**Pull request by draffelt**
Added the capability to perform rigid, linear and non-linear registration of scalar and FOD images. Including a script to estimate unbiased study-specific templates. In addition, several other tools required to perform a complete fixel-based analysis:

**New commands:**

- mrregister 
- fixelreorient
- fixelcorrespondence
- fixellog
- mraverage header
- mrcheckerboardmask
- mrmetric
- warp2metric
- warpconvert
- scripts/population_template
- scripts/dwiintensitynorm

**Extensive changes to:**

- mrtransform
- transformcalc

**Two new documentation workflow tutorials:**

- DWI_preprocessing_for_quantitative_analysis
- fixel_based_analysis

### CODE REVIEW

**Comment by jdtournier** [comment]
:beers:

**Comment by draffelt** [comment]
Shame the TravisCI checks are failing. `mrregister` takes longer than 10min to build and so Travis kills gcc when there is no output for longer than 10min! Clang compiles fine and tests ok.

Any suggestions on how to deal with this. Unfortunately I can't see anyway to change this build limit. Keen to merge today. I'm also writing a blog post to go with it.

**Comment by draffelt** [comment]
OK, it might a memory limit issue. I'll re-add the option to compile with only 1 core on travis.

**Comment by jdtournier** [comment]
Crap... How about we drop the g++ tests...? I don't think I've ever seen g++ fail when clang worked. It would also make for faster tests...

**Comment by draffelt** [comment]
I'm happy with that. We can always revert back if needed. Most of us probably use a more up-to-date version of gcc anyway.

**Comment by jdtournier** [comment]
:tada:

**Pull request merged**
