### PR TITLE
fod2dec tests

### PR DESCRIPTION
**Pull request by thijsdhollander**
It was about time I looked into this. :v:

### CODE REVIEW

**Comment by thijsdhollander** [comment]
Ok, so it seems I failed somewhere to update the submodule... I basically followed the instructions at https://github.com/MRtrix3/mrtrix3/tree/master/testing , added the test data using a separate standalone repo (option "2" in the instructions), and then moved on to the "Updating the main MRtrix3 repo to make use of the latest commits" part... (but using a new branch of course).

So... what could I be missing? :confused:  Running the tests locally also confirms it's not getting the data itself.

**Comment by jdtournier** [comment]
Not sure... Seems to work fine at my end. From `master`, I just tried running:

    $ git submodule
    b6d0e018d0bad96edec423b81ef1b006a94932fb testing/data (b6d0e01)

which shows that recent changes from @Lestropie & @draffelt haven't been picked up in `master` - not sure whether that's intentional, maybe these tests relate to unmerged changes. If they do, you need to worry about this, and branch off whatever the commit is that `master` is pointing to currently, otherwise these test data are going to land on `master` when you merge and potentially introduce failures on `master` - but that depends on whether the changes made recently by @Lestropie & @draffelt break anything - not sure, haven't checked. 

In any case, all I did was what it said on the howto:
```
$ git submodule update --remote
remote: Counting objects: 26, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 26 (delta 6), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (26/26), done.
From https://github.com/MRtrix3/test_data
  1fce3a9..f0e5aa9  master     -> origin/master
Submodule path '': checked out 'f0e5aa9fbf08135f6523376e705919d5addfd892'
    
$ git submodule
+f0e5aa9fbf08135f6523376e705919d5addfd892 testing/data (remotes/origin/HEAD)

$ git status
On branch master
Your branch is up-to-date with 'github/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   testing/data (new commits)

no changes added to commit (use "git add" and/or "git commit -a")

$ git add testing/data/
$ git status
On branch master
Your branch is up-to-date with 'github/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   testing/data

$ git commit -m "add test data"
[master 8b8aa6c] add test data
 1 file changed, 1 insertion(+), 1 deletion(-)

$ git submodule
 f0e5aa9fbf08135f6523376e705919d5addfd892 testing/data (remotes/origin/HEAD)
```

At this point, the tests should use that particular version of the test data. It'll be visible on other repo once you push, obviously. But it should work...?

**Comment by thijsdhollander** [comment]
Ok, it seems to be working now.  Before, `git submodule update --remote` gave me no output.  The only thing that has changed between that first attempt and this one, is that I ran the `run_tests` script in between both attempts (and I had never run it in that repo before): I figure that sets up the existence of the submodule on my repo?  Well, at least I learned a thing or two about submodules now. :smiley: :+1: 

The other remaining issue now is at the `test_data` repo's end: I hadn't even spotted yet that the current `mrtrix3` master wasn't pointing to the latest commit there, and you're right in guessing that that causes trouble for other tests related to the commits that changed testing data for them.  However, no need to worry about master getting messed up though: I can't merge this one to master before tests check out anyway of course. :wink:

**Comment by thijsdhollander** [comment]
So for the record: I fixed it by branching the test repo at the commit that master was pointing to before (as @jdtournier suggested above).

It does feel like it should've been the other way around from the outset: those test repo commits that hadn't been picked up on mrtrix3 master yet, should probably have been in a separate (non-master) branch on the test repo, if they were going to be related to a longer term unmerged branch on the mrtrix3 repo...?  Now the `fod2dec_data` branch on the test repo has to live until those other branches are merged into mrtrix3 master... it could be merged already, but can't be deleted yet.

**Comment by jdtournier** [comment]
Glad you guys were paying attention [the last time this happened](https://github.com/MRtrix3/mrtrix3/issues/602#issuecomment-225533742)... 😠 

Although it was suggested that [maybe the README should be updated](https://github.com/MRtrix3/mrtrix3/issues/693) to explain these subtleties... I'll get round to this now. There's actually quite a few issues that could do with being discussed in a bit more detail in there.

> Ok, it seems to be working now. Before, git submodule update --remote gave me no output. The only thing that has changed between that first attempt and this one, is that I ran the run_tests script in between both attempts (and I had never run it in that repo before): I figure that sets up the existence of the submodule on my repo? 

Yes, that's another thing that probably ought to be mentioned in the README... The first thing the `run_tests` script will do is update the submodule with this:

    git submodule update --init

Nothing will really work without this. Glad you figured it out eventually... I'll update the instructions.

**Comment by jdtournier** [comment]
OK, updated the README in #846 with hopefully clearer instructions. Let me know if anything is still murky...

> It does feel like it should've been the other way around from the outset: those test repo commits that hadn't been picked up on mrtrix3 master yet, should probably have been in a separate (non-master) branch on the test repo, if they were going to be related to a longer term unmerged branch on the mrtrix3 repo...?

Yes, that's exactly what should have happened _if these changes modified any pre-existing data_. It's fine to push simple additions to `master`. Hopefully the new & improved README will make this perfectly clear...

**Comment by draffelt** [comment]
Sorry guys. I had assumed the tests for master we're fairly static (i.e already done), and most of the large changes to MRtrix were happening in the new tag branch. Also, when I deleted the old .msf test data I thought I was days away from merging the fixel_format branch...but then other projects got in the way. Sorry...

**Comment by thijsdhollander** [comment]
Thanks for updating that readme: it does definitely all make good sense.  The moment I understood (hadn't looked into it before) that a submodule is nothing more than a simple pointer to a commit elsewhere, it all came together and I figured too that separate branches on the test repo were unavoidably needed for a construct like this.

Maybe this sentence in the solution:

> To avoid these issues, the best thing to do is to push any changes that modify existing data to a separate branch on the test_data repo, and merge these to master when the corresponding branch on the main MRtrix3 repo has also been merged. 

...does need a subtle change to lead to the behaviour that we're after, as in:

> To avoid these issues, the best thing to do is to push any changes that modify existing data to a separate branch on the test_data repo, and merge these to master **right before** the corresponding branch on the main MRtrix3 repo has also been merged.

This would effectively be needed so the pointer to the submodule can be changed to master on the test repo right before such a merge too; i.e., it would be good if the submodule on mrtrix3 master always points to a commit on the test repo master, right?

**Comment by jdtournier** [comment]
> Sorry guys. I had assumed the tests for master we're fairly static (i.e already done), and most of the large changes to MRtrix were happening in the new tag branch. Also, when I deleted the old .msf test data I thought I was days away from merging the fixel_format branch...but then other projects got in the way. Sorry...

😜 Ha! Couldn't find a emoji for crying my eyes out laughing... No need to get worried about this, this only affects us, not the users. No big deal. 

I reckon in future cases, we could probably also 'fix' it by pushing a new branch off the problematic `master` (just another label for the same commit), then force-updating `master` back to the previous working commit - I think you guys probably have rights to do this, I'll check. But in any case, it's not worth treating this as much more than a minor irritation...

> .. and merge these to master **right before** the corresponding branch on the main MRtrix3 repo has also been merged

No need. The only thing that matters is that the commit with the SHA1 checksum that has been recorded in the main repo still exists. As long as the branch that it belongs to hasn't been deleted, then it will be there. In fact, as soon as you merge, the commit SHA1 of that merge will differ from what's recorded in the main repo: `./run_tests` will still pull in the commit stated. 

The only recommendation I'd made here was that the branch be merged to `master` eventually - but that's just so that the relevant commit doesn't get garbage-collected later on if that branch ever gets deleted. As long as it's in `master`'s history, it will be there.

**Pull request merged**
