### PR TITLE
mrcalc: increase tolerance on transform match test

### PR DESCRIPTION
**Pull request by jdtournier**
As discussed in #1198

### CODE REVIEW

**Comment by jdtournier** [comment]
One slight concern with this pull request: currently [transform_check()](https://github.com/MRtrix3/mrtrix3/blob/dev/core/image_helpers.h#L407-L416) tests for equivalence within tolerance in an absolute sense. This is fine for the elements of the rotation part of the transform, since _MRtrix3_ keep this bit unitary.  But I think the translation components should really be checked within _relative_ tolerance, since the relevant units may differ for e.g. small animal studies, or in different contexts. It's no big deal since we're unlikely to encounter data where the spatial scale varies by several orders of magnitude compared to what we typically come across, but nonetheless... I'm considering making the translation part of the tests relative to the FoV - thoughts?

**Comment by maxpietsch** [comment]
You could apply both transformations to the [tetrahedron](https://github.com/MRtrix3/mrtrix3/blob/57e44453cf96a01e5d75c8edb577821daa5d3da9/src/registration/metric/params.h#L103 ) or the image [bounding box](https://github.com/MRtrix3/mrtrix3/blob/57e44453cf96a01e5d75c8edb577821daa5d3da9/core/math/average_space.cpp#L77) coordinates and check the deviations between both sets in units of voxel sizes.

**Comment by jdtournier** [comment]
@maxpietsch: good call. I've just pushed a change (76c57f7) that checks for the difference in real space positions of 4 opposing corners of the bounding box. See what you think...

**Comment by maxpietsch** [comment]
I've changed the test using the same coordinates but different tolerance criteria. Full FOV coordinates are compared to smallest voxel size. I added a test for voxel size as well. The latter is violated by `mrconvert` for conversion from mif to nii if I use a tolerance of 1e-6, fine with 1e-4.

**Comment by jdtournier** [comment]
OK, after a quick chat with @maxpietsch, I reckon a rethink is in order. At it stands, given the way our transforms are defined (i.e. image → scanner space), the test is not as practically useful as it seems. The main reason to invoke this check is to verify that it is safe to perform voxel-wise operations on two images, which implies that we are interested in verifying that voxels in the first image have a one-to-one correspondence with the voxels in the other. But this is not actually what this test does - or what its name suggests it does. 

So I reckon we should rename the test to something like `voxel_grids_match_in_scanner_space()` (a bit of a mouthful, I'll admit - but hopefully expressive :wink:), and in that test we'd check that:

- the dimensions for the first 3 (spatial) axes match;
- the projection of the bounding box corners into scanner space match within the specified tolerance, _relative_ to the smallest voxel dimension (note that this inherently ensures that the voxel sizes match). 

Wadayall reckon?

**Comment by maxpietsch** [comment]
I went ahead and made the changes @jdtournier suggested above. Feel free to revert or amend! I noticed that we check the image spacings without tolerance so I changed `spacings_match` to compare up to a specified tolerance in units of voxel dimensions but left the tolerance at zero for back compatibility. I'd suggest relaxing the voxel spacing test in `core/image_diff.h` to a tolerance of 1e-6.

**Comment by maxpietsch** [comment]
The last two commits change the nifti voxel size handling (reading) in that the header voxel spacing is taken from the pixdim header entry and not overwritten by the s-form-derived spacing.

This causes mrcalc to issue a warning about header transform mismatch if nifti files written before and after this change are compared or when a mismatching version of mrcalc is used. The difference in the read transformations is in the 7th digit.

(Travis fails due to a certificate error with bitbucket but tests complete sucessfully on my machine.)

**Comment by jdtournier** [comment]
I'm happy with these changes. Any other reactions before we merge?

**Comment by jdtournier** [comment]
No complaints - I'll merge now...

**Pull request merged**
