### PR TITLE
population_template uses rigid registration first. tweaks for linear registration

### PR DESCRIPTION
**Pull request by maxpietsch**
related to #827:

- `population_template`
    - rigid, affine and nonlinear registration are optional
    - defaults to run rigid registration before affine before nonlinear registration
    - changed arguments to be more similar to mrregister: for instance `-type rigid_affine_nonlinear`
- `mrregister`
    - added convergence check to speed up rigid registration
    - cleaned up base transformation class
- `dwiintensitynorm`
    - use new population_template syntax, 
    - avoid copy of warps
    - changed linear scale to `-rigid_scale 0.25,0.5,0.8,1.0 -affine_scale 0.7,0.8,1.0,1.0`

Do we want to tag this merge as it changes the command line interface of population_template?

### CODE REVIEW

**Comment by thijsdhollander** [comment]
Maybe together with #785 ?

**Comment by draffelt** [comment]
I'm hoping to merge the fixel_format branch into the tag 0.3.16 this week (which also has some changes to population_template which will require manual merging). So it might be worth you also merging it into there before I do?

**Comment by draffelt** [comment]
I've merged fixel_format into tag_0.3.16

**Comment by maxpietsch** [comment]
Closing this as it is merged into tag_0.3.16 (1242148e3e34fa4ddd6b6146dfb7b051e44). Love git but this was a rather painful merge...

**Pull request closed without merging**
