### PR TITLE
MRView: better filename elision in List Views

### PR DESCRIPTION
**Pull request by jdtournier**
Attempt at fixing #1866.

### CODE REVIEW

**Comment by maxpietsch** [comment]
RE  "when clicking at "open", to jump to directory of currently selected file in the toolbar" suggested in #1866

I am in favour of setting all open dialogues relative to the selected file in the toolbar or the last selected folder for that tool in the absence of selected items (or the main image if none exists so far). For example, a workflow where the current behaviour is counterproductive is opening a tractogram, setting a screenshot directory somewhere else, opening the next tractogram, setting a different screenshot directory, ...

**Comment by thijsdhollander** [comment]
I agree. 👍

**Comment by jdtournier** [comment]
OK, by popular request, the last few commits ensure that each tool keeps track of its own current working directory, and that seems to work as expected. Each tool will default to the current folder, or wherever the file dialog was when last used. Once used for a tool, that tool will keep track of its own folder, with no interaction with the other tools' folders. 

One outstanding question is whether the main window should also keep track of its own folder. Currently, opening an image (File->Open) will pop up the dialog wherever it was last used, tool or otherwise. I can see there would be an argument for ensuring the main window also tracks its own separate folder. 

Thoughts / feedback welcome.

**Comment by maxpietsch** [comment]
I'd also track the folder for the main window for the same reason as the toolbars but also to unify the behaviour of open dialogues across the app.

**Comment by jdtournier** [comment]
That's my feeling too. OK, the last couple of commits should address that. Untested at the moment other than checking it all compiles. I'll check it all works as expected on Monday.

**Comment by jdtournier** [comment]
OK, seems to check out... I'll merge now, feel free to re-open if issues arise.

**Pull request merged**
