### PR TITLE
Tag 3.0_RC3

### PR DESCRIPTION
**Pull request by Lestropie**
Creating the tag PR in order to produce the log of commits and code changes, which can then be used to write a changelog to post on the forum (to be drafted in the Staff section of the forum). Also created a milestone on GitHub.

### CODE REVIEW

**Comment by maxpietsch** [comment]
Another fix to add is the Dicom Time class. I can not compile this branch using clang on macOS:

```
ERROR: (39/75) [CC] tmp/core/file/dicom/mapper.o

clang++ -c -std=c++11 -flto=thin -DMRTRIX_MACOSX -fPIC -mmacosx-version-min=10.13 -DMRTRIX_WORD64 -DMRTRIX_TIFF_SUPPORT -isystem /usr/local/Cellar/libtiff/4.0.8_5/include -DEIGEN_FFTW_DEFAULT -isystem /usr/local/Cellar/fftw/3.3.6-pl2/include -Wall -O3 -DNDEBUG -Isrc -I./core -Icmd -isystem /usr/local/Cellar/eigen/3.3.4/include/eigen3 -DEIGEN_DONT_PARALLELIZE core/file/dicom/mapper.cpp -o tmp/core/file/dicom/mapper.o

failed with output

core/file/dicom/mapper.cpp:230:20: error: no matching function for call to 'isfinite'
        } else if (std::isfinite (frame.acquisition_time)) {
                   ^~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:397:5: note: candidate template ignored: disabled by 'enable_if' [with _A1 = MR::File::Dicom::Time]
    std::is_arithmetic<_A1>::value && std::numeric_limits<_A1>::has_infinity,
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:407:5: note: candidate template ignored: disabled by 'enable_if' [with _A1 = MR::File::Dicom::Time]
    std::is_arithmetic<_A1>::value && !std::numeric_limits<_A1>::has_infinity,
    ^
1 error generated.
```

**Comment by Lestropie** [comment]
I have activated automatic building of the `dev` branch on ReadTheDocs in case anybody wants to check anything.

**Comment by thijsdhollander** [comment]
Almost there.  Final TODOs: hit the button on #1228 (and #1061, if that was still the plan, or not?).  Finally, hit the button on this one, which will solve all documentation shenanigans immediately as well.  If done in this order, the only conflict with `master` at the moment seems to be `cmd/tckconvert.cpp`, which should be pretty minimal.

**Comment by Lestropie** [comment]
Pending a satisfactory solution to #1332, this is ready to go.

@jdtournier: Given the principal change is the SH precomputer fix, do you want to merge / tag / sign?

**Comment by jdtournier** [comment]
OK, release is on!

**Pull request merged**
