### PR TITLE
GitHub Issue / PR templates and contributing guidelines

### PR DESCRIPTION
**Pull request by maxpietsch**
- added bug report and feature request templates (#1652)
- It'd be good to add a custom template for contributions to the user documentation. What would our recommendation be regarding editing, documenting and testing the changes?

Should this go into master or dev?

---

A new issue looks like this:
image

image

image

---

A PR looks like this:
image

### CODE REVIEW

**Comment by Lestropie** [comment]
Some suggested changes to the PR template. The comment on creating commits with multiple authors is I think more appropriate in contributing guidelines rather than the PR template (as at the point of PR generation such commits have already been completed).

**Comment by Lestropie** [comment]
> Should this go into master or dev?

Given I've raised this for the sake of being able to say "yes" to the relevant questions in my grant application, it would need to go to `master` to satisfy such.

**Comment by Lestropie** [comment]
Having been through some codes of conduct yesterday, it's a bit of a minefield, and I'm not wholly happy with any of the well-established ones. I don't think that we're going to settle on something in that respect in the available time, especially if Donald is away. So we might omit the code of conduct from this particular exercise.

@maxpietsch Any comments on what I've changed?

**Comment by Lestropie** [comment]
@jdtournier: Could you please prioritise this given I flagged it as being present in the grant application, and had to provide a link to its eventual location on `master`.

**Comment by maxpietsch** [comment]
I forked mrtrix3 and created issues and PR using all templates: https://github.com/maxpietsch/mrtrix3/

- I wasn't shown the [contributing guidelines](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors) when opening an issue, maybe because I am the owner?
- Made some changes to the wording (and order) in `CONTRIBUTING.md` to emphasize more that we welcome contributions.
- Added a reference to `CONTRIBUTING.md` in `README.md` to give it more visibility
- The general issue template did not show but there is a smallish button to open a regular issue:
image

Feel free to amend/revert any of the above or merge.

**Comment by Lestropie** [comment]
:+1:

> I wasn't shown the contributing guidelines when opening an issue, maybe because I am the owner?

I think it's only supposed to appear for first-time contributors, and only as a link:

**Comment by jdtournier** [comment]
Looks all good to me. What codes of conduct have you looked at, and what problems would we need to address?

**Pull request merged**
