### PR TITLE
fix const-qualifier issue in image_diff.h

### PR DESCRIPTION
**Pull request by jdtournier**
As discussed in #1107.

### CODE REVIEW

**Comment by jdtournier** [comment]
OK, cherry-picked commit and changed base to `master`. I agree it might as well go there, it is completely harmless for users, only affects testing...

**Comment by jdtournier** [comment]
Seems there is an issue with the changes in #1103:
```
$ ./docs/generate_user_docs.sh && git diff --exit-code docs/ > gitdiff.log || echo "Documentation is not up to date; run docs/generate_user_docs.sh and commit changes"
./docs/generate_user_docs.sh: line 24: reference/commands_list.rst: No such file or directory
find: `../cmd/': No such file or directory
find: `../bin/': No such file or directory
./docs/generate_user_docs.sh: line 101: ./format_config_options: No such file or directory
Documentation is not up to date; run docs/generate_user_docs.sh and commit changes
```
I reckon we should revert that command to run within the `docs/` folder...

**Comment by Lestropie** [comment]
The changes in #1103 are to make it possible to run that script from *any* directory. If that's not working, it's something I need to fix in `dev`; mind you, I've no idea how it could have passed testing in the first place if that line weren't working...?

**Comment by Lestropie** [comment]
You might need to check exactly what you're running there: The current version of `generate_user_docs.sh` in `dev` [clearly](https://github.com/MRtrix3/mrtrix3/blob/dev/docs/generate_user_docs.sh) has the requisite path determinations, and wouldn't produce the errors you're getting. So you're running the TravisCI test from #1103 without the corresponding changes that came with #1103 to make it possible. I think.

**Comment by jdtournier** [comment]
Well this is straight off the current `master`, so not sure what's going on... You'll not there's only my commit in the diff here.

**Comment by Lestropie** [comment]
My guess is it's an issue with the PR re-basing then. The docs test is clearly [not present](https://github.com/MRtrix3/mrtrix3/blob/master/.travis.yml) in `master`, and as you say there's nothing listed in the diff of this PR outside of your one commit. So maybe create a fresh PR?

**Comment by jdtournier** [comment]
Yes, strange... I'll look into it later today when I have a minute.

**Comment by jdtournier** [comment]
OK, looks like TravisCI is getting confused by the forced push, and is trying to build the old commit (or something else altogether - there is no commit b0d6574, should be 92e57e7). Seems [others have also encountered issues with this](https://github.com/travis-ci/travis-ci/issues/6991). I'll close this pull request and create a fresh one, see if TravisCI picks it up properly this time...

**Pull request closed without merging**
