### PR TITLE
Docs: Update advanced debugging page for 3.0_RC1

### PR DESCRIPTION
**Pull request by Lestropie**
Triggered by [this post](http://community.mrtrix.org/t/error-segmentation-fault-invalid-memory-access/1071).

Is nice to have an up-to-date documentation page on debugging so that a link can be provided rather than having to repeat the details each time. However "Advanced debugging" documentation page was not updated to reflect changes to binary location and multi-build-configuration with `3.0_RC1`.

### CODE REVIEW

**Comment by Lestropie** [comment]
Are the instructions otherwise precisely equivalent? Because if not, it needs additional details, and I've never used it.

**Comment by jdtournier** [comment]
Good question. I think they are, but maybe someone with actual macOS experience can confirm...?

**Comment by chunhungyeh** [comment]
Oops... sorry, I thought that the commit comment would appeared over here... Well, anyway... just want to let you know that I added some instructions about using ``lldb`` on macOS, but I am not sure whether ``valgrind`` (which can be installed through Homebrew or Macports) would function similarly.

**Comment by Lestropie** [comment]
@chunhungyeh: The commit comment can still be accessed on this page: Click on the "..." button next to the first line of the commit message. All good for additional details to go into commit messages, that way they're stored in `git` itself. Thanks for the addition. If `valgrind` is also available on Mac, I'd expect the interface to be exactly the same, so there shouldn't be any need for modification there.

**Pull request merged**
