### PR TITLE
Alternative handling for abs

### PR DESCRIPTION
**Pull request by jdtournier**
This is an alternative solution to #1247, which was already addressed in #1299. My concern is that relying on the built-in `std::abs()` calls means casting from unsigned to signed versions of each variant. This is probably fine for most operations, but it is [technically ill-defined](http://en.cppreference.com/w/cpp/numeric/math/abs) if the integer can't be promoted to something that can't handle the precision of the original. This solution means we have our own `MR::abs()` call, and rely on SFINAE to call the built-in `std::abs()` call unless the type is unsigned. This seems to work on Linux, currently building on Windows (no errors so far... :crossed_fingers:)

### CODE REVIEW

**Comment by jdtournier** [comment]
OK, confirmed this builds with no warning on MSYS2. Checks out OK on macOS as well, according to TravisCI, but can't tell whether there are any warnings, since it's build with `-nowarnings`...

**Comment by maxpietsch** [comment]
:+1: All good in macOS, no warnings and tests pass.

**Comment by Lestropie** [comment]
Figured if you're going to go to the effort of editing every single usage, might as well use CI to make sure it doesn't get used again.

> ... can't tell whether there are any warnings, since it's build with `-nowarnings`...

Should these be `Werror` rather than `-nowarnings`? I'd rather be cleaning up compiler warnings as soon as they arise.

**Comment by jdtournier** [comment]
> Figured if you're going to go to the effort of editing every single usage, might as well use CI to make sure it doesn't get used again.

:+1:

> Should these be Werror rather than -nowarnings? I'd rather be cleaning up compiler warnings as soon as they arise.

I think `-Werror` is a bit OTT... It would be nice to be notified of warnings though. The reason we introduced this flag was that sometimes there were so many warnings that the job output exceeded the max size allowed by TravisCI. One way around this would be to at least have the build script record the fact that warnings were produced (i.e.the gcc stderr/stdout was non-empty), make a note of that in the output, and `cat build.log` so it can be inspected (all warnings are always captured in there). Worth doing?

**Comment by jdtournier** [comment]
> One way around this would be to at least have the build script record the fact that warnings were produced (i.e.the gcc stderr/stdout was non-empty), make a note of that in the output, and cat build.log so it can be inspected (all warnings are always captured in there). Worth doing?

Actually, thinking about this, I don't see that this would be any different from compiling without the `-nowarnings` flag... Maybe that's what we should do?

**Comment by maxpietsch** [comment]
I think the SFINAE fails for MR::Image types. I get warnings for lines 307, 308, and 325 in `fixel2voxel`:

```
cmd/fixel2voxel.cpp:307:29: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
        if (!f.padding() && abs (data.value()) > absmax)
```

**Comment by Lestropie** [comment]
> I think the SFINAE fails for MR::Image types.

[Reproduced](https://travis-ci.org/MRtrix3/mrtrix3/jobs/376650684). Given the compiler hint:
```
cmd/fixel2voxel.cpp:307:29: note: use function 'std::abs' instead
```
, it seems that on OSX there is a function `abs<int>()` defined in default namespace (i.e. *not* in `std::`), which is being selected in preference to `MR::abs<float>()`. Solution can be pursued as part of #1329.

**Pull request merged**
