### PR TITLE
Connectome tool list

### LINKED ISSUE #320: Connectome tool: 'Primary' matrix file list view
Hopefully this will give an appropriate compromise between users not being able to figure out the logic behind the tool, and me not wanting to lose functionality I need by simplifying the initial entry point.

Have a list view where matrix files can be loaded, but only one selected at a time. Relevant visual properties can be set through their comboboxes via the 'primary connectome' (i.e. the matrix file selected), or an external matrix file (as is done currently). If the selected 'primary connectome' (lemme know if you think of a better term) changes, all relevant visual properties update.

Importantly, set certain edge-wise visual properties such as edge visibility and edge colour should be set to this by default; so when someone opens a connectome file, they immediately get some sensible visualisation of it. But these properties can also be set via external files that are independent of the particular connectome currently selected.

Also, change the current command-line option for this tool to `-connectome.init` (where the parcellation file must be passed), and `connectome.load` can then be used to load matrix files.

### PR DESCRIPTION
**Pull request by Lestropie**
Enhancing the connectome tool to hopefully make the initial entry point a bit easier for users: Initialise using the parcellation image, load a connectome, and you can see the connectome (with somewhat sensible defaults). Also gives the possibility of scrolling through a set of connectomes (though I still need to enable use of the keyboard arrows in the QListView).

But throwing it up here now in case someone wants to take up the challenge of breaking it, or has any other comments about the UI design, e.g. in #320.

Closes #320.

### CODE REVIEW

**Comment by chunhungyeh** [comment]
Verified on MacOSX. The only issue that I have on my laptop is that the current layout of the connectome tool is too long. See the attached image of my screenshot: I could not see the connectome node list unless I undocked the window. Perhaps it might be good to decrease the font size or gap between the parameters, or even make the 'node visualisation' and 'edge visualisation' sections foldable?
 
screen shot 2015-08-17 at 8 56 11 am

**Comment by Lestropie** [comment]
Hmmm, looks like the vertical spacing in the grid layout is larger on your system, even though it's set explicitly. Either that or it's adding some space where there are empty rows. I'll have to play with this on a Mac.

I also need to move the LUT loading back out from the node colouring to the main setup. In cases where the atlas is already provided with sequential indices from 1, there's no need to provide a config file, you can just provide the LUT to get both node names and colours. So I might reconsider moving that and the config file load out of the 'basic setup' to somewhere else.

I can also potentially lose the 'node selection' label, and replace it with a button (with an appropriate icon) right near the top.

I have commented previously that I would like to make a foldable group box; added as Issue #325.

**Comment by Lestropie** [comment]
OK, just did a little bit of fiddling of the UI ordering. Should be able to merge this independently of the `updated_syntax` work without too much drama.

@chunhungyeh We need to look at what's going on on your Mac.

**Comment by Lestropie** [comment]
OK @chunhungyeh: Give that a spin, see if it further reduces the tool sizing issue on Mac.

**Pull request merged**
